<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiaGioiHanhChinhSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $data = [
            ['ma_gis' => '0', 'phuong_xa' => 'Xã Bình Đông', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '1', 'phuong_xa' => 'Xã Bình Xuân', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '2', 'phuong_xa' => 'Phường Long Chánh', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '3', 'phuong_xa' => 'Phường Long Hòa', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '4', 'phuong_xa' => 'Phường Long Hưng', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '5', 'phuong_xa' => 'Phường Long Thuận', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '6', 'phuong_xa' => 'Phường 1', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '7', 'phuong_xa' => 'Phường 2', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '8', 'phuong_xa' => 'Phường 5', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '9', 'phuong_xa' => 'Xã Tân Trung', 'huyen_tp' => 'Thị xã Gò Công', 'ghi_chu' => ''],
            ['ma_gis' => '10', 'phuong_xa' => 'Xã Mỹ Hạnh Đông', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '11', 'phuong_xa' => 'Xã Mỹ Hạnh Trung', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '12', 'phuong_xa' => 'Xã Mỹ Phước Tây', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '13', 'phuong_xa' => 'Phường Nhị Mỹ', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '14', 'phuong_xa' => 'Xã Nhị Quý', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '15', 'phuong_xa' => 'Phường 1', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '16', 'phuong_xa' => 'Phường 2', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '17', 'phuong_xa' => 'Phường 3', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '18', 'phuong_xa' => 'Phường 4', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '19', 'phuong_xa' => 'Phường 5', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '20', 'phuong_xa' => 'Xã Phú Quý', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '21', 'phuong_xa' => 'Xã Tân Bình', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '22', 'phuong_xa' => 'Xã Tân Hội', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '23', 'phuong_xa' => 'Xã Tân Phú', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '24', 'phuong_xa' => 'Xã Thanh Hòa', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '25', 'phuong_xa' => 'Xã Long Khánh', 'huyen_tp' => 'Thị xã Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '26', 'phuong_xa' => 'Xã Đạo Thạnh', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '27', 'phuong_xa' => 'Xã Mỹ Phong', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '28', 'phuong_xa' => 'Xã Phước Thạnh', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '29', 'phuong_xa' => 'Phường 1', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '30', 'phuong_xa' => 'Phường 10', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '31', 'phuong_xa' => 'Phường 2', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '32', 'phuong_xa' => 'Phường 3', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '33', 'phuong_xa' => 'Phường 4', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '34', 'phuong_xa' => 'Phường 5', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '35', 'phuong_xa' => 'Phường 6', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '36', 'phuong_xa' => 'Phường 7', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '37', 'phuong_xa' => 'Phường 8', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '38', 'phuong_xa' => 'Phường 9', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '39', 'phuong_xa' => 'Phường Tân Long', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '40', 'phuong_xa' => 'Xã Tân Mỹ Chánh', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '41', 'phuong_xa' => 'Xã Thới Sơn', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '42', 'phuong_xa' => 'Xã Trung An', 'huyen_tp' => 'Thành phố Mỹ Tho', 'ghi_chu' => ''],
            ['ma_gis' => '43', 'phuong_xa' => 'Xã Thạnh Tân', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '44', 'phuong_xa' => 'Xã Thạnh Mỹ', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '45', 'phuong_xa' => 'Xã Thạnh Hoà', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '46', 'phuong_xa' => 'Xã Tân Lập 2', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '47', 'phuong_xa' => 'Xã Tân Lập 1', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '48', 'phuong_xa' => 'Xã Tân Hòa Thành', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '49', 'phuong_xa' => 'Xã Tân Hòa Tây', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '50', 'phuong_xa' => 'Xã Tân Hòa Đông', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '51', 'phuong_xa' => 'Xã Phước Lập', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '52', 'phuong_xa' => 'Xã Phú Mỹ', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '53', 'phuong_xa' => 'Xã Hưng Thạnh', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => ''],
            ['ma_gis' => '54', 'phuong_xa' => 'Xã Tân Thới', 'huyen_tp' => 'Huyện Tân Phú Đông', 'ghi_chu' => ''],
            ['ma_gis' => '55', 'phuong_xa' => 'Xã Tân Thạnh', 'huyen_tp' => 'Huyện Tân Phú Đông', 'ghi_chu' => ''],
            ['ma_gis' => '56', 'phuong_xa' => 'Xã Tân Phú', 'huyen_tp' => 'Huyện Tân Phú Đông', 'ghi_chu' => ''],
            ['ma_gis' => '57', 'phuong_xa' => 'Xã Phú Thạnh', 'huyen_tp' => 'Huyện Tân Phú Đông', 'ghi_chu' => ''],
            ['ma_gis' => '58', 'phuong_xa' => 'Xã Phú Tân', 'huyen_tp' => 'Huyện Tân Phú Đông', 'ghi_chu' => ''],
            ['ma_gis' => '59', 'phuong_xa' => 'Xã Phú Đông', 'huyen_tp' => 'Huyện Tân Phú Đông', 'ghi_chu' => ''],
            ['ma_gis' => '60', 'phuong_xa' => 'Xã Yên Luông', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '61', 'phuong_xa' => 'Xã Vĩnh Hựu', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '62', 'phuong_xa' => 'Thị trấn Vĩnh Bình', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '63', 'phuong_xa' => 'Xã Thạnh Trị', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '64', 'phuong_xa' => 'Xã Thạnh Nhựt', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '65', 'phuong_xa' => 'Xã Thành Công', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '66', 'phuong_xa' => 'Xã Long Vĩnh', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '67', 'phuong_xa' => 'Xã Long Bình', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '68', 'phuong_xa' => 'Xã Đồng Thạnh', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '69', 'phuong_xa' => 'Xã Đồng Sơn', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '70', 'phuong_xa' => 'Xã Bình Tân', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '71', 'phuong_xa' => 'Xã Bình Phú', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '72', 'phuong_xa' => 'Xã Bình Nhì', 'huyen_tp' => 'Huyện Gò Công Tây', 'ghi_chu' => ''],
            ['ma_gis' => '73', 'phuong_xa' => 'Xã Bình Ân', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '74', 'phuong_xa' => 'Xã Bình Nghị', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '75', 'phuong_xa' => 'Xã Gia Thuận', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '76', 'phuong_xa' => 'Xã Kiểng Phước', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '77', 'phuong_xa' => 'Xã Phước Trung', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '78', 'phuong_xa' => 'Xã Tân Điền', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '79', 'phuong_xa' => 'Xã Tân Đông', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '80', 'phuong_xa' => 'Xã Tăng Hoà', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '81', 'phuong_xa' => 'Xã Tân Phước', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '82', 'phuong_xa' => 'Xã Tân Tây', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '83', 'phuong_xa' => 'Xã Tân Thành', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '84', 'phuong_xa' => 'Thị trấn Vàm Láng', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '85', 'phuong_xa' => 'Thị trấn Tân Hòa', 'huyen_tp' => 'Huyện Gò Công Đông', 'ghi_chu' => ''],
            ['ma_gis' => '86', 'phuong_xa' => 'Xã Xuân Đông', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '87', 'phuong_xa' => 'Xã Tân Thuận Bình', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '88', 'phuong_xa' => 'Xã Song Bình', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '89', 'phuong_xa' => 'Xã Quơn Long', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '90', 'phuong_xa' => 'Xã Long Bình Điền', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '91', 'phuong_xa' => 'Xã Hòa Định', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '92', 'phuong_xa' => 'Xã Đăng Hưng Phước', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '93', 'phuong_xa' => 'Xã Bình Phục Nhứt', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '94', 'phuong_xa' => 'Xã Bình Phan', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '95', 'phuong_xa' => 'Xã Bình Ninh', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '96', 'phuong_xa' => 'Xã An Thạnh Thủy', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '97', 'phuong_xa' => 'Xã Trung Hòa', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '98', 'phuong_xa' => 'Xã Thanh Bình', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '99', 'phuong_xa' => 'Xã Tân Bình Thạnh', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '100', 'phuong_xa' => 'Xã Phú Kiết', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '101', 'phuong_xa' => 'Xã Mỹ Tịnh An', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '102', 'phuong_xa' => 'Xã Lương Hòa Lạc', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '103', 'phuong_xa' => 'Xã Hòa Tịnh', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '104', 'phuong_xa' => 'Thị trấn Chợ Gạo', 'huyen_tp' => 'Huyện Chợ Gạo', 'ghi_chu' => ''],
            ['ma_gis' => '105', 'phuong_xa' => 'Xã Bàn Long', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '106', 'phuong_xa' => 'Xã Bình Đức', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '107', 'phuong_xa' => 'Xã Bình Trưng', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '108', 'phuong_xa' => 'Xã Điềm Hy', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '109', 'phuong_xa' => 'Xã Đông Hòa', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '110', 'phuong_xa' => 'Xã Dưỡng Điềm', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '111', 'phuong_xa' => 'Xã Hữu Đạo', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '112', 'phuong_xa' => 'Xã Kim Sơn', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '113', 'phuong_xa' => 'Xã Long An', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '114', 'phuong_xa' => 'Xã Long Định', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '115', 'phuong_xa' => 'Xã Long Hưng', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '116', 'phuong_xa' => 'Xã Nhị Bình', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '117', 'phuong_xa' => 'Xã Phú Phong', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '118', 'phuong_xa' => 'Xã Song Thuận', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '119', 'phuong_xa' => 'Xã Tam Hiệp', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '120', 'phuong_xa' => 'Thị trấn Tân Hiệp', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '121', 'phuong_xa' => 'Xã Tân Hội Đông', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '122', 'phuong_xa' => 'Xã Tân Hương', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '123', 'phuong_xa' => 'Xã Tân Lý Đông', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '124', 'phuong_xa' => 'Xã Tân Lý Tây', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '125', 'phuong_xa' => 'Xã Thân Cửu Nghĩa', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '126', 'phuong_xa' => 'Xã Thạnh Phú', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '127', 'phuong_xa' => 'Xã Vĩnh Kim', 'huyen_tp' => 'Huyện Châu Thành', 'ghi_chu' => ''],
            ['ma_gis' => '128', 'phuong_xa' => 'Xã Tân Phong', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '129', 'phuong_xa' => 'Xã Tam Bình', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '130', 'phuong_xa' => 'Xã Phú Nhuận', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '131', 'phuong_xa' => 'Xã Phú An', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '132', 'phuong_xa' => 'Xã Ngũ Hiệp', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '133', 'phuong_xa' => 'Xã Mỹ Long', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '134', 'phuong_xa' => 'Xã Long Trung', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '135', 'phuong_xa' => 'Xã Long Tiên', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '136', 'phuong_xa' => 'Xã Hội Xuân', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '137', 'phuong_xa' => 'Xã Hiệp Đức', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '138', 'phuong_xa' => 'Xã Cẩm Sơn', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '139', 'phuong_xa' => 'Xã Bình Phú', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '140', 'phuong_xa' => 'Xã Thạnh Lộc', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '141', 'phuong_xa' => 'Xã Phú Cường', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '142', 'phuong_xa' => 'Xã Mỹ Thành Nam', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '143', 'phuong_xa' => 'Xã Mỹ Thành Bắc', 'huyen_tp' => 'Huyện Cai Lậy', 'ghi_chu' => ''],
            ['ma_gis' => '144', 'phuong_xa' => 'Xã An Cư', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '145', 'phuong_xa' => 'Xã An Hữu', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '146', 'phuong_xa' => 'Xã An Thái Đông', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '147', 'phuong_xa' => 'Xã An Thái Trung', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '148', 'phuong_xa' => 'Xã Đông Hòa Hiệp', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '149', 'phuong_xa' => 'Xã Hậu Mỹ Bắc A', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '150', 'phuong_xa' => 'Xã Hậu Mỹ Bắc B', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '151', 'phuong_xa' => 'Xã Hậu Mỹ Phú', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '152', 'phuong_xa' => 'Xã Hậu Mỹ Trinh', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '153', 'phuong_xa' => 'Xã Hậu Thành', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '154', 'phuong_xa' => 'Xã Hòa Hưng', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '155', 'phuong_xa' => 'Xã Hòa Khánh', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '156', 'phuong_xa' => 'Xã Mỹ Đức Đông', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '157', 'phuong_xa' => 'Xã Mỹ Đức Tây', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '158', 'phuong_xa' => 'Xã Mỹ Hội', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '159', 'phuong_xa' => 'Xã Mỹ Lợi A', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '160', 'phuong_xa' => 'Xã Mỹ Lợi B', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '161', 'phuong_xa' => 'Xã Mỹ Lương', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '162', 'phuong_xa' => 'Xã Mỹ Tân', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '163', 'phuong_xa' => 'Xã Mỹ Trung', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '164', 'phuong_xa' => 'Xã Tân Hưng', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '165', 'phuong_xa' => 'Xã Tân Thanh', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '166', 'phuong_xa' => 'Xã Thiện Trí', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '167', 'phuong_xa' => 'Xã Thiện Trung', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '168', 'phuong_xa' => 'Thị trấn Cái Bè', 'huyen_tp' => 'Huyện Cái Bè', 'ghi_chu' => ''],
            ['ma_gis' => '169', 'phuong_xa' => 'Thị trấn Mỹ Phước', 'huyen_tp' => 'Huyện Tân Phước', 'ghi_chu' => '']
        ];

        // Nhập dữ liệu vào bảng
        DB::table('q_l_dia_gioi_hanh_chinh_t_g_s')->insert($data);
    }
}
