// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define(["exports","../../../../../core/mathUtils","../../../../../core/libs/gl-matrix-2/factories/vec3f64","../../lib/triangleIntersectionUtils"],function(H,J,K,L){function I(a,b,c,e){a*=4;const l=e[a+0+b];return e[a+2+b]<c?-1:l>c?1:0}class M{constructor(a,b){this.elementCount=a;this.model=b;this._elementIndexMap=null;this._bspNodes=[];this._generatedBVH=!1;this.localMode=b.localMode;this.planetCenterZ=b.planetCenterZ;this.geometryMinZ=b.geometryMinZ;this.planetCenter=K.fromValues(0,0,this.planetCenterZ);
this.maxBspNodeDepth=b.maxBspNodeDepth??8;this.minElementCountForBVH=b.minElementCountForBVH??15;this.minBspNodeElementCount=b.minBspNodeElementCount??5}get elementIndexMap(){this._ensureBVH();return this._elementIndexMap}get _skipBVH(){return this.elementCount<this.minElementCountForBVH||this.geometryMinZ<.5*this.planetCenterZ}_ensureBVH(){this._generatedBVH||this._skipBVH||0===this._bspNodes.length&&this._generateBsp()}intersectRay(a,b,c){1>this.elementCount||(this._skipBVH?this._intersectRayWithoutBVH(c):
this._intersectRayWithBVH(a,b,c))}_intersectRayWithoutBVH(a){this._intersectRange(0,this.elementCount)}_intersectRange(a,b){this.model.intersectRange(a,b)}_intersectRayWithBVH(a,b,c){this._ensureBVH();c?this._intersectGeometryWithBVHVerticalRay(a):this._intersectGeometryWithBVHGeneralRay(a,b)}_intersectGeometryWithBVHVerticalRay(a){let b=a[0];var c=a[1];if(!this.localMode){const {geometryMinZ:l,planetCenterZ:d}=this;c=(l-d)/(a[2]-d);b=a[0]*c;c*=a[1]}({_bspNodes:a}=this);for(var e=0;0<=e;){e=a[e];
const {d:l,dim:d,minIndexIndex:p,minMidIndexIndex:f,maxMidIndexIndex:q,maxIndexIndex:A,aabb2D:g}=e;if(b<g[0]||b>g[2]||c<g[1]||c>g[3])break;if(-1===d||-1===e.child0&&-1===e.child1){this._intersectRange(p,A);break}else{this._intersectRange(f,q);const u=(0===d?b:c)-l;if(0>u){if(-1===e.child0){this._intersectRange(p,f);break}e=e.child0}else if(0<u){if(-1===e.child1){this._intersectRange(q,A);break}e=e.child1}else break}}}_intersectGeometryWithBVHGeneralRay(a,b){var c=a[0],e=a[1],l=b[0],d=b[1],{geometryMinZ:p}=
this;if(!this.localMode){d=0;var f=1;c=Math.min(.5*this.planetCenterZ,p);e=a[2];l=b[2];if(e<c&&l<c)return;e<c&&(d=(c-e)/(l-e));l<c&&(f=(c-e)/(l-e));if(d>f)return;c=(1-d)*a[0]+d*b[0];e=(1-d)*a[1]+d*b[1];var q=(1-d)*a[2]+d*b[2];l=(1-f)*a[0]+f*b[0];d=(1-f)*a[1]+f*b[1];a=(1-f)*a[2]+f*b[2];({planetCenterZ:b}=this);p-=b;f=p/(q-b);c*=f;e*=f;p/=a-b;l*=p;d*=p}p=l-c;a=d-e;b=this._bspNodes;let A=1;({aabb2D:d}=b[0]);l=(w,v,z,x)=>{if(Math.abs(v)<1E-5*Math.max(x-z,1))return!1;const r=0<v;z=r?x:z;x=w+A*v;return(r?
x<z:x>z)?(A=Math.max((z-w)/v,A),!0):!1};Math.abs(p)>=Math.abs(a)?l(c,p,d[0],d[2])||l(e,a,d[1],d[3]):l(e,a,d[1],d[3])||l(c,p,d[0],d[2]);d=[0,0,A];for(l=0;l<d.length;){var g=d[l];f=d[l+1];q=d[l+2];l+=3;if(f>q)continue;g=b[g];const {minIndexIndex:w,maxIndexIndex:v}=g,{child0:z,child1:x,minMidIndexIndex:r,maxMidIndexIndex:m,aabb2D:k,d:t,dim:y}=g;var u=c+f*p,h=c+q*p;g=Math.min(u,h);u=Math.max(u,h);var n=k[0];h=k[2];if(!(u<n||h<g||(g<n&&(g=(n-c)/p,0<p?f=Math.max(f,g):q=Math.min(q,g)),h<u&&(g=(h-c)/p,0<
p?q=Math.min(q,g):f=Math.max(f,g)),u=e+f*a,h=e+q*a,g=Math.min(u,h),u=Math.max(u,h),n=k[1],h=k[3],u<n||h<g)))if(g<n&&(g=(n-e)/a,0<a?f=Math.max(f,g):q=Math.min(q,g)),h<u&&(g=(h-e)/a,0<a?q=Math.min(q,g):f=Math.max(f,g)),-1===z&&-1===x)this._intersectRange(w,v);else{h=0===y?c:e;g=0===y?p:a;n=h+f*g;const B=h+q*g;u=Math.min(n,B);n=Math.max(n,B);h=J.clamp((t-h)/g,0,A);w<r&&u<=t&&(-1!==z?(d.push(z),d.push(0<=g?f:Math.max(f,h)),d.push(0<=g?Math.min(q,h):q)):this._intersectRange(w,r));this._intersectRange(r,
m);m<v&&t<=n&&(-1!==x?(d.push(x),d.push(0<=g?Math.max(f,h):f),d.push(0<=g?q:Math.min(q,h))):this._intersectRange(m,v))}}}_generateBsp(){var {elementCount:a}=this;if(!(1>a)){var b=L.createUintArray(a,a);this._elementIndexMap=b;for(var c=0;c<a;++c)b[c]=c;var e=this.model.getAabbs2D();c=0;var l=this._bspNodes;l.length=0;var {localMode:d}=this,p=!1;if(!d){const {planetCenterZ:h,geometryMinZ:n}=this;p=0<=h||n<.5*h}var f=[],q=(h,n,w,v,z)=>{f.push(h);f.push(n);f.push(w);f.push(0>v?-1:(z?0:1)+2*v)},{maxBspNodeDepth:A,
minBspNodeElementCount:g}=this,u=(h,n,w,v,z)=>{const x=l.length;if(!(0<x&&(p||w>=A||n-h<g))){var r=[0,0,0,0],m=Infinity,k=Infinity,t=-Infinity,y=-Infinity;for(var B=h;B<n;++B){const C=4*b[B];m=Math.min(m,e[C+0]);k=Math.min(k,e[C+1]);t=Math.max(t,e[C+2]);y=Math.max(y,e[C+3])}r[0]=m;r[1]=k;r[2]=t;r[3]=y;d?(m=r[0],k=r[1],t=r[2],y=r[3],t-m>=y-k?(k=.5*(m+t),m=0):(k=.5*(k+y),m=1),m={d:k,dim:m}):(k=r[0],t=r[1],y=r[2],B=r[3],y-k>=B-t?(m=0,k=.5*(k+y)):(m=1,k=.5*(t+B)),m={dim:m,d:k});var {d:D,dim:E}=m;k=h;
for(m=n;k<m;)t=b[k],0>I(t,E,D,e)?++k:(--m,b[k]=b[m],b[m]=t);m=k;for(t=n;k<t;)y=b[t-1],0<I(y,E,D,e)?--t:(b[t-1]=b[k],b[k]=y,++k);var {rangeMidStart:F,rangeMidEnd:G}={rangeMidStart:m,rangeMidEnd:t};k=w===A-1;m=!k&&F>=h+g;k=!k&&n>=G+g;if(m||k||0===x)r=new N(h,F,G,n,E,D,r),m&&q(h,F,w+1,x,!0),k&&q(G,n,w+1,x,!1),l.push(r),-1!==v&&(h=l[v],z?h.child0=x:h.child1=x)}};for(q(0,a,0,-1,!1);c<f.length;){a=f[c];const h=f[c+1],n=f[c+2],w=f[c+3];c+=4;const v=w>>1;u(a,h,n,v,0===w-(v<<1))}this._generatedBVH=!0}}}class N{constructor(a,
b,c,e,l,d,p){this.minIndexIndex=a;this.minMidIndexIndex=b;this.maxMidIndexIndex=c;this.maxIndexIndex=e;this.dim=l;this.d=d;this.aabb2D=p;this.child1=this.child0=-1}}H.ElevationAgnosticBVH=M;Object.defineProperty(H,Symbol.toStringTag,{value:"Module"})});