// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../../Color ../../../../../core/colorUtils ../../../../../core/Evented ../../../../../core/handleUtils ../../../../../core/has ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../core/reactiveUtils ../../../../../core/libs/gl-matrix-2/math/mat4 ../../../../../core/libs/gl-matrix-2/factories/mat4f64 ../../../../../chunks/vec32 ../../../../../core/libs/gl-matrix-2/factories/vec3f64 ../../Manipulator3D ../../manipulatorUtils ../../RenderObject ../dragEventPipeline3D ../ManipulatorType ../settings ./config ./Manipulation ./moveUtils ../../../webgl-engine/lib/GeometryUtil ../../../webgl-engine/lib/Material ../../../../interactive/dragEventPipeline ../../../../interactive/interfaces".split(" "),
function(w,E,F,G,H,U,I,J,K,x,L,l,q,M,u,m,N,y,O,v,P,Q,z,A,B,n){function p(a,d,b){a=F.darken(a,b);a.a*=d;return E.toUnitRGBA(a)}class R extends P.Manipulation{constructor(a){super();this._radius=v.discRadius;this.events=new G;this._tool=a.tool;this._view=a.view;const d=new O.Settings({getTheme:()=>this._view.effectiveTheme});this._settings=d;null!=a.radius&&(this._radius=a.radius);a=this._view.effectiveTheme.accentColor;this._materials={materialUnfocused:u.createManipulatorMaterial(p(a,1,.25),A.RenderOccludedFlag.Occlude),
materialFocused:u.createManipulatorMaterial(p(a,1,0),A.RenderOccludedFlag.Occlude),materialOccludedUnfocused:u.createManipulatorMaterial(p(a,.7,0),d.zManipulator.renderOccluded),materialOccludedFocused:u.createManipulatorMaterial(p(a,.85,0),d.zManipulator.renderOccluded)};this._themeHandle=K.watch(()=>this._view.effectiveTheme.accentColor,b=>{const c=p(b,1,.25),e=p(b,1,0),k=p(b,.7,0);b=p(b,.85,0);const {materialUnfocused:h,materialFocused:f,materialOccludedUnfocused:g,materialOccludedFocused:r}=this._materials;
h.setParameters({color:c});f.setParameters({color:e});g.setParameters({color:k});r.setParameters({color:b})});this._createManipulator();this.forEachManipulator(b=>this._tool.manipulators.add(b))}destroy(){this._themeHandle=J.removeMaybe(this._themeHandle);this._manipulator.applyObjectTransform=S;this.forEachManipulator(a=>{this._tool.manipulators.remove(a);a.destroy()})}forEachManipulator(a){a(this._manipulator,y.ManipulatorType.TRANSLATE_Z)}createManipulatedObjectDragPipeline(a,d,b){if(!d.operations)return H.makeHandle();
const c=d.operations.data.spatialReference;return Q.createManipulatedMoveDragPipeline(d,b,e=>this.createDragPipeline((k,h,f,g,r)=>{({steps:h,cancel:f}=a(k,h,f,g,r));return e(k,h,f)},c))}createDragPipeline(a,d){const b=this._view;return B.createManipulatorDragEventPipeline(this._manipulator,(c,e,k,h,f)=>{e=e.next(g=>({...g,manipulatorType:y.ManipulatorType.TRANSLATE_Z})).next(N.screenToZConstrained(b,c.renderLocation,d)).next(B.addScreenDelta());a(c,e,k,h,f)})}get radius(){return this._radius}set radius(a){a!==
this._radius&&(this._radius=a,this._updateManipulator())}_updateManipulator(){var a=this._settings,d=this._radius/v.discRadius,b=a.zManipulator.height*d,c=a.zManipulator.coneHeight*d;const e=a.zManipulator.coneWidth*d;a=a.zManipulator.width*d;const k=[q.fromValues(0,0,0),q.fromValues(0,0,b)];d=[q.fromValues(0,0,0),q.fromValues(0,0,b+c)];const h=L.create();x.translate(h,h,[0,0,b]);x.rotateX(h,h,Math.PI/2);const {materialUnfocused:f,materialFocused:g,materialOccludedUnfocused:r,materialOccludedFocused:C}=
this._materials;b=z.createTubeGeometry(f,k,a/2,16,!1);c=z.createConeGeometry(f,c,e/2,16,!1);c.transformation=h;this._manipulator.renderObjects=[new m.RenderObject(c,n.ManipulatorStateFlags.Unfocused),new m.RenderObject(b,n.ManipulatorStateFlags.Unfocused),new m.RenderObject(c.instantiate({material:g}),n.ManipulatorStateFlags.Focused),new m.RenderObject(b.instantiate({material:g}),n.ManipulatorStateFlags.Focused),new m.RenderObject(c.instantiate({material:r}),n.ManipulatorStateFlags.Unfocused),new m.RenderObject(b.instantiate({material:r}),
n.ManipulatorStateFlags.Unfocused),new m.RenderObject(c.instantiate({material:C}),n.ManipulatorStateFlags.Focused),new m.RenderObject(b.instantiate({material:C}),n.ManipulatorStateFlags.Focused)];this._manipulator.radius=a/2+2;this._manipulator.collisionType={type:"line",paths:[d]}}_createManipulator(){const a=this._view,d=new M.Manipulator3D({view:a,autoScaleRenderObjects:!1,worldSized:!1,selectable:!1,cursor:"ns-resize",elevationInfo:this.elevationInfo,worldOriented:!0,collisionPriority:1.6});d.applyObjectTransform=
b=>{var c=a.state.camera,e=D;a.renderCoordsHelper.toRenderCoords(this._manipulator.elevationAlignedLocation,e);const k=l.dist(c.eye,e),h=c.computeRenderPixelSizeAtDist(k);var f=l.subtract(t,e,c.eye);l.normalize(f,f);var g=T;a.renderCoordsHelper.worldUpAtPosition(D,g);e=Math.abs(l.dot(f,g));f=l.cross(t,f,g);g=l.cross(t,f,g);e=I.clamp(e,.01,1);c=1-Math.sqrt(1-e*e)/e/c.fullWidth;e=this._radius/v.discRadius*this._settings.zManipulator.width;l.scale(g,l.normalize(g,g),(1/c-1)*k+h*e);b[12]-=t[0];b[13]-=
t[1];b[14]-=t[2]};this._manipulator=d;this._updateManipulator()}get test(){}}const D=q.create(),t=q.create(),T=q.create(),S=()=>{};w.MoveZManipulation=R;Object.defineProperty(w,Symbol.toStringTag,{value:"Module"})});