// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../../Color ../../../../../core/Handles ../../../../../core/handleUtils ../../../../../core/has ../../../../../core/maybe ../../../../../core/reactiveUtils ../../../../../core/libs/gl-matrix-2/math/mat4 ../../../../../core/libs/gl-matrix-2/factories/mat4f64 ../../../../../chunks/vec32 ../../../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../../../geometry/support/vectorStacks ../../Manipulator3D ../../RenderObject ../dragEventPipeline3D ../ManipulatorType ./config ./Manipulation ./moveUtils ../snapping/SnapToScene ../../../webgl-engine/lib/basicInterfaces ../../../webgl-engine/lib/GeometryUtil ../../../webgl-engine/lib/Material ../../../webgl-engine/materials/ColorMaterial ../../../../interactive/dragEventPipeline ../../../../interactive/interfaces".split(" "),
function(r,z,A,B,Q,C,t,u,D,E,l,v,F,w,G,x,d,H,I,J,K,L,M,N,n,y){class O extends H.Manipulation{constructor(a){super();this._handles=new A;this._snapToScene=new J.SnapToScene;this._scale=1;this._radius=d.discRadius;this._view=a.view;this._tool=a.tool;this._discMaterial=this._createMaterial();this._discMaterialTransparent=this._createMaterial(.5);null!=a.snapToScene&&(this.snapToScene=a.snapToScene);null!=a.radius&&(this._radius=a.radius);this._createManipulator();this.forEachManipulator(b=>this._tool.manipulators.add(b))}destroy(){this._handles=
C.destroyMaybe(this._handles);this.forEachManipulator(a=>{this._tool.manipulators.remove(a);a.destroy()});this._manipulator=this._view=this._tool=null}forEachManipulator(a){a(this._manipulator,x.ManipulatorType.TRANSLATE_XY)}get displayScale(){return this._scale}set displayScale(a){this._scale=a;this._updateManipulatorTransform()}get snapToScene(){return this._snapToScene.enabled}set snapToScene(a){this._snapToScene.enabled=a}get radius(){return this._radius}set radius(a){a!==this._radius&&(this._radius=
a,this._updateManipulator())}get discManipulator(){return this._manipulator}createManipulatedObjectDragPipeline(a,b,c){if(!b.operations)return B.makeHandle();const p=b.graphic,e=b.elevationInfo,f=b.operations.data.spatialReference;return I.createManipulatedMoveDragPipeline(b,c,g=>this.createDragPipeline((m,h,k,q,P)=>{({steps:h,cancel:k}=a(m,h,k,q,P));return g(m,h,k)},e,f,p))}createDragPipeline(a,b,c,p){const e=this._view;return n.createManipulatorDragEventPipeline(this._manipulator,(f,g,m,h,k)=>{g=
g.next(n.dragAtLocation(e,f.elevationAlignedLocation)).next(G.screenToMapXYAtLocation(e,f.elevationAlignedLocation,b,c,p)).next(...this._snapToScene.createDragEventPipelineStep(e,b)).next(q=>({...q,manipulatorType:x.ManipulatorType.TRANSLATE_XY})).next(n.addScreenDelta());a(f,g,m,h,k)})}_updateManipulatorTransform(){const a=u.fromScaling(v.sm4d.get(),E.set(v.sv3d.get(),this.displayScale,this.displayScale,this.displayScale));this._manipulator.modelTransform=a}_createManipulator(){this._manipulator=
new F.Manipulator3D({view:this._view,worldSized:!1,autoScaleRenderObjects:!1,focusMultiplier:1,touchMultiplier:1,collisionType:{type:"disc",direction:l.fromValues(0,0,1)},worldOriented:!0});this._updateManipulator()}_updateManipulator(){const a=L.createCylinderGeometry(this._discMaterial,d.discHeight,1,d.geometrySegments,l.fromValues(0,0,1),l.fromValues(0,0,0));a.transformation=u.fromScaling(D.create(),l.fromValues(this._radius,this._radius,this._radius));this._manipulator.renderObjects=[new w.RenderObject(a,
y.ManipulatorStateFlags.Focused),new w.RenderObject(a.instantiate({material:this._discMaterialTransparent}),y.ManipulatorStateFlags.Unfocused)];this._manipulator.radius=this._radius/d.discRadius*d.discCollisionRadius}_createMaterial(a=1){const b=new N.ColorMaterial({cullFace:K.CullFaceOptions.Back,renderOccluded:M.RenderOccludedFlag.Transparent,isDecoration:!0});this._handles.add(t.watch(()=>z.toUnitRGBA(this._view.effectiveTheme.accentColor),c=>{c[3]*=a;b.setParameters({color:c})},t.initial));return b}get test(){}}
r.MoveXYDiscManipulation=O;Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});