// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define(["exports","./_commonjsHelpers"],function(pd,W){var va={exports:{}};(function(qd,Ed){(function(){var Dd=(()=>{var la="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename&&(la||=__filename);return function(rd={}){function wa(){var a=ea.buffer;b.HEAP8=P=new Int8Array(a);b.HEAP16=fa=new Int16Array(a);b.HEAPU8=Q=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAP32=F=new Int32Array(a);b.HEAPU32=R=new Uint32Array(a);b.HEAPF32=ha=new Float32Array(a);b.HEAPF64=
ia=new Float64Array(a)}function V(a){a="Aborted("+a+")";X(a);xa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma(a);throw a;}function sd(){if(!"pe-wasm.wasm".startsWith("data:application/octet-stream;base64,")){var a=b.locateFile?b.locateFile("pe-wasm.wasm",O):O+"pe-wasm.wasm";return a}return"pe-wasm.wasm"}function ya(a){if(a==na&&oa)return new Uint8Array(oa);if(pa)return pa(a);throw"both async and sync fetching of the wasm failed";}function td(a){if(za||ja){if("function"==
typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(c=>{if(!c.ok)throw`failed to load wasm binary file at '${a}'`;return c.arrayBuffer()}).catch(()=>ya(a));if(qa)return new Promise((c,d)=>{qa(a,g=>c(new Uint8Array(g)),d)})}return Promise.resolve().then(()=>ya(a))}function Aa(a,c,d){return td(a).then(g=>WebAssembly.instantiate(g,c)).then(d,g=>{X(`failed to asynchronously prepare wasm: ${g}`);V(g)})}function ud(a,c,d,g){return"function"!=typeof WebAssembly.instantiateStreaming||
c.startsWith("data:application/octet-stream;base64,")||c.startsWith("file://")||Ba||"function"!=typeof fetch?Aa(c,d,g):fetch(c,{credentials:"same-origin"}).then(h=>WebAssembly.instantiateStreaming(h,d).then(g,function(l){X(`wasm streaming compile failed: ${l}`);X("falling back to ArrayBuffer instantiation");return Aa(c,d,g)}))}function Ca(){if(!(0<Y)){for(var a=vd;0<a.length;)a.shift()(b);if(!(0<Y||ka||(ka=!0,b.calledRun=!0,xa))){for(a=Da;0<a.length;)a.shift()(b);Ea(b);for(a=wd;0<a.length;)a.shift()(b)}}}
function r(){}function Z(a){return(a||r).__cache__}function x(a,c){var d=Z(c),g=d[a];if(g)return g;g=Object.create((c||r).prototype);g.ptr=a;return d[a]=g}function ra(a){if("string"===typeof a){for(var c=0,d=0;d<a.length;++d){var g=a.charCodeAt(d);127>=g?c++:2047>=g?c+=2:55296<=g&&57343>=g?(c+=4,++d):c+=3}c=Array(c+1);aa(a,c,0,c.length);a=k.alloc(c,P);k.copy(c,P,a);return a}return a}function N(a){if("object"===typeof a){var c=k.alloc(a,P);k.copy(a,P,c);return c}return a}function v(){throw"cannot construct a PeObject, no constructor in IDL";
}function G(){throw"cannot construct a PeCoordsys, no constructor in IDL";}function S(){throw"cannot construct a VoidPtr, no constructor in IDL";}function D(){throw"cannot construct a PeDatum, no constructor in IDL";}function f(){throw"cannot construct a PeDefs, no constructor in IDL";}function H(){throw"cannot construct a PeFactory, no constructor in IDL";}function z(a,c,d,g,h,l){a&&"object"===typeof a&&(a=a.ptr);c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);g&&"object"===typeof g&&
(g=g.ptr);h&&"object"===typeof h&&(h=h.ptr);l&&"object"===typeof l&&(l=l.ptr);this.ptr=Fa(a,c,d,g,h,l);Z(z)[this.ptr]=this}function w(){throw"cannot construct a PeGeogcs, no constructor in IDL";}function t(){throw"cannot construct a PeGeogtran, no constructor in IDL";}function K(){throw"cannot construct a PeGTlistExtended, no constructor in IDL";}function J(){throw"cannot construct a PeGTlistExtendedEntry, no constructor in IDL";}function L(){throw"cannot construct a PeGTlistExtendedGTs, no constructor in IDL";
}function y(){throw"cannot construct a PeHorizon, no constructor in IDL";}function B(a){a&&"object"===typeof a&&(a=a.ptr);this.ptr=Ga(a);Z(B)[this.ptr]=this}function p(){throw"cannot construct a PeNotationMgrs, no constructor in IDL";}function u(){throw"cannot construct a PeNotationUtm, no constructor in IDL";}function I(){throw"cannot construct a PeParameter, no constructor in IDL";}function m(){throw"cannot construct a PePCSInfo, no constructor in IDL";}function E(){throw"cannot construct a PePrimem, no constructor in IDL";
}function q(){throw"cannot construct a PeProjcs, no constructor in IDL";}function A(){throw"cannot construct a PeSpheroid, no constructor in IDL";}function C(){throw"cannot construct a PeUnit, no constructor in IDL";}function T(){throw"cannot construct a PeVersion, no constructor in IDL";}var b=Object.assign({},rd),Ea,ma,xd=new Promise((a,c)=>{Ea=a;ma=c}),za="object"==typeof window,ja="function"==typeof importScripts,Ba="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,
Ha=Object.assign({},b),Ia="./this.program",O="";if(Ba){var Ja=require("fs"),Ka=require("path");O=__dirname+"/";var La=(a,c)=>{a=a.startsWith("file://")?new URL(a):Ka.normalize(a);return Ja.readFileSync(a,c?void 0:"utf8")};var pa=a=>{a=La(a,!0);a.buffer||(a=new Uint8Array(a));return a};var qa=(a,c,d,g=!0)=>{a=a.startsWith("file://")?new URL(a):Ka.normalize(a);Ja.readFile(a,g?void 0:"utf8",(h,l)=>{h?d(h):c(g?l.buffer:l)})};!b.thisProgram&&1<process.argv.length&&(Ia=process.argv[1].replace(/\\/g,"/"));
process.argv.slice(2)}else if(za||ja)ja?O=self.location.href:"undefined"!=typeof document&&document.currentScript&&(O=document.currentScript.src),la&&(O=la),O=O.startsWith("blob:")?"":O.substr(0,O.replace(/[?#].*/,"").lastIndexOf("/")+1),La=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},ja&&(pa=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),qa=(a,c,d)=>{var g=new XMLHttpRequest;g.open("GET",
a,!0);g.responseType="arraybuffer";g.onload=()=>{200==g.status||0==g.status&&g.response?c(g.response):d()};g.onerror=d;g.send(null)};var yd=console.log.bind(console),X=console.error.bind(console);Object.assign(b,Ha);Ha=null;var oa,ea,xa=!1,P,Q,fa,F,R,ha,ia,vd=[],Da=[],wd=[],Y=0,ba=null,na,Ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Na=(a,c,d)=>{var g=c+d;for(d=c;a[d]&&!(d>=g);)++d;if(16<d-c&&a.buffer&&Ma)return Ma.decode(a.subarray(c,d));for(g="";c<d;){var h=a[c++];if(h&128){var l=
a[c++]&63;if(192==(h&224))g+=String.fromCharCode((h&31)<<6|l);else{var n=a[c++]&63;h=224==(h&240)?(h&15)<<12|l<<6|n:(h&7)<<18|l<<12|n<<6|a[c++]&63;65536>h?g+=String.fromCharCode(h):(h-=65536,g+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else g+=String.fromCharCode(h)}return g},M=(a,c)=>a?Na(Q,a,c):"",aa=(a,c,d,g)=>{if(!(0<g))return 0;var h=d;g=d+g-1;for(var l=0;l<a.length;++l){var n=a.charCodeAt(l);if(55296<=n&&57343>=n){var U=a.charCodeAt(++l);n=65536+((n&1023)<<10)|U&1023}if(127>=n){if(d>=
g)break;c[d++]=n}else{if(2047>=n){if(d+1>=g)break;c[d++]=192|n>>6}else{if(65535>=n){if(d+2>=g)break;c[d++]=224|n>>12}else{if(d+3>=g)break;c[d++]=240|n>>18;c[d++]=128|n>>12&63}c[d++]=128|n>>6&63}c[d++]=128|n&63}}c[d]=0;return d-h},zd=[0,31,60,91,121,152,182,213,244,274,305,335],Ad=[0,31,59,90,120,151,181,212,243,273,304,334],sa={},ca=()=>{if(!ca.strings){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||
"C").replace("-","_")+".UTF-8",_:Ia||"./this.program"},c;for(c in sa)void 0===sa[c]?delete a[c]:a[c]=sa[c];var d=[];for(c in a)d.push(`${c}=${a[c]}`);ca.strings=d}return ca.strings},Bd=[null,[],[]],Cd={c:function(a,c,d){return 0},r:(a,c,d)=>{},h:function(a,c,d){return 0},d:function(a,c,d,g){},p:a=>{},o:(a,c)=>{},q:(a,c,d)=>{},l:()=>{V("")},s:(a,c,d)=>Q.copyWithin(a,c,c+d),j:function(a,c,d){a=new Date(1E3*(c+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*c:NaN));F[d>>2]=a.getSeconds();F[d+4>>2]=a.getMinutes();
F[d+8>>2]=a.getHours();F[d+12>>2]=a.getDate();F[d+16>>2]=a.getMonth();F[d+20>>2]=a.getFullYear()-1900;F[d+24>>2]=a.getDay();c=a.getFullYear();c=(0!==c%4||0===c%100&&0!==c%400?Ad:zd)[a.getMonth()]+a.getDate()-1;F[d+28>>2]=c|0;F[d+36>>2]=-(60*a.getTimezoneOffset());var g=new Date(a.getFullYear(),0,1);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();g=g.getTimezoneOffset();a=(c!=g&&a.getTimezoneOffset()==Math.min(g,c))|0;F[d+32>>2]=a},n:(a,c,d,g)=>{var h=(new Date).getFullYear(),l=new Date(h,0,
1),n=new Date(h,6,1);h=l.getTimezoneOffset();var U=n.getTimezoneOffset();R[a>>2]=60*Math.max(h,U);F[c>>2]=Number(h!=U);a=da=>da.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];l=a(l);n=a(n);U<h?(aa(l,Q,d,17),aa(n,Q,g,17)):(aa(l,Q,g,17),aa(n,Q,d,17))},i:()=>Date.now(),m:a=>{var c=Q.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var g=c*(1+.2/d);g=Math.min(g,a+100663296);var h=Math;g=Math.max(a,g);a:{h=(h.min.call(h,2147483648,g+(65536-g%65536)%65536)-ea.buffer.byteLength+
65535)/65536;try{ea.grow(h);wa();var l=1;break a}catch(n){}l=void 0}if(l)return!0}return!1},e:(a,c)=>{var d=0;ca().forEach((g,h)=>{var l=c+d;h=R[a+4*h>>2]=l;for(l=0;l<g.length;++l)P[h++]=g.charCodeAt(l);P[h]=0;d+=g.length+1});return 0},f:(a,c)=>{var d=ca();R[a>>2]=d.length;var g=0;d.forEach(h=>g+=h.length+1);R[c>>2]=g;return 0},a:a=>52,g:(a,c,d,g)=>52,k:function(a,c,d,g,h){return 70},b:(a,c,d,g)=>{for(var h=0,l=0;l<d;l++){var n=R[c>>2],U=R[c+4>>2];c+=8;for(var da=0;da<U;da++){var ta=Q[n+da],ua=Bd[a];
0===ta||10===ta?((1===a?yd:X)(Na(ua,0)),ua.length=0):ua.push(ta)}h+=U}R[g>>2]=h;return 0}},e=function(){var a={a:Cd};Y++;na||=sd();ud(oa,na,a,function(c){e=c.instance.exports;ea=e.t;wa();Da.unshift(e.u);Y--;0==Y&&ba&&(c=ba,ba=null,c())}).catch(ma);return{}}();b._webidl_free=a=>(b._webidl_free=e.v)(a);b._webidl_malloc=a=>(b._webidl_malloc=e.w)(a);var Oa=b._emscripten_bind_PeObject_getCode_0=a=>(Oa=b._emscripten_bind_PeObject_getCode_0=e.x)(a),Pa=b._emscripten_bind_PeObject_getName_1=(a,c)=>(Pa=b._emscripten_bind_PeObject_getName_1=
e.y)(a,c),Qa=b._emscripten_bind_PeObject_getType_0=a=>(Qa=b._emscripten_bind_PeObject_getType_0=e.z)(a),Ra=b._emscripten_bind_PeCoordsys_getCode_0=a=>(Ra=b._emscripten_bind_PeCoordsys_getCode_0=e.A)(a),Sa=b._emscripten_bind_PeCoordsys_getName_1=(a,c)=>(Sa=b._emscripten_bind_PeCoordsys_getName_1=e.B)(a,c),Ta=b._emscripten_bind_PeCoordsys_getType_0=a=>(Ta=b._emscripten_bind_PeCoordsys_getType_0=e.C)(a),Ua=b._emscripten_bind_VoidPtr___destroy___0=a=>(Ua=b._emscripten_bind_VoidPtr___destroy___0=e.D)(a),
Va=b._emscripten_bind_PeDatum_getSpheroid_0=a=>(Va=b._emscripten_bind_PeDatum_getSpheroid_0=e.E)(a),Wa=b._emscripten_bind_PeDatum_getCode_0=a=>(Wa=b._emscripten_bind_PeDatum_getCode_0=e.F)(a),Xa=b._emscripten_bind_PeDatum_getName_1=(a,c)=>(Xa=b._emscripten_bind_PeDatum_getName_1=e.G)(a,c),Ya=b._emscripten_bind_PeDatum_getType_0=a=>(Ya=b._emscripten_bind_PeDatum_getType_0=e.H)(a),Za=b._emscripten_bind_PeDefs_get_PE_BUFFER_MAX_0=a=>(Za=b._emscripten_bind_PeDefs_get_PE_BUFFER_MAX_0=e.I)(a),$a=b._emscripten_bind_PeDefs_get_PE_NAME_MAX_0=
a=>($a=b._emscripten_bind_PeDefs_get_PE_NAME_MAX_0=e.J)(a),ab=b._emscripten_bind_PeDefs_get_PE_MGRS_MAX_0=a=>(ab=b._emscripten_bind_PeDefs_get_PE_MGRS_MAX_0=e.K)(a),bb=b._emscripten_bind_PeDefs_get_PE_USNG_MAX_0=a=>(bb=b._emscripten_bind_PeDefs_get_PE_USNG_MAX_0=e.L)(a),cb=b._emscripten_bind_PeDefs_get_PE_DD_MAX_0=a=>(cb=b._emscripten_bind_PeDefs_get_PE_DD_MAX_0=e.M)(a),db=b._emscripten_bind_PeDefs_get_PE_DMS_MAX_0=a=>(db=b._emscripten_bind_PeDefs_get_PE_DMS_MAX_0=e.N)(a),eb=b._emscripten_bind_PeDefs_get_PE_DDM_MAX_0=
a=>(eb=b._emscripten_bind_PeDefs_get_PE_DDM_MAX_0=e.O)(a),fb=b._emscripten_bind_PeDefs_get_PE_UTM_MAX_0=a=>(fb=b._emscripten_bind_PeDefs_get_PE_UTM_MAX_0=e.P)(a),gb=b._emscripten_bind_PeDefs_get_PE_PARM_MAX_0=a=>(gb=b._emscripten_bind_PeDefs_get_PE_PARM_MAX_0=e.Q)(a),hb=b._emscripten_bind_PeDefs_get_PE_TYPE_NONE_0=a=>(hb=b._emscripten_bind_PeDefs_get_PE_TYPE_NONE_0=e.R)(a),ib=b._emscripten_bind_PeDefs_get_PE_TYPE_GEOGCS_0=a=>(ib=b._emscripten_bind_PeDefs_get_PE_TYPE_GEOGCS_0=e.S)(a),jb=b._emscripten_bind_PeDefs_get_PE_TYPE_PROJCS_0=
a=>(jb=b._emscripten_bind_PeDefs_get_PE_TYPE_PROJCS_0=e.T)(a),kb=b._emscripten_bind_PeDefs_get_PE_TYPE_GEOGTRAN_0=a=>(kb=b._emscripten_bind_PeDefs_get_PE_TYPE_GEOGTRAN_0=e.U)(a),lb=b._emscripten_bind_PeDefs_get_PE_TYPE_COORDSYS_0=a=>(lb=b._emscripten_bind_PeDefs_get_PE_TYPE_COORDSYS_0=e.V)(a),mb=b._emscripten_bind_PeDefs_get_PE_TYPE_UNIT_0=a=>(mb=b._emscripten_bind_PeDefs_get_PE_TYPE_UNIT_0=e.W)(a),nb=b._emscripten_bind_PeDefs_get_PE_TYPE_LINUNIT_0=a=>(nb=b._emscripten_bind_PeDefs_get_PE_TYPE_LINUNIT_0=
e.X)(a),ob=b._emscripten_bind_PeDefs_get_PE_STR_OPTS_NONE_0=a=>(ob=b._emscripten_bind_PeDefs_get_PE_STR_OPTS_NONE_0=e.Y)(a),pb=b._emscripten_bind_PeDefs_get_PE_STR_AUTH_NONE_0=a=>(pb=b._emscripten_bind_PeDefs_get_PE_STR_AUTH_NONE_0=e.Z)(a),qb=b._emscripten_bind_PeDefs_get_PE_STR_AUTH_TOP_0=a=>(qb=b._emscripten_bind_PeDefs_get_PE_STR_AUTH_TOP_0=e._)(a),rb=b._emscripten_bind_PeDefs_get_PE_STR_NAME_CANON_0=a=>(rb=b._emscripten_bind_PeDefs_get_PE_STR_NAME_CANON_0=e.$)(a),sb=b._emscripten_bind_PeDefs_get_PE_STR_FMT_WKT_0=
a=>(sb=b._emscripten_bind_PeDefs_get_PE_STR_FMT_WKT_0=e.aa)(a),tb=b._emscripten_bind_PeDefs_get_PE_STR_FMT_WKT2_0=a=>(tb=b._emscripten_bind_PeDefs_get_PE_STR_FMT_WKT2_0=e.ba)(a),ub=b._emscripten_bind_PeDefs_get_PE_PARM_X0_0=a=>(ub=b._emscripten_bind_PeDefs_get_PE_PARM_X0_0=e.ca)(a),vb=b._emscripten_bind_PeDefs_get_PE_PARM_ND_0=a=>(vb=b._emscripten_bind_PeDefs_get_PE_PARM_ND_0=e.da)(a),wb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_1_TO_2_0=a=>(wb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_1_TO_2_0=
e.ea)(a),xb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_2_TO_1_0=a=>(xb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_2_TO_1_0=e.fa)(a),yb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_P_TO_G_0=a=>(yb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_P_TO_G_0=e.ga)(a),zb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_G_TO_P_0=a=>(zb=b._emscripten_bind_PeDefs_get_PE_TRANSFORM_G_TO_P_0=e.ha)(a),Ab=b._emscripten_bind_PeDefs_get_PE_HORIZON_RECT_0=a=>(Ab=b._emscripten_bind_PeDefs_get_PE_HORIZON_RECT_0=e.ia)(a),Bb=b._emscripten_bind_PeDefs_get_PE_HORIZON_POLY_0=
a=>(Bb=b._emscripten_bind_PeDefs_get_PE_HORIZON_POLY_0=e.ja)(a),Cb=b._emscripten_bind_PeDefs_get_PE_HORIZON_LINE_0=a=>(Cb=b._emscripten_bind_PeDefs_get_PE_HORIZON_LINE_0=e.ka)(a),Db=b._emscripten_bind_PeDefs_get_PE_HORIZON_DELTA_0=a=>(Db=b._emscripten_bind_PeDefs_get_PE_HORIZON_DELTA_0=e.la)(a),Eb=b._emscripten_bind_PeFactory_initialize_1=a=>(Eb=b._emscripten_bind_PeFactory_initialize_1=e.ma)(a),Fb=b._emscripten_bind_PeFactory_factoryByType_2=(a,c)=>(Fb=b._emscripten_bind_PeFactory_factoryByType_2=
e.na)(a,c),Gb=b._emscripten_bind_PeFactory_fromString_2=(a,c)=>(Gb=b._emscripten_bind_PeFactory_fromString_2=e.oa)(a,c),Hb=b._emscripten_bind_PeFactory_getCode_1=a=>(Hb=b._emscripten_bind_PeFactory_getCode_1=e.pa)(a),Fa=b._emscripten_bind_PeGCSExtent_PeGCSExtent_6=(a,c,d,g,h,l)=>(Fa=b._emscripten_bind_PeGCSExtent_PeGCSExtent_6=e.qa)(a,c,d,g,h,l),Ib=b._emscripten_bind_PeGCSExtent_getLLon_0=a=>(Ib=b._emscripten_bind_PeGCSExtent_getLLon_0=e.ra)(a),Jb=b._emscripten_bind_PeGCSExtent_getSLat_0=a=>(Jb=b._emscripten_bind_PeGCSExtent_getSLat_0=
e.sa)(a),Kb=b._emscripten_bind_PeGCSExtent_getRLon_0=a=>(Kb=b._emscripten_bind_PeGCSExtent_getRLon_0=e.ta)(a),Lb=b._emscripten_bind_PeGCSExtent_getNLat_0=a=>(Lb=b._emscripten_bind_PeGCSExtent_getNLat_0=e.ua)(a),Mb=b._emscripten_bind_PeGCSExtent___destroy___0=a=>(Mb=b._emscripten_bind_PeGCSExtent___destroy___0=e.va)(a),Nb=b._emscripten_bind_PeGeogcs_getDatum_0=a=>(Nb=b._emscripten_bind_PeGeogcs_getDatum_0=e.wa)(a),Ob=b._emscripten_bind_PeGeogcs_getPrimem_0=a=>(Ob=b._emscripten_bind_PeGeogcs_getPrimem_0=
e.xa)(a),Pb=b._emscripten_bind_PeGeogcs_getUnit_0=a=>(Pb=b._emscripten_bind_PeGeogcs_getUnit_0=e.ya)(a),Qb=b._emscripten_bind_PeGeogcs_getCode_0=a=>(Qb=b._emscripten_bind_PeGeogcs_getCode_0=e.za)(a),Rb=b._emscripten_bind_PeGeogcs_getName_1=(a,c)=>(Rb=b._emscripten_bind_PeGeogcs_getName_1=e.Aa)(a,c),Sb=b._emscripten_bind_PeGeogcs_getType_0=a=>(Sb=b._emscripten_bind_PeGeogcs_getType_0=e.Ba)(a),Tb=b._emscripten_bind_PeGeogtran_isEqual_1=(a,c)=>(Tb=b._emscripten_bind_PeGeogtran_isEqual_1=e.Ca)(a,c),Ub=
b._emscripten_bind_PeGeogtran_getGeogcs1_0=a=>(Ub=b._emscripten_bind_PeGeogtran_getGeogcs1_0=e.Da)(a),Vb=b._emscripten_bind_PeGeogtran_getGeogcs2_0=a=>(Vb=b._emscripten_bind_PeGeogtran_getGeogcs2_0=e.Ea)(a),Wb=b._emscripten_bind_PeGeogtran_getParameters_0=a=>(Wb=b._emscripten_bind_PeGeogtran_getParameters_0=e.Fa)(a),Xb=b._emscripten_bind_PeGeogtran_loadConstants_0=a=>(Xb=b._emscripten_bind_PeGeogtran_loadConstants_0=e.Ga)(a),Yb=b._emscripten_bind_PeGeogtran_getCode_0=a=>(Yb=b._emscripten_bind_PeGeogtran_getCode_0=
e.Ha)(a),Zb=b._emscripten_bind_PeGeogtran_getName_1=(a,c)=>(Zb=b._emscripten_bind_PeGeogtran_getName_1=e.Ia)(a,c),$b=b._emscripten_bind_PeGeogtran_getType_0=a=>($b=b._emscripten_bind_PeGeogtran_getType_0=e.Ja)(a),ac=b._emscripten_bind_PeGTlistExtended_getGTlist_6=(a,c,d,g,h,l)=>(ac=b._emscripten_bind_PeGTlistExtended_getGTlist_6=e.Ka)(a,c,d,g,h,l),bc=b._emscripten_bind_PeGTlistExtended_get_PE_GTLIST_OPTS_COMMON_0=a=>(bc=b._emscripten_bind_PeGTlistExtended_get_PE_GTLIST_OPTS_COMMON_0=e.La)(a),cc=b._emscripten_bind_PeGTlistExtendedEntry_getEntries_0=
a=>(cc=b._emscripten_bind_PeGTlistExtendedEntry_getEntries_0=e.Ma)(a),dc=b._emscripten_bind_PeGTlistExtendedEntry_getSteps_0=a=>(dc=b._emscripten_bind_PeGTlistExtendedEntry_getSteps_0=e.Na)(a),ec=b._emscripten_bind_PeGTlistExtendedEntry_Delete_1=a=>(ec=b._emscripten_bind_PeGTlistExtendedEntry_Delete_1=e.Oa)(a),fc=b._emscripten_bind_PeGTlistExtendedGTs_getDirection_0=a=>(fc=b._emscripten_bind_PeGTlistExtendedGTs_getDirection_0=e.Pa)(a),gc=b._emscripten_bind_PeGTlistExtendedGTs_getGeogtran_0=a=>(gc=
b._emscripten_bind_PeGTlistExtendedGTs_getGeogtran_0=e.Qa)(a),hc=b._emscripten_bind_PeHorizon_getNump_0=a=>(hc=b._emscripten_bind_PeHorizon_getNump_0=e.Ra)(a),ic=b._emscripten_bind_PeHorizon_getKind_0=a=>(ic=b._emscripten_bind_PeHorizon_getKind_0=e.Sa)(a),jc=b._emscripten_bind_PeHorizon_getInclusive_0=a=>(jc=b._emscripten_bind_PeHorizon_getInclusive_0=e.Ta)(a),kc=b._emscripten_bind_PeHorizon_getSize_0=a=>(kc=b._emscripten_bind_PeHorizon_getSize_0=e.Ua)(a),lc=b._emscripten_bind_PeHorizon_getCoord_0=
a=>(lc=b._emscripten_bind_PeHorizon_getCoord_0=e.Va)(a),Ga=b._emscripten_bind_PeInteger_PeInteger_1=a=>(Ga=b._emscripten_bind_PeInteger_PeInteger_1=e.Wa)(a),mc=b._emscripten_bind_PeInteger_get_val_0=a=>(mc=b._emscripten_bind_PeInteger_get_val_0=e.Xa)(a),nc=b._emscripten_bind_PeInteger_set_val_1=(a,c)=>(nc=b._emscripten_bind_PeInteger_set_val_1=e.Ya)(a,c),oc=b._emscripten_bind_PeInteger___destroy___0=a=>(oc=b._emscripten_bind_PeInteger___destroy___0=e.Za)(a),pc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_STYLE_NEW_0=
a=>(pc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_STYLE_NEW_0=e._a)(a),qc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_STYLE_OLD_0=a=>(qc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_STYLE_OLD_0=e.$a)(a),rc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_STYLE_AUTO_0=a=>(rc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_STYLE_AUTO_0=e.ab)(a),sc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_180_ZONE_1_PLUS_0=a=>(sc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_180_ZONE_1_PLUS_0=e.bb)(a),tc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_ADD_SPACES_0=
a=>(tc=b._emscripten_bind_PeNotationMgrs_get_PE_MGRS_ADD_SPACES_0=e.cb)(a),uc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_NONE_0=a=>(uc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_NONE_0=e.db)(a),vc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_NS_0=a=>(vc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_NS_0=e.eb)(a),wc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_NS_STRICT_0=a=>(wc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_NS_STRICT_0=e.fb)(a),xc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_ADD_SPACES_0=
a=>(xc=b._emscripten_bind_PeNotationUtm_get_PE_UTM_OPTS_ADD_SPACES_0=e.gb)(a),yc=b._emscripten_bind_PeParameter_getValue_0=a=>(yc=b._emscripten_bind_PeParameter_getValue_0=e.hb)(a),zc=b._emscripten_bind_PeParameter_getCode_0=a=>(zc=b._emscripten_bind_PeParameter_getCode_0=e.ib)(a),Ac=b._emscripten_bind_PeParameter_getName_1=(a,c)=>(Ac=b._emscripten_bind_PeParameter_getName_1=e.jb)(a,c),Bc=b._emscripten_bind_PeParameter_getType_0=a=>(Bc=b._emscripten_bind_PeParameter_getType_0=e.kb)(a),Cc=b._emscripten_bind_PePCSInfo_getCentralMeridian_0=
a=>(Cc=b._emscripten_bind_PePCSInfo_getCentralMeridian_0=e.lb)(a),Dc=b._emscripten_bind_PePCSInfo_getDomainMinx_0=a=>(Dc=b._emscripten_bind_PePCSInfo_getDomainMinx_0=e.mb)(a),Ec=b._emscripten_bind_PePCSInfo_getDomainMiny_0=a=>(Ec=b._emscripten_bind_PePCSInfo_getDomainMiny_0=e.nb)(a),Fc=b._emscripten_bind_PePCSInfo_getDomainMaxx_0=a=>(Fc=b._emscripten_bind_PePCSInfo_getDomainMaxx_0=e.ob)(a),Gc=b._emscripten_bind_PePCSInfo_getDomainMaxy_0=a=>(Gc=b._emscripten_bind_PePCSInfo_getDomainMaxy_0=e.pb)(a),
Hc=b._emscripten_bind_PePCSInfo_getNorthPoleLocation_0=a=>(Hc=b._emscripten_bind_PePCSInfo_getNorthPoleLocation_0=e.qb)(a),Ic=b._emscripten_bind_PePCSInfo_getNorthPoleGeometry_0=a=>(Ic=b._emscripten_bind_PePCSInfo_getNorthPoleGeometry_0=e.rb)(a),Jc=b._emscripten_bind_PePCSInfo_getSouthPoleLocation_0=a=>(Jc=b._emscripten_bind_PePCSInfo_getSouthPoleLocation_0=e.sb)(a),Kc=b._emscripten_bind_PePCSInfo_getSouthPoleGeometry_0=a=>(Kc=b._emscripten_bind_PePCSInfo_getSouthPoleGeometry_0=e.tb)(a),Lc=b._emscripten_bind_PePCSInfo_isDensificationNeeded_0=
a=>(Lc=b._emscripten_bind_PePCSInfo_isDensificationNeeded_0=e.ub)(a),Mc=b._emscripten_bind_PePCSInfo_isGcsHorizonMultiOverlap_0=a=>(Mc=b._emscripten_bind_PePCSInfo_isGcsHorizonMultiOverlap_0=e.vb)(a),Nc=b._emscripten_bind_PePCSInfo_isPannableRectangle_0=a=>(Nc=b._emscripten_bind_PePCSInfo_isPannableRectangle_0=e.wb)(a),Oc=b._emscripten_bind_PePCSInfo_generate_2=(a,c)=>(Oc=b._emscripten_bind_PePCSInfo_generate_2=e.xb)(a,c),Pc=b._emscripten_bind_PePCSInfo_get_PE_PCSINFO_OPTION_NONE_0=a=>(Pc=b._emscripten_bind_PePCSInfo_get_PE_PCSINFO_OPTION_NONE_0=
e.yb)(a),Qc=b._emscripten_bind_PePCSInfo_get_PE_PCSINFO_OPTION_DOMAIN_0=a=>(Qc=b._emscripten_bind_PePCSInfo_get_PE_PCSINFO_OPTION_DOMAIN_0=e.zb)(a),Rc=b._emscripten_bind_PePCSInfo_get_PE_POLE_OUTSIDE_BOUNDARY_0=a=>(Rc=b._emscripten_bind_PePCSInfo_get_PE_POLE_OUTSIDE_BOUNDARY_0=e.Ab)(a),Sc=b._emscripten_bind_PePCSInfo_get_PE_POLE_POINT_0=a=>(Sc=b._emscripten_bind_PePCSInfo_get_PE_POLE_POINT_0=e.Bb)(a),Tc=b._emscripten_bind_PePrimem_getLongitude_0=a=>(Tc=b._emscripten_bind_PePrimem_getLongitude_0=e.Cb)(a),
Uc=b._emscripten_bind_PePrimem_getCode_0=a=>(Uc=b._emscripten_bind_PePrimem_getCode_0=e.Db)(a),Vc=b._emscripten_bind_PePrimem_getName_1=(a,c)=>(Vc=b._emscripten_bind_PePrimem_getName_1=e.Eb)(a,c),Wc=b._emscripten_bind_PePrimem_getType_0=a=>(Wc=b._emscripten_bind_PePrimem_getType_0=e.Fb)(a),Xc=b._emscripten_bind_PeProjcs_getGeogcs_0=a=>(Xc=b._emscripten_bind_PeProjcs_getGeogcs_0=e.Gb)(a),Yc=b._emscripten_bind_PeProjcs_getParameters_0=a=>(Yc=b._emscripten_bind_PeProjcs_getParameters_0=e.Hb)(a),Zc=b._emscripten_bind_PeProjcs_getUnit_0=
a=>(Zc=b._emscripten_bind_PeProjcs_getUnit_0=e.Ib)(a),$c=b._emscripten_bind_PeProjcs_loadConstants_0=a=>($c=b._emscripten_bind_PeProjcs_loadConstants_0=e.Jb)(a),ad=b._emscripten_bind_PeProjcs_horizonGcsGenerate_0=a=>(ad=b._emscripten_bind_PeProjcs_horizonGcsGenerate_0=e.Kb)(a),bd=b._emscripten_bind_PeProjcs_horizonPcsGenerate_0=a=>(bd=b._emscripten_bind_PeProjcs_horizonPcsGenerate_0=e.Lb)(a),cd=b._emscripten_bind_PeProjcs_getCode_0=a=>(cd=b._emscripten_bind_PeProjcs_getCode_0=e.Mb)(a),dd=b._emscripten_bind_PeProjcs_getName_1=
(a,c)=>(dd=b._emscripten_bind_PeProjcs_getName_1=e.Nb)(a,c),ed=b._emscripten_bind_PeProjcs_getType_0=a=>(ed=b._emscripten_bind_PeProjcs_getType_0=e.Ob)(a),fd=b._emscripten_bind_PeSpheroid_getAxis_0=a=>(fd=b._emscripten_bind_PeSpheroid_getAxis_0=e.Pb)(a),gd=b._emscripten_bind_PeSpheroid_getFlattening_0=a=>(gd=b._emscripten_bind_PeSpheroid_getFlattening_0=e.Qb)(a),hd=b._emscripten_bind_PeSpheroid_getCode_0=a=>(hd=b._emscripten_bind_PeSpheroid_getCode_0=e.Rb)(a),id=b._emscripten_bind_PeSpheroid_getName_1=
(a,c)=>(id=b._emscripten_bind_PeSpheroid_getName_1=e.Sb)(a,c),jd=b._emscripten_bind_PeSpheroid_getType_0=a=>(jd=b._emscripten_bind_PeSpheroid_getType_0=e.Tb)(a),kd=b._emscripten_bind_PeUnit_getUnitFactor_0=a=>(kd=b._emscripten_bind_PeUnit_getUnitFactor_0=e.Ub)(a),ld=b._emscripten_bind_PeUnit_getCode_0=a=>(ld=b._emscripten_bind_PeUnit_getCode_0=e.Vb)(a),md=b._emscripten_bind_PeUnit_getName_1=(a,c)=>(md=b._emscripten_bind_PeUnit_getName_1=e.Wb)(a,c),nd=b._emscripten_bind_PeUnit_getType_0=a=>(nd=b._emscripten_bind_PeUnit_getType_0=
e.Xb)(a),od=b._emscripten_bind_PeVersion_version_string_0=a=>(od=b._emscripten_bind_PeVersion_version_string_0=e.Yb)(a);b._pe_getPeGTlistExtendedEntrySize=()=>(b._pe_getPeGTlistExtendedEntrySize=e.Zb)();b._pe_getPeGTlistExtendedGTsSize=()=>(b._pe_getPeGTlistExtendedGTsSize=e._b)();b._pe_getPeHorizonSize=()=>(b._pe_getPeHorizonSize=e.$b)();b._pe_geog_to_geog=(a,c,d,g,h)=>(b._pe_geog_to_geog=e.bc)(a,c,d,g,h);b._pe_geog_to_proj=(a,c,d)=>(b._pe_geog_to_proj=e.cc)(a,c,d);b._pe_geog_to_dd=(a,c,d,g,h)=>
(b._pe_geog_to_dd=e.dc)(a,c,d,g,h);b._pe_dd_to_geog=(a,c,d,g)=>(b._pe_dd_to_geog=e.ec)(a,c,d,g);b._pe_geog_to_ddm=(a,c,d,g,h)=>(b._pe_geog_to_ddm=e.fc)(a,c,d,g,h);b._pe_ddm_to_geog=(a,c,d,g)=>(b._pe_ddm_to_geog=e.gc)(a,c,d,g);b._pe_geog_to_dms=(a,c,d,g,h)=>(b._pe_geog_to_dms=e.hc)(a,c,d,g,h);b._pe_dms_to_geog=(a,c,d,g)=>(b._pe_dms_to_geog=e.ic)(a,c,d,g);b._pe_geog_to_mgrs_extended=(a,c,d,g,h,l,n)=>(b._pe_geog_to_mgrs_extended=e.jc)(a,c,d,g,h,l,n);b._pe_mgrs_to_geog_extended=(a,c,d,g,h)=>(b._pe_mgrs_to_geog_extended=
e.kc)(a,c,d,g,h);b._pe_geog_to_usng=(a,c,d,g,h,l,n)=>(b._pe_geog_to_usng=e.lc)(a,c,d,g,h,l,n);b._pe_usng_to_geog=(a,c,d,g)=>(b._pe_usng_to_geog=e.mc)(a,c,d,g);b._pe_geog_to_utm=(a,c,d,g,h)=>(b._pe_geog_to_utm=e.nc)(a,c,d,g,h);b._pe_utm_to_geog=(a,c,d,g,h)=>(b._pe_utm_to_geog=e.oc)(a,c,d,g,h);b._pe_object_to_string_ext=(a,c,d)=>(b._pe_object_to_string_ext=e.pc)(a,c,d);b._pe_proj_to_geog_center=(a,c,d,g)=>(b._pe_proj_to_geog_center=e.qc)(a,c,d,g);b.getValue=function(a,c="i8"){c.endsWith("*")&&(c="*");
switch(c){case "i1":return P[a];case "i8":return P[a];case "i16":return fa[a>>1];case "i32":return F[a>>2];case "i64":V("to do getValue(i64) use WASM_BIGINT");case "float":return ha[a>>2];case "double":return ia[a>>3];case "*":return R[a>>2];default:V(`invalid type for getValue: ${c}`)}};b.UTF8ToString=M;var ka;ba=function c(){ka||Ca();ka||(ba=c)};Ca();r.prototype=Object.create(r.prototype);r.prototype.constructor=r;r.prototype.__class__=r;r.__cache__={};b.WrapperObject=r;b.getCache=Z;b.wrapPointer=
x;b.castObject=function(c,d){return x(c.ptr,d)};b.NULL=x(0);b.destroy=function(c){if(!c.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";c.__destroy__();delete Z(c.__class__)[c.ptr]};b.compare=function(c,d){return c.ptr===d.ptr};b.getPointer=function(c){return c.ptr};b.getClass=function(c){return c.__class__};var k={buffer:0,size:0,pos:0,temps:[],needed:0,prepare(){if(k.needed){for(var c=0;c<k.temps.length;c++)b._webidl_free(k.temps[c]);k.temps.length=0;b._webidl_free(k.buffer);
k.buffer=0;k.size+=k.needed;k.needed=0}k.buffer||(k.size+=128,k.buffer=b._webidl_malloc(k.size),k.buffer||V(void 0));k.pos=0},alloc(c,d){k.buffer||V(void 0);c=c.length*d.BYTES_PER_ELEMENT;c=8*Math.ceil(c/8);k.pos+c>=k.size?(0<c||V(void 0),k.needed+=c,d=b._webidl_malloc(c),k.temps.push(d)):(d=k.buffer+k.pos,k.pos+=c);return d},copy(c,d,g){g/=d.BYTES_PER_ELEMENT;for(var h=0;h<c.length;h++)d[g+h]=c[h]}};v.prototype=Object.create(r.prototype);v.prototype.constructor=v;v.prototype.__class__=v;v.__cache__=
{};b.PeObject=v;v.prototype.getCode=v.prototype.getCode=function(){return Oa(this.ptr)};v.prototype.getName=v.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(Pa(d,c))};v.prototype.getType=v.prototype.getType=function(){return Qa(this.ptr)};G.prototype=Object.create(v.prototype);G.prototype.constructor=G;G.prototype.__class__=G;G.__cache__={};b.PeCoordsys=G;G.prototype.getCode=G.prototype.getCode=function(){return Ra(this.ptr)};G.prototype.getName=G.prototype.getName=
function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(Sa(d,c))};G.prototype.getType=G.prototype.getType=function(){return Ta(this.ptr)};S.prototype=Object.create(r.prototype);S.prototype.constructor=S;S.prototype.__class__=S;S.__cache__={};b.VoidPtr=S;S.prototype.__destroy__=S.prototype.__destroy__=function(){Ua(this.ptr)};D.prototype=Object.create(v.prototype);D.prototype.constructor=D;D.prototype.__class__=D;D.__cache__={};b.PeDatum=D;D.prototype.getSpheroid=D.prototype.getSpheroid=
function(){return x(Va(this.ptr),A)};D.prototype.getCode=D.prototype.getCode=function(){return Wa(this.ptr)};D.prototype.getName=D.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(Xa(d,c))};D.prototype.getType=D.prototype.getType=function(){return Ya(this.ptr)};f.prototype=Object.create(r.prototype);f.prototype.constructor=f;f.prototype.__class__=f;f.__cache__={};b.PeDefs=f;f.prototype.get_PE_BUFFER_MAX=f.prototype.get_PE_BUFFER_MAX=function(){return Za(this.ptr)};
Object.defineProperty(f.prototype,"PE_BUFFER_MAX",{get:f.prototype.get_PE_BUFFER_MAX});f.prototype.get_PE_NAME_MAX=f.prototype.get_PE_NAME_MAX=function(){return $a(this.ptr)};Object.defineProperty(f.prototype,"PE_NAME_MAX",{get:f.prototype.get_PE_NAME_MAX});f.prototype.get_PE_MGRS_MAX=f.prototype.get_PE_MGRS_MAX=function(){return ab(this.ptr)};Object.defineProperty(f.prototype,"PE_MGRS_MAX",{get:f.prototype.get_PE_MGRS_MAX});f.prototype.get_PE_USNG_MAX=f.prototype.get_PE_USNG_MAX=function(){return bb(this.ptr)};
Object.defineProperty(f.prototype,"PE_USNG_MAX",{get:f.prototype.get_PE_USNG_MAX});f.prototype.get_PE_DD_MAX=f.prototype.get_PE_DD_MAX=function(){return cb(this.ptr)};Object.defineProperty(f.prototype,"PE_DD_MAX",{get:f.prototype.get_PE_DD_MAX});f.prototype.get_PE_DMS_MAX=f.prototype.get_PE_DMS_MAX=function(){return db(this.ptr)};Object.defineProperty(f.prototype,"PE_DMS_MAX",{get:f.prototype.get_PE_DMS_MAX});f.prototype.get_PE_DDM_MAX=f.prototype.get_PE_DDM_MAX=function(){return eb(this.ptr)};Object.defineProperty(f.prototype,
"PE_DDM_MAX",{get:f.prototype.get_PE_DDM_MAX});f.prototype.get_PE_UTM_MAX=f.prototype.get_PE_UTM_MAX=function(){return fb(this.ptr)};Object.defineProperty(f.prototype,"PE_UTM_MAX",{get:f.prototype.get_PE_UTM_MAX});f.prototype.get_PE_PARM_MAX=f.prototype.get_PE_PARM_MAX=function(){return gb(this.ptr)};Object.defineProperty(f.prototype,"PE_PARM_MAX",{get:f.prototype.get_PE_PARM_MAX});f.prototype.get_PE_TYPE_NONE=f.prototype.get_PE_TYPE_NONE=function(){return hb(this.ptr)};Object.defineProperty(f.prototype,
"PE_TYPE_NONE",{get:f.prototype.get_PE_TYPE_NONE});f.prototype.get_PE_TYPE_GEOGCS=f.prototype.get_PE_TYPE_GEOGCS=function(){return ib(this.ptr)};Object.defineProperty(f.prototype,"PE_TYPE_GEOGCS",{get:f.prototype.get_PE_TYPE_GEOGCS});f.prototype.get_PE_TYPE_PROJCS=f.prototype.get_PE_TYPE_PROJCS=function(){return jb(this.ptr)};Object.defineProperty(f.prototype,"PE_TYPE_PROJCS",{get:f.prototype.get_PE_TYPE_PROJCS});f.prototype.get_PE_TYPE_GEOGTRAN=f.prototype.get_PE_TYPE_GEOGTRAN=function(){return kb(this.ptr)};
Object.defineProperty(f.prototype,"PE_TYPE_GEOGTRAN",{get:f.prototype.get_PE_TYPE_GEOGTRAN});f.prototype.get_PE_TYPE_COORDSYS=f.prototype.get_PE_TYPE_COORDSYS=function(){return lb(this.ptr)};Object.defineProperty(f.prototype,"PE_TYPE_COORDSYS",{get:f.prototype.get_PE_TYPE_COORDSYS});f.prototype.get_PE_TYPE_UNIT=f.prototype.get_PE_TYPE_UNIT=function(){return mb(this.ptr)};Object.defineProperty(f.prototype,"PE_TYPE_UNIT",{get:f.prototype.get_PE_TYPE_UNIT});f.prototype.get_PE_TYPE_LINUNIT=f.prototype.get_PE_TYPE_LINUNIT=
function(){return nb(this.ptr)};Object.defineProperty(f.prototype,"PE_TYPE_LINUNIT",{get:f.prototype.get_PE_TYPE_LINUNIT});f.prototype.get_PE_STR_OPTS_NONE=f.prototype.get_PE_STR_OPTS_NONE=function(){return ob(this.ptr)};Object.defineProperty(f.prototype,"PE_STR_OPTS_NONE",{get:f.prototype.get_PE_STR_OPTS_NONE});f.prototype.get_PE_STR_AUTH_NONE=f.prototype.get_PE_STR_AUTH_NONE=function(){return pb(this.ptr)};Object.defineProperty(f.prototype,"PE_STR_AUTH_NONE",{get:f.prototype.get_PE_STR_AUTH_NONE});
f.prototype.get_PE_STR_AUTH_TOP=f.prototype.get_PE_STR_AUTH_TOP=function(){return qb(this.ptr)};Object.defineProperty(f.prototype,"PE_STR_AUTH_TOP",{get:f.prototype.get_PE_STR_AUTH_TOP});f.prototype.get_PE_STR_NAME_CANON=f.prototype.get_PE_STR_NAME_CANON=function(){return rb(this.ptr)};Object.defineProperty(f.prototype,"PE_STR_NAME_CANON",{get:f.prototype.get_PE_STR_NAME_CANON});f.prototype.get_PE_STR_FMT_WKT=f.prototype.get_PE_STR_FMT_WKT=function(){return sb(this.ptr)};Object.defineProperty(f.prototype,
"PE_STR_FMT_WKT",{get:f.prototype.get_PE_STR_FMT_WKT});f.prototype.get_PE_STR_FMT_WKT2=f.prototype.get_PE_STR_FMT_WKT2=function(){return tb(this.ptr)};Object.defineProperty(f.prototype,"PE_STR_FMT_WKT2",{get:f.prototype.get_PE_STR_FMT_WKT2});f.prototype.get_PE_PARM_X0=f.prototype.get_PE_PARM_X0=function(){return ub(this.ptr)};Object.defineProperty(f.prototype,"PE_PARM_X0",{get:f.prototype.get_PE_PARM_X0});f.prototype.get_PE_PARM_ND=f.prototype.get_PE_PARM_ND=function(){return vb(this.ptr)};Object.defineProperty(f.prototype,
"PE_PARM_ND",{get:f.prototype.get_PE_PARM_ND});f.prototype.get_PE_TRANSFORM_1_TO_2=f.prototype.get_PE_TRANSFORM_1_TO_2=function(){return wb(this.ptr)};Object.defineProperty(f.prototype,"PE_TRANSFORM_1_TO_2",{get:f.prototype.get_PE_TRANSFORM_1_TO_2});f.prototype.get_PE_TRANSFORM_2_TO_1=f.prototype.get_PE_TRANSFORM_2_TO_1=function(){return xb(this.ptr)};Object.defineProperty(f.prototype,"PE_TRANSFORM_2_TO_1",{get:f.prototype.get_PE_TRANSFORM_2_TO_1});f.prototype.get_PE_TRANSFORM_P_TO_G=f.prototype.get_PE_TRANSFORM_P_TO_G=
function(){return yb(this.ptr)};Object.defineProperty(f.prototype,"PE_TRANSFORM_P_TO_G",{get:f.prototype.get_PE_TRANSFORM_P_TO_G});f.prototype.get_PE_TRANSFORM_G_TO_P=f.prototype.get_PE_TRANSFORM_G_TO_P=function(){return zb(this.ptr)};Object.defineProperty(f.prototype,"PE_TRANSFORM_G_TO_P",{get:f.prototype.get_PE_TRANSFORM_G_TO_P});f.prototype.get_PE_HORIZON_RECT=f.prototype.get_PE_HORIZON_RECT=function(){return Ab(this.ptr)};Object.defineProperty(f.prototype,"PE_HORIZON_RECT",{get:f.prototype.get_PE_HORIZON_RECT});
f.prototype.get_PE_HORIZON_POLY=f.prototype.get_PE_HORIZON_POLY=function(){return Bb(this.ptr)};Object.defineProperty(f.prototype,"PE_HORIZON_POLY",{get:f.prototype.get_PE_HORIZON_POLY});f.prototype.get_PE_HORIZON_LINE=f.prototype.get_PE_HORIZON_LINE=function(){return Cb(this.ptr)};Object.defineProperty(f.prototype,"PE_HORIZON_LINE",{get:f.prototype.get_PE_HORIZON_LINE});f.prototype.get_PE_HORIZON_DELTA=f.prototype.get_PE_HORIZON_DELTA=function(){return Db(this.ptr)};Object.defineProperty(f.prototype,
"PE_HORIZON_DELTA",{get:f.prototype.get_PE_HORIZON_DELTA});H.prototype=Object.create(r.prototype);H.prototype.constructor=H;H.prototype.__class__=H;H.__cache__={};b.PeFactory=H;H.prototype.initialize=H.prototype.initialize=function(c){k.prepare();c=c&&"object"===typeof c?c.ptr:ra(c);Eb(c)};H.prototype.factoryByType=H.prototype.factoryByType=function(c,d){c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return x(Fb(c,d),v)};H.prototype.fromString=H.prototype.fromString=function(c,
d){k.prepare();c&&"object"===typeof c&&(c=c.ptr);d=d&&"object"===typeof d?d.ptr:ra(d);return x(Gb(c,d),v)};H.prototype.getCode=H.prototype.getCode=function(c){c&&"object"===typeof c&&(c=c.ptr);return Hb(c)};z.prototype=Object.create(r.prototype);z.prototype.constructor=z;z.prototype.__class__=z;z.__cache__={};b.PeGCSExtent=z;z.prototype.getLLon=z.prototype.getLLon=function(){return Ib(this.ptr)};z.prototype.getSLat=z.prototype.getSLat=function(){return Jb(this.ptr)};z.prototype.getRLon=z.prototype.getRLon=
function(){return Kb(this.ptr)};z.prototype.getNLat=z.prototype.getNLat=function(){return Lb(this.ptr)};z.prototype.__destroy__=z.prototype.__destroy__=function(){Mb(this.ptr)};w.prototype=Object.create(G.prototype);w.prototype.constructor=w;w.prototype.__class__=w;w.__cache__={};b.PeGeogcs=w;w.prototype.getDatum=w.prototype.getDatum=function(){return x(Nb(this.ptr),D)};w.prototype.getPrimem=w.prototype.getPrimem=function(){return x(Ob(this.ptr),E)};w.prototype.getUnit=w.prototype.getUnit=function(){return x(Pb(this.ptr),
C)};w.prototype.getCode=w.prototype.getCode=function(){return Qb(this.ptr)};w.prototype.getName=w.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(Rb(d,c))};w.prototype.getType=w.prototype.getType=function(){return Sb(this.ptr)};t.prototype=Object.create(v.prototype);t.prototype.constructor=t;t.prototype.__class__=t;t.__cache__={};b.PeGeogtran=t;t.prototype.isEqual=t.prototype.isEqual=function(c){var d=this.ptr;c&&"object"===typeof c&&(c=c.ptr);return!!Tb(d,
c)};t.prototype.getGeogcs1=t.prototype.getGeogcs1=function(){return x(Ub(this.ptr),w)};t.prototype.getGeogcs2=t.prototype.getGeogcs2=function(){return x(Vb(this.ptr),w)};t.prototype.getParameters=t.prototype.getParameters=function(){return Wb(this.ptr)};t.prototype.loadConstants=t.prototype.loadConstants=function(){return!!Xb(this.ptr)};t.prototype.getCode=t.prototype.getCode=function(){return Yb(this.ptr)};t.prototype.getName=t.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&
(c=N(c));return M(Zb(d,c))};t.prototype.getType=t.prototype.getType=function(){return $b(this.ptr)};K.prototype=Object.create(r.prototype);K.prototype.constructor=K;K.prototype.__class__=K;K.__cache__={};b.PeGTlistExtended=K;K.prototype.getGTlist=K.prototype.getGTlist=function(c,d,g,h,l,n){c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);g&&"object"===typeof g&&(g=g.ptr);h&&"object"===typeof h&&(h=h.ptr);l&&"object"===typeof l&&(l=l.ptr);n&&"object"===typeof n&&(n=n.ptr);return x(ac(c,
d,g,h,l,n),J)};K.prototype.get_PE_GTLIST_OPTS_COMMON=K.prototype.get_PE_GTLIST_OPTS_COMMON=function(){return bc(this.ptr)};Object.defineProperty(K.prototype,"PE_GTLIST_OPTS_COMMON",{get:K.prototype.get_PE_GTLIST_OPTS_COMMON});J.prototype=Object.create(r.prototype);J.prototype.constructor=J;J.prototype.__class__=J;J.__cache__={};b.PeGTlistExtendedEntry=J;J.prototype.getEntries=J.prototype.getEntries=function(){return x(cc(this.ptr),L)};J.prototype.getSteps=J.prototype.getSteps=function(){return dc(this.ptr)};
J.prototype.Delete=J.prototype.Delete=function(c){c&&"object"===typeof c&&(c=c.ptr);ec(c)};L.prototype=Object.create(r.prototype);L.prototype.constructor=L;L.prototype.__class__=L;L.__cache__={};b.PeGTlistExtendedGTs=L;L.prototype.getDirection=L.prototype.getDirection=function(){return fc(this.ptr)};L.prototype.getGeogtran=L.prototype.getGeogtran=function(){return x(gc(this.ptr),t)};y.prototype=Object.create(r.prototype);y.prototype.constructor=y;y.prototype.__class__=y;y.__cache__={};b.PeHorizon=
y;y.prototype.getNump=y.prototype.getNump=function(){return hc(this.ptr)};y.prototype.getKind=y.prototype.getKind=function(){return ic(this.ptr)};y.prototype.getInclusive=y.prototype.getInclusive=function(){return jc(this.ptr)};y.prototype.getSize=y.prototype.getSize=function(){return kc(this.ptr)};y.prototype.getCoord=y.prototype.getCoord=function(){return lc(this.ptr)};B.prototype=Object.create(r.prototype);B.prototype.constructor=B;B.prototype.__class__=B;B.__cache__={};b.PeInteger=B;B.prototype.get_val=
B.prototype.get_val=function(){return mc(this.ptr)};B.prototype.set_val=B.prototype.set_val=function(c){var d=this.ptr;c&&"object"===typeof c&&(c=c.ptr);nc(d,c)};Object.defineProperty(B.prototype,"val",{get:B.prototype.get_val,set:B.prototype.set_val});B.prototype.__destroy__=B.prototype.__destroy__=function(){oc(this.ptr)};p.prototype=Object.create(r.prototype);p.prototype.constructor=p;p.prototype.__class__=p;p.__cache__={};b.PeNotationMgrs=p;p.prototype.get_PE_MGRS_STYLE_NEW=p.prototype.get_PE_MGRS_STYLE_NEW=
function(){return pc(this.ptr)};Object.defineProperty(p.prototype,"PE_MGRS_STYLE_NEW",{get:p.prototype.get_PE_MGRS_STYLE_NEW});p.prototype.get_PE_MGRS_STYLE_OLD=p.prototype.get_PE_MGRS_STYLE_OLD=function(){return qc(this.ptr)};Object.defineProperty(p.prototype,"PE_MGRS_STYLE_OLD",{get:p.prototype.get_PE_MGRS_STYLE_OLD});p.prototype.get_PE_MGRS_STYLE_AUTO=p.prototype.get_PE_MGRS_STYLE_AUTO=function(){return rc(this.ptr)};Object.defineProperty(p.prototype,"PE_MGRS_STYLE_AUTO",{get:p.prototype.get_PE_MGRS_STYLE_AUTO});
p.prototype.get_PE_MGRS_180_ZONE_1_PLUS=p.prototype.get_PE_MGRS_180_ZONE_1_PLUS=function(){return sc(this.ptr)};Object.defineProperty(p.prototype,"PE_MGRS_180_ZONE_1_PLUS",{get:p.prototype.get_PE_MGRS_180_ZONE_1_PLUS});p.prototype.get_PE_MGRS_ADD_SPACES=p.prototype.get_PE_MGRS_ADD_SPACES=function(){return tc(this.ptr)};Object.defineProperty(p.prototype,"PE_MGRS_ADD_SPACES",{get:p.prototype.get_PE_MGRS_ADD_SPACES});u.prototype=Object.create(r.prototype);u.prototype.constructor=u;u.prototype.__class__=
u;u.__cache__={};b.PeNotationUtm=u;u.prototype.get_PE_UTM_OPTS_NONE=u.prototype.get_PE_UTM_OPTS_NONE=function(){return uc(this.ptr)};Object.defineProperty(u.prototype,"PE_UTM_OPTS_NONE",{get:u.prototype.get_PE_UTM_OPTS_NONE});u.prototype.get_PE_UTM_OPTS_NS=u.prototype.get_PE_UTM_OPTS_NS=function(){return vc(this.ptr)};Object.defineProperty(u.prototype,"PE_UTM_OPTS_NS",{get:u.prototype.get_PE_UTM_OPTS_NS});u.prototype.get_PE_UTM_OPTS_NS_STRICT=u.prototype.get_PE_UTM_OPTS_NS_STRICT=function(){return wc(this.ptr)};
Object.defineProperty(u.prototype,"PE_UTM_OPTS_NS_STRICT",{get:u.prototype.get_PE_UTM_OPTS_NS_STRICT});u.prototype.get_PE_UTM_OPTS_ADD_SPACES=u.prototype.get_PE_UTM_OPTS_ADD_SPACES=function(){return xc(this.ptr)};Object.defineProperty(u.prototype,"PE_UTM_OPTS_ADD_SPACES",{get:u.prototype.get_PE_UTM_OPTS_ADD_SPACES});I.prototype=Object.create(v.prototype);I.prototype.constructor=I;I.prototype.__class__=I;I.__cache__={};b.PeParameter=I;I.prototype.getValue=I.prototype.getValue=function(){return yc(this.ptr)};
I.prototype.getCode=I.prototype.getCode=function(){return zc(this.ptr)};I.prototype.getName=I.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(Ac(d,c))};I.prototype.getType=I.prototype.getType=function(){return Bc(this.ptr)};m.prototype=Object.create(r.prototype);m.prototype.constructor=m;m.prototype.__class__=m;m.__cache__={};b.PePCSInfo=m;m.prototype.getCentralMeridian=m.prototype.getCentralMeridian=function(){return Cc(this.ptr)};m.prototype.getDomainMinx=
m.prototype.getDomainMinx=function(){return Dc(this.ptr)};m.prototype.getDomainMiny=m.prototype.getDomainMiny=function(){return Ec(this.ptr)};m.prototype.getDomainMaxx=m.prototype.getDomainMaxx=function(){return Fc(this.ptr)};m.prototype.getDomainMaxy=m.prototype.getDomainMaxy=function(){return Gc(this.ptr)};m.prototype.getNorthPoleLocation=m.prototype.getNorthPoleLocation=function(){return Hc(this.ptr)};m.prototype.getNorthPoleGeometry=m.prototype.getNorthPoleGeometry=function(){return Ic(this.ptr)};
m.prototype.getSouthPoleLocation=m.prototype.getSouthPoleLocation=function(){return Jc(this.ptr)};m.prototype.getSouthPoleGeometry=m.prototype.getSouthPoleGeometry=function(){return Kc(this.ptr)};m.prototype.isDensificationNeeded=m.prototype.isDensificationNeeded=function(){return!!Lc(this.ptr)};m.prototype.isGcsHorizonMultiOverlap=m.prototype.isGcsHorizonMultiOverlap=function(){return!!Mc(this.ptr)};m.prototype.isPannableRectangle=m.prototype.isPannableRectangle=function(){return!!Nc(this.ptr)};
m.prototype.generate=m.prototype.generate=function(c,d){c&&"object"===typeof c&&(c=c.ptr);d&&"object"===typeof d&&(d=d.ptr);return x(Oc(c,d),m)};m.prototype.get_PE_PCSINFO_OPTION_NONE=m.prototype.get_PE_PCSINFO_OPTION_NONE=function(){return Pc(this.ptr)};Object.defineProperty(m.prototype,"PE_PCSINFO_OPTION_NONE",{get:m.prototype.get_PE_PCSINFO_OPTION_NONE});m.prototype.get_PE_PCSINFO_OPTION_DOMAIN=m.prototype.get_PE_PCSINFO_OPTION_DOMAIN=function(){return Qc(this.ptr)};Object.defineProperty(m.prototype,
"PE_PCSINFO_OPTION_DOMAIN",{get:m.prototype.get_PE_PCSINFO_OPTION_DOMAIN});m.prototype.get_PE_POLE_OUTSIDE_BOUNDARY=m.prototype.get_PE_POLE_OUTSIDE_BOUNDARY=function(){return Rc(this.ptr)};Object.defineProperty(m.prototype,"PE_POLE_OUTSIDE_BOUNDARY",{get:m.prototype.get_PE_POLE_OUTSIDE_BOUNDARY});m.prototype.get_PE_POLE_POINT=m.prototype.get_PE_POLE_POINT=function(){return Sc(this.ptr)};Object.defineProperty(m.prototype,"PE_POLE_POINT",{get:m.prototype.get_PE_POLE_POINT});E.prototype=Object.create(v.prototype);
E.prototype.constructor=E;E.prototype.__class__=E;E.__cache__={};b.PePrimem=E;E.prototype.getLongitude=E.prototype.getLongitude=function(){return Tc(this.ptr)};E.prototype.getCode=E.prototype.getCode=function(){return Uc(this.ptr)};E.prototype.getName=E.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(Vc(d,c))};E.prototype.getType=E.prototype.getType=function(){return Wc(this.ptr)};q.prototype=Object.create(G.prototype);q.prototype.constructor=q;q.prototype.__class__=
q;q.__cache__={};b.PeProjcs=q;q.prototype.getGeogcs=q.prototype.getGeogcs=function(){return x(Xc(this.ptr),w)};q.prototype.getParameters=q.prototype.getParameters=function(){return Yc(this.ptr)};q.prototype.getUnit=q.prototype.getUnit=function(){return x(Zc(this.ptr),C)};q.prototype.loadConstants=q.prototype.loadConstants=function(){return!!$c(this.ptr)};q.prototype.horizonGcsGenerate=q.prototype.horizonGcsGenerate=function(){return x(ad(this.ptr),y)};q.prototype.horizonPcsGenerate=q.prototype.horizonPcsGenerate=
function(){return x(bd(this.ptr),y)};q.prototype.getCode=q.prototype.getCode=function(){return cd(this.ptr)};q.prototype.getName=q.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(dd(d,c))};q.prototype.getType=q.prototype.getType=function(){return ed(this.ptr)};A.prototype=Object.create(v.prototype);A.prototype.constructor=A;A.prototype.__class__=A;A.__cache__={};b.PeSpheroid=A;A.prototype.getAxis=A.prototype.getAxis=function(){return fd(this.ptr)};A.prototype.getFlattening=
A.prototype.getFlattening=function(){return gd(this.ptr)};A.prototype.getCode=A.prototype.getCode=function(){return hd(this.ptr)};A.prototype.getName=A.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(id(d,c))};A.prototype.getType=A.prototype.getType=function(){return jd(this.ptr)};C.prototype=Object.create(v.prototype);C.prototype.constructor=C;C.prototype.__class__=C;C.__cache__={};b.PeUnit=C;C.prototype.getUnitFactor=C.prototype.getUnitFactor=function(){return kd(this.ptr)};
C.prototype.getCode=C.prototype.getCode=function(){return ld(this.ptr)};C.prototype.getName=C.prototype.getName=function(c){var d=this.ptr;k.prepare();"object"==typeof c&&(c=N(c));return M(md(d,c))};C.prototype.getType=C.prototype.getType=function(){return nd(this.ptr)};T.prototype=Object.create(r.prototype);T.prototype.constructor=T;T.prototype.__class__=T;T.__cache__={};b.PeVersion=T;T.prototype.version_string=T.prototype.version_string=function(){return M(od(this.ptr))};b.ensureCache=k;b.ensureString=
ra;b.ensureInt8=N;b.ensureInt16=function(c){if("object"===typeof c){var d=k.alloc(c,fa);k.copy(c,fa,d);return d}return c};b.ensureInt32=function(c){if("object"===typeof c){var d=k.alloc(c,F);k.copy(c,F,d);return d}return c};b.ensureFloat32=function(c){if("object"===typeof c){var d=k.alloc(c,ha);k.copy(c,ha,d);return d}return c};b.ensureFloat64=function(c){if("object"===typeof c){var d=k.alloc(c,ia);k.copy(c,ia,d);return d}return c};return xd}})();qd.exports=Dd})()})(va);W=W.getDefaultExportFromCjs(va.exports);
W=Object.freeze(Object.defineProperty({__proto__:null,default:W},Symbol.toStringTag,{value:"Module"}));pd.peWasm=W});