// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("../../chunks/tslib.es6 ../../Graphic ../../intl ../../core/Accessor ../../core/Collection ../../core/Error ../../core/Logger ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/RandomLCG ../../core/accessorSupport/decorators/subclass ../../core/support/UpdatingHandles ../../layers/GraphicsLayer ../../symbols/LineSymbolMarker ../../symbols/SimpleLineSymbol ../../views/draw/support/layerUtils ../../intl/locale ../../intl/messages".split(" "),function(d,
q,c,v,w,r,t,m,e,C,D,x,y,z,n,p,u,A,B){c=class extends v{constructor(b){super(b);this._internalGraphicsLayerConnectivity=this._createInternalGraphicsLayer("Connectivity Associations (Internal)");this._internalGraphicsLayerStructuralAttachment=this._createInternalGraphicsLayer("Structural Attachment Associations (Internal)");this._initialValidationsFinished=!1;this._updatingHandles=new y.UpdatingHandles;this.autoRefreshAssociations=!1;this.connectivityAssociationsLineSymbol=new p({style:"short-dash",
width:2,color:[190,159,159,1]});this.executionError="";this.loadErrors=new w;this.maxAllowableAssociations=250;this.showArrowsStructuralAttachment=this.showArrowsConnectivity=this.showAssociationsEnabled=!1;this.structuralAttachmentAssociationsLineSymbol=new p({style:"short-dash",width:2,color:[159,190,159,1]})}initialize(){const b=async()=>{this.messages||(this.messages=await B.fetchMessageBundle("esri/widgets/UtilityNetworkAssociations/t9n/UtilityNetworkAssociations"))};b().then(()=>{this.view||
(this.view=null);this.utilityNetwork||(this.utilityNetwork=null);this.addHandles([m.watch(()=>[this.view,this.utilityNetwork],async()=>{const {loadErrors:a,messages:{info:{noUtilityNetwork:f,noView:g}}}=this;this._initialValidationsFinished=!1;a.removeAll();let h=!1,k=!1;this.removeAssociations();"utility"!==this.utilityNetwork?.type?(this.loadErrors.push(f),t.getLogger(this).error(new r("utilityNetworkAssociations:missing-property",f))):(this.utilityNetwork.loaded||await this.utilityNetwork.load(),
h=!0);"2d"!==this.view?.type?(this.loadErrors.push(g),t.getLogger(this).error(new r("utilityNetworkAssociations:missing-property",g))):(u.addUniqueLayer(this.view,this._internalGraphicsLayerConnectivity),u.addUniqueLayer(this.view,this._internalGraphicsLayerStructuralAttachment),k=!0);h&&k&&this.showAssociationsEnabled&&await this.showAssociations();this._internalGraphicsLayerConnectivity.visible=this.includeConnectivityAssociations;this._internalGraphicsLayerStructuralAttachment.visible=this.includeStructuralAttachmentAssociations;
this._initialValidationsFinished=!0},{initial:!0}),m.watch(()=>[this.view?.stationary,this.showAssociationsEnabled,this.maxAllowableAssociations],async()=>{this.view?.stationary&&this.showAssociationsEnabled&&(this.includeConnectivityAssociations||this.includeStructuralAttachmentAssociations)&&await this.showAssociations()}),m.watch(()=>[this.showArrowsConnectivity],()=>{const a=this.connectivityAssociationsLineSymbol.clone();a.marker=null;this.showArrowsConnectivity&&(a.marker=new n({color:this.connectivityAssociationsLineSymbol.color,
placement:"end",style:"arrow"}));for(const f of this._internalGraphicsLayerConnectivity.graphics)f.symbol=a}),m.watch(()=>[this.showArrowsStructuralAttachment],()=>{const a=this.structuralAttachmentAssociationsLineSymbol.clone();a.marker=null;this.showArrowsStructuralAttachment&&(a.marker=new n({color:this.structuralAttachmentAssociationsLineSymbol.color,placement:"end",style:"arrow"}));for(const f of this._internalGraphicsLayerStructuralAttachment.graphics)f.symbol=a}),m.watch(()=>{const {cap:a,
color:f,style:g,width:h,marker:k}=this.connectivityAssociationsLineSymbol;return[a,f,g,h,k]},()=>{const a=this.connectivityAssociationsLineSymbol.clone();for(const f of this._internalGraphicsLayerConnectivity.graphics)f.symbol=a;this.showArrowsConnectivity=!1;a.marker=null;this.connectivityAssociationsLineSymbol.marker&&(this.showArrowsConnectivity=!0,a.marker=new n({color:this.connectivityAssociationsLineSymbol.color,placement:"end",style:"arrow"}))}),m.watch(()=>{const {cap:a,color:f,style:g,width:h,
marker:k}=this.structuralAttachmentAssociationsLineSymbol;return[a,f,g,h,k]},()=>{const a=this.structuralAttachmentAssociationsLineSymbol.clone();for(const f of this._internalGraphicsLayerStructuralAttachment.graphics)f.symbol=a;this.showArrowsStructuralAttachment=!1;a.marker=null;this.structuralAttachmentAssociationsLineSymbol.marker&&(this.showArrowsStructuralAttachment=!0,a.marker=new n({color:this.structuralAttachmentAssociationsLineSymbol.color,placement:"end",style:"arrow"}))}),A.onLocaleChange(b)])})}destroy(){this._updatingHandles.destroy();
this.view=null;this._removeInternalGraphicsLayers()}set includeConnectivityAssociations(b){this._set("includeConnectivityAssociations",b);this._internalGraphicsLayerConnectivity.visible=b}set includeStructuralAttachmentAssociations(b){this._set("includeStructuralAttachmentAssociations",b);this._internalGraphicsLayerStructuralAttachment.visible=b}get state(){return this.loadErrors.length?"disabled":this._updatingHandles.updating?"executing":""!==this.executionError?"warning":this._initialValidationsFinished?
"ready":"loading"}set utilityNetwork(b){this._get("utilityNetwork")!==b&&this._set("utilityNetwork",b)}set view(b){this._get("view")!==b&&this._set("view",b)}removeAssociations(){this._internalGraphicsLayerConnectivity.removeAll();this._internalGraphicsLayerStructuralAttachment.removeAll()}async showAssociations(){const {messages:{info:{maxAllowableAssociationsExceeded:b,noAssociationsFound:a}},utilityNetwork:f}=this;this._set("executionError","");this._updatingHandles.addPromise(f?.synthesizeAssociationGeometries({returnConnectivityAssociations:this.includeConnectivityAssociations,
returnAttachmentAssociations:this.includeStructuralAttachmentAssociations,extent:this.view?.extent,outSpatialReference:this.utilityNetwork?.spatialReference.clone(),maxGeometryCount:this.maxAllowableAssociations}).then(g=>{let h=[],k=[];g?.maxGeometryCountExceeded?(this.removeAssociations(),this._set("executionError",b)):0===g?.associations.length?(this.removeAssociations(),this._set("executionError",a)):g&&(h=g?.associations.filter(({associationType:l})=>"connectivity"===l).map(l=>{this.connectivityAssociationsLineSymbol.marker=
null;this.showArrowsConnectivity&&(this.connectivityAssociationsLineSymbol.marker=new n({color:this.connectivityAssociationsLineSymbol.color,placement:"end",style:"arrow"}));return new q({geometry:l.geometry.clone(),symbol:this.connectivityAssociationsLineSymbol})}),k=g.associations.filter(({associationType:l})=>"attachment"===l).map(l=>{this.structuralAttachmentAssociationsLineSymbol.marker=null;this.showArrowsStructuralAttachment&&(this.structuralAttachmentAssociationsLineSymbol.marker=new n({color:this.structuralAttachmentAssociationsLineSymbol.color,
placement:"end",style:"arrow"}));return new q({geometry:l.geometry.clone(),symbol:this.structuralAttachmentAssociationsLineSymbol})}),this._internalGraphicsLayerConnectivity.removeAll(),0<h.length&&this._internalGraphicsLayerConnectivity.addMany(h),this._internalGraphicsLayerStructuralAttachment.removeAll(),0<k.length&&this._internalGraphicsLayerStructuralAttachment.addMany(k))},({message:g})=>{this._set("executionError",g)}))}_createInternalGraphicsLayer(b){return new z({listMode:"hide",internal:!0,
title:b})}_removeInternalGraphicsLayers(){this._internalGraphicsLayerConnectivity&&this._internalGraphicsLayerStructuralAttachment&&this.view?.map&&(this.view.map.remove(this._internalGraphicsLayerConnectivity),this.view.map.remove(this._internalGraphicsLayerStructuralAttachment))}};d.__decorate([e.property()],c.prototype,"_initialValidationsFinished",void 0);d.__decorate([e.property()],c.prototype,"autoRefreshAssociations",void 0);d.__decorate([e.property({type:p,nonNullable:!0})],c.prototype,"connectivityAssociationsLineSymbol",
void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"executionError",void 0);d.__decorate([e.property({type:Boolean,value:!0})],c.prototype,"includeConnectivityAssociations",null);d.__decorate([e.property({type:Boolean,value:!0})],c.prototype,"includeStructuralAttachmentAssociations",null);d.__decorate([e.property()],c.prototype,"loadErrors",void 0);d.__decorate([e.property()],c.prototype,"maxAllowableAssociations",void 0);d.__decorate([e.property()],c.prototype,"messages",void 0);d.__decorate([e.property()],
c.prototype,"showAssociationsEnabled",void 0);d.__decorate([e.property()],c.prototype,"showArrowsConnectivity",void 0);d.__decorate([e.property()],c.prototype,"showArrowsStructuralAttachment",void 0);d.__decorate([e.property({readOnly:!0})],c.prototype,"state",null);d.__decorate([e.property({type:p,nonNullable:!0})],c.prototype,"structuralAttachmentAssociationsLineSymbol",void 0);d.__decorate([e.property()],c.prototype,"utilityNetwork",null);d.__decorate([e.property()],c.prototype,"view",null);return c=
d.__decorate([x.subclass("esri.widgets.UtilityNetworkAssociations.UtilityNetworkAssociationsViewModel")],c)});