// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../core/accessorSupport/layerContainerType ../../geometry/Extent ../../geometry/SpatialReference ../../chunks/persistableUrlUtils ../../symbols/support/ElevationInfo ../../webdoc/support/opacityUtils".split(" "),function(a,d,k,m,g,n,l){const p={type:Boolean,value:!0,json:{origins:{service:{read:!1,write:!1},"web-map":{read:!1,write:!1}},name:"screenSizePerspective",write:{enabled:!0,layerContainerTypes:d.excludeTables}}},q={type:Boolean,value:!0,json:{name:"disablePopup",read:{reader(c,
b){return!b.disablePopup}},write:{enabled:!0,writer(c,b,e){b[e]=!c}}}},r={type:Boolean,value:!0,nonNullable:!0,json:{name:"showLabels",write:{enabled:!0,layerContainerTypes:d.excludeTables}}};g={type:String,json:{origins:{"portal-item":{write:!1}},write:{isRequired:!0,ignoreOrigin:!0,writer:g.write}}};const t={type:Boolean,value:!0,nonNullable:!0,json:{origins:{service:{read:{enabled:!1}}},name:"showLegend",write:{enabled:!0,layerContainerTypes:d.excludeTables}}};var f={write:{enabled:!0,layerContainerTypes:d.excludeTables},
read:!0};const h={type:Number,json:{origins:{"web-document":f,"portal-item":{write:!0}}}};f={...h,json:{...h.json,origins:{"web-document":{...f,write:{enabled:!0,layerContainerTypes:d.excludeTables,target:{opacity:{type:Number},"layerDefinition.drawingInfo.transparency":{type:Number}}}}},read:{source:["layerDefinition.drawingInfo.transparency","drawingInfo.transparency"],reader(c,b,e){if((!e||"service"===e.origin)&&b.drawingInfo&&void 0!==b.drawingInfo.transparency)return l.transparencyToOpacity(b.drawingInfo.transparency);
if(b.layerDefinition?.drawingInfo&&void 0!==b.layerDefinition.drawingInfo.transparency)return l.transparencyToOpacity(b.layerDefinition.drawingInfo.transparency)}}}};const u={type:k,readOnly:!0,json:{origins:{service:{read:{source:["fullExtent","spatialReference"],reader:(c,b)=>{c=k.fromJSON(c);null!=b.spatialReference&&"object"===typeof b.spatialReference&&(c.spatialReference=m.fromJSON(b.spatialReference));return c}}}},read:!1}},v={type:String,json:{origins:{service:{read:!1},"portal-item":{read:!1}}}},
w={type:Number,json:{origins:{service:{write:{enabled:!1}},"web-scene":{name:"layerDefinition.minScale",write:{enabled:!0,layerContainerTypes:d.excludeTables}}},name:"layerDefinition.minScale",write:!0}},x={type:Number,json:{origins:{service:{write:{enabled:!1}},"web-scene":{name:"layerDefinition.maxScale",write:{enabled:!0,layerContainerTypes:d.excludeTables}}},name:"layerDefinition.maxScale",write:!0}},y={json:{write:{ignoreOrigin:!0,layerContainerTypes:d.excludeTables},origins:{"web-map":{read:!1,
write:!1}}}};a.elevationInfo={value:null,type:n,json:{origins:{service:{name:"elevationInfo",write:!0}},name:"layerDefinition.elevationInfo",write:{enabled:!0,layerContainerTypes:d.excludeTables}}};a.id=v;a.labelsVisible=r;a.legendEnabled=t;a.listMode=y;a.maxScale=x;a.minScale=w;a.opacity=h;a.opacityDrawingInfo=f;a.popupEnabled=q;a.readOnlyService=function(c){return{type:c,readOnly:!0,json:{origins:{service:{read:!0}},read:!1}}};a.sceneLayerFullExtent=u;a.screenSizePerspectiveEnabled=p;a.url=g;Object.defineProperty(a,
Symbol.toStringTag,{value:"Module"})});