// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define(["exports","../../../../core/asyncUtils","../../../../core/lang","../../../../layers/support/featureQueryAll"],function(z,E,F,G){function A(a,b,c,e,d=null,f=!0){const h=[];a={gidToFeatureInfo:new Map,oidToFeatureInfo:new Map,featuresResolved:null==c,fieldsIndex:a.fieldsIndex,objectIdField:a.objectIdField,globalIdField:a.globalIdField,featureOrIdentifierList:c};for(const p of b)if(null==p.error){b=p.objectId??-1;c=p.globalId;if(-1===b||f){var g=b;var n=c,k=a;const {gidToFeatureInfo:q,oidToFeatureInfo:l,
fieldsIndex:w,objectIdField:v,globalIdField:r,featureOrIdentifierList:u}=k;if(!k.featuresResolved&&null!=u){for(const t of u){const m={feature:null,oid:-1,gid:null};if("attributes"in t){m.feature=t;const y=t.attributes;if(null!=y)for(const B in y){if(-1!==m.oid&&null!=m.gid)break;const C=w.normalizeFieldName(B);C===v&&(m.oid=y[B]??-1);C===r&&(m.gid=y[B])}}else m.oid=t.objectId??-1,m.gid=t.globalId;null!=m.gid&&q.set(m.gid,m);-1!==m.oid&&l.set(m.oid,m)}k.featuresResolved=!0}g=(-1!==g?l.get(g):null)??
(null!=n?q.get(n):null)}else g=null;g=g??{feature:null,oid:b,gid:c};b={oid:-1===b?g.oid:b,gid:c??g.gid,feature:g.feature,result:p};h.push(b);-1===b.oid&&null!=b.gid&&null!=d&&(b.oid=d.get(b.gid)??-1);-1===b.oid&&null!=b.gid&&(c=e.get(b.gid),null==c&&(c=[],e.set(b.gid,c)),c.push(b))}return h}async function H(a,b){a=a.i3sOverrides.layer.associatedLayer;if(null!=a?.globalIdField){var c=a.createQuery(),{objectIdField:e,globalIdField:d}=a;c.where=Array.from(b.keys()).map(f=>`${d}='${f}'`).join(" OR ");
c.returnGeometry=!1;c.outFields=[e,d];c.cacheHint=!1;a=await E.resultOrAbort(G.queryAllJSON(a,c));if(a.ok){a=a.value.features;for(const f of a)if(c=f.attributes[d],a=f.attributes[e],null!=c&&null!=a&&-1!==a&&(c=b.get(c),null!=c))for(const h of c)h.oid=a}}}function I(a,b){const c=new Map;b=b.adds;if(!b||0===b.length||null==a.globalIdField)return c;for(const e of b)a=e.oid,b=e.feature,"mesh"===b?.geometry?.type&&c.set(a,b);return c}function J(a,b){const c=b.updates;if(!c||0===c.length)return new D;
const e=new D;b=new Map;for(let d=0;d<a.attributeStorageInfo.length;d++)b.set(a.attributeStorageInfo[d].name,d);a.forEachNode((d,f)=>{for(const p of c){if(null==p.feature)continue;const q=p.feature,l=p.oid,w=f.indexOf(l);for(const v in q.attributes){var h=a.fieldsIndex.normalizeFieldName(v);var g=e;var n=d.index,k=g.get(n);k?g=k:(k=new K,g.set(n,k),g=k);(n=null!=h&&g.get(h))?h=n:(n=[],g.set(h,n),h=n);h.push({featureIndex:w,featureId:l,value:q.attributes[v]})}}});return e}const L={setAttribute(){},
rollback(){},commit(){}};var x;(function(a){a[a.EDITING=0]="EDITING";a[a.ROLLED_BACK=1]="ROLLED_BACK";a[a.COMMITTED=2]="COMMITTED"})(x||={});const K=Map,D=Map;z.createInteractiveEditSession=function(a,b){const c=b.attributes[a.objectIdField];if(null==c)return L;var e=a.sessions.get(c);if(e)return e;const d=F.clone(b.attributes),f=new Set,h=a.i3sOverrides.createInteractiveEditSession(c),g=new Map;let n=x.EDITING;e={setAttribute(k,p){if(n===x.EDITING){var q=a.fieldsIndex.get(k);if(q){var l=a.attributeStorageInfo.findIndex(r=>
r.name===q.name);if(!(0>l)){if(!(k in d))throw Error(`Attribute "${k}" is not an attribute of the edited feature.`);h.setAttribute(l,p);var w=a.attributeStorageInfo[l],v=!1;f.add(k);a.forEachNode((r,u)=>{var t=g.get(r);null==t?(u=u.indexOf(c),g.set(r,u)):u=t;if(-1!==u&&(t=a.getAttributeData(r.index))){const m=t[w.name];m&&(m[u]=p,a.setAttributeData(r.index,t,b),v=!0)}});v&&a.clearMemCache()}}}},rollback(){if(n===x.EDITING){for(const k of f)this.setAttribute(k,d[k]);h.remove();n=x.ROLLED_BACK;a.sessions.delete(c)}},
commit(){n===x.EDITING&&(h.remove(),n=x.COMMITTED,a.sessions.delete(c))}};a.sessions.set(c,e);return e};z.normalizeEditResultsEvent=async function(a,b){const c=new Map,e=A(a,b.addedFeatures,b.edits?.addFeatures,c),d=A(a,b.updatedFeatures,b.edits?.updateFeatures,c);b=A(a,b.deletedFeatures,b.edits?.deleteFeatures,c,b.globalIdToObjectId,!1);0<c.size&&await H(a,c);return{adds:e.filter(f=>-1!==f.oid),updates:d.filter(f=>-1!==f.oid),deletes:b.filter(f=>-1!==f.oid)}};z.processAttributeEdits=function(a,b){var c=
J(a,b);b=I(a,b);if(0!==c.size||0!==b.size){var e=new Map;for(var d=0;d<a.attributeStorageInfo.length;d++)e.set(a.attributeStorageInfo[d].name,d);var f=!1;c.forEach((p,q)=>{const l=a.getAttributeData(q);let w=!1;p.forEach((v,r)=>{const u=null!=l?l[r]:null;r=e.get(r);for(const {featureIndex:t,value:m,featureId:y}of v)u&&(u[t]=m,f=w=!0),a.i3sOverrides.updateAttributeValue(y,r,m)});w&&a.setAttributeData(q,l,null)});f&&a.clearMemCache();var {fieldsIndex:h,i3sOverrides:g,objectIdField:n,globalIdField:k}=
a;c=g.layer.associatedLayer?.infoFor3D;c=new Set(c?[...Object.values(c.assetMapFieldRoles),...Object.values(c.transformFieldRoles)]:[]);for(const [p,q]of b){g.featureAdded(p);({attributes:b}=q);for(const l in b)l!==n&&l!==k&&c.has(l)||(d=h.normalizeFieldName(l),d=null!=d?e.get(d):null,null!=d&&g.updateAttributeValue(p,d,b[l]))}}};z.processGeometryEdits=function(a,b){const c=new Map,e=d=>{for(const {oid:f,feature:h}of d)d=h?.geometry,"mesh"===d?.type&&c.set(f,d)};e(b.adds);e(b.updates);for(const d of b.deletes)c.set(d.oid,
null);for(const [d,f]of c)a.i3sOverrides.updateGeometry(d,f)};Object.defineProperty(z,Symbol.toStringTag,{value:"Module"})});