// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/has ../../../../core/PooledArray ../../../../core/promiseUtils ../../../../geometry/projection/projectBoundingSphere ../../../../chunks/sphere ../../../../support/featureFlags ./I3SNode ./I3SUtil ./ValidatedNode ../../support/ElevationRange ../../support/orientedBoundingBox".split(" "),function(F,O,C,L,G,y,P,r,w,Q,R,H){function A(a,b){return 0>a?-1:0<b?a/b|0:0}function x(a,b){return 0>a?-a-1:0===b?a:a%b}function E(a,b,c){return-1===b?-(a+1):0===c?a:b*c+a}function M(a){if(a)for(let b=
0;b<a.length;b++)for(const c of S)if(c[0]===a[b].metricType)return{lodMetric:c[1],maxError:a[b].maxError};return{lodMetric:r.LodMetric.None,maxError:0}}function T(a){return Math.sqrt(4/Math.PI*a)}class I{constructor(a,b,c,d,e){this.childOffset=a;this.childCount=b;this.visibilityCache=c;this.ref=d;this.node=e;this.useAsHole=0;this.filterImpact=r.NodeFilterImpact.NotChecked;this.traversalState=null;this.parent=-1}invalidateBounds(){this.node?.invalidateServiceBVsInRenderSR();this.ref?.invalidateServiceBVsInRenderSR()}}
class J{constructor(a=[],b=[]){this.nodes=a;this.children=b;this.numNodesWithLoadedChildren=this.lastTraversed=0}}class U{get _useNodePages(){return 0<this._pageSize}constructor(a,b,c,d,e,f,h,g,p,k,q,t,m,l,n,u){this.viewingMode=a;this._layer=b;this._streamDataController=d;this._clientNodeLoader=e;this._viewportQueries=f;this._logger=h;this.holeFilling=g;this._isLoaded=p;this._isReloading=k;this._isSelected=q;this._enable=t;this._needsUpdate=m;this._canRequest=l;this._computeVisibilityObb=n;this._computeNodeFiltering=
u;this._dirty=!0;this._nodePages=new Map;this._clientNodePage=null;this._rootIndex=this._pageSize=0;this._lodMetric=r.LodMetric.None;this._lodConversion=B=>B;this._isEditable=!1;this._urlPrefix="";this._loadingNodes=new Set;this._loadingPages=new Set;this._failedNodes=new Set;this._failedPages=new Set;this._indexMissing=1;this._maxUnloadedPrio=Number.NEGATIVE_INFINITY;this._maxProcessingPrio=Number.POSITIVE_INFINITY;this._version=w.addWraparound(0,2);this._visibilityCacheVersion=w.addWraparound(0,
2);this._maxLevel=1;this._featureEstimate={estimate:0,leavesReached:!1};this._unloadedMemoryEstimate=0;this._missingPagesAndNodes=new C({deallocator:null});this._prefetchNodes=new C({deallocator:null});this._updates=new V(this._missingPagesAndNodes);this._imModificationUncategorized=new C({deallocator:null});this.ignoreServiceObb=!1;this.progressiveLoadPenalty=0;this._pageQueue=[];this._newPages=[];this._layerHasFilter=this.layerHasModifications=this.needNodeElevationRange=!1;this._frameNumber=0;
this._traverseDescendantsQueue=[0];this._traverseDescendantsNestingLevel=0;this._isEditable=P.i3sPatchingEnabled()&&null!=b.associatedLayer?.infoFor3D;b.serviceUpdateTimeStamp?.lastUpdate&&(this._lastUpdate=`${b.serviceUpdateTimeStamp.lastUpdate}`);this._maxLodLevel=this._viewportQueries?this._viewportQueries.maxLodLevel:1;this._init(c)}_init(a){if("page"===a.type){var b=a.rootPage;this._urlPrefix=a.urlPrefix;this._pageSize=a.pageSize;switch(a.lodMetric){case "maxScreenThreshold":this._lodMetric=
r.LodMetric.MaxScreenThreshold;break;case "maxScreenThresholdSQ":this._lodMetric=r.LodMetric.MaxScreenThreshold,this._lodConversion=T}if(this._isEditable){this._rootIndex=-1;var c=x(a.rootIndex,a.pageSize);c=b.nodes[c];c={nodes:[{index:this._rootIndex,children:[a.rootIndex],mesh:void 0,obb:c.obb,lodThreshold:c.lodThreshold}]};this._addPage(A(this._rootIndex,this._pageSize),c);this.getNode(-1).serviceObbInIndexSR=void 0}else this._rootIndex=a.rootIndex;this._addPage(A(a.rootIndex,this._pageSize),b);
this._updateParentsAndLevel()}else"node"===a.type&&(this._urlPrefix=a.urlPrefix,b=new J,this._nodePages.set(0,b),this._isEditable?(this._clientNodePage=new J,b={id:"-1",version:null,mbs:a.rootNode.mbs,obb:a.rootNode.obb,sharedResource:null,geometryData:null,attributeData:null,featureData:null,children:[{id:"root",href:"../root",mbs:a.rootNode.mbs,obb:a.rootNode.obb}]},this._rootIndex=this._makeClientRefNode(new r.NodeBase(b.id,null),-1),(b=this._validateNode(b.id,b))&&this._addNode(b,this._rootIndex)):
this._rootIndex=this._makeRefNode(new r.NodeBase(a.rootNode.id,null),-1),(a=this._validateNode(a.rootNode.id,a.rootNode))&&this._addNode(a,0))}addClientNodeToIndex(a,b){a=new r.NodeBase(a,b);a=this._makeClientRefNode(a,-1);this._linkChildToParentNode(-1,a);this.requestUpdate();return a}removeClientNodeFromIndex(a,b,c){this._destroyClientRefNode(a,b,c);this.requestUpdate()}_loadPage(a){this._loadingPages.add(a);this._streamDataController.request(this._urlPrefix+a,"json").then(b=>{this._pageQueue.push({pageIndex:a,
page:b})}).catch(b=>{this._loadingPages.delete(a);L.isAbortError(b)||(this._failedPages.add(a),this._logger.error("#loadPage()",this._layer,`Error when loading page ${a}`,b))})}_addQueuedPages(a){for(;0<this._pageQueue.length&&!a.done;){const {pageIndex:b,page:c}=this._pageQueue.shift();this._addPage(b,c);this._loadingPages.delete(b);a.madeProgress();this.needNodeElevationRange&&this._newPages.push(b)}this._updateParentsAndLevel()}_invalidateElevationRangeForNewPages(a){if(this.needNodeElevationRange)for(;0<
this._newPages.length&&!a.done;)this._nodePages.get(this._newPages.shift())?.nodes.forEach(b=>{for(b=b.parent;null!=b&&b!==this._rootIndex;){const c=this.getNode(b);c&&!Number.isNaN(c?.elevationRangeMin)&&(c.invalidateElevationRange(),this.invalidateBoundingVolumeCache(b));b=this.getParentIndex(b)}})}_addPage(a,b){const c=[],d=[];b=b.nodes.map((e,f)=>{const h=c.length,g=e.children?e.children.length:0;d.push(this._rootIndex);for(var p=0;p<g;p++)c.push(e.children[p]);const k=`${e.index}`;p=H.Obb.fromJSON(e.obb);
const q=y.fromCenterAndRadius(p.center,p.radius);var t=e.mesh?.attribute;const m=e.mesh?.geometry,l=e.mesh?.material;t={hasSharedResource:!1,isEmpty:null==m,attributes:null!=t?.resource?`${t.resource}`:void 0,geometry:null!=m?.resource?`${m.resource}`:void 0,texture:null!=l?.resource?`${l.resource}`:void 0,geometryDefinition:m?m.definition:-1,materialDefinition:l?l.definition:-1};e=new r.Node(k,E(f,a,this._pageSize),q,g,0,t,this._lastUpdate,this._lodMetric,this._lodConversion(e.lodThreshold),m?m.featureCount:
null);e.serviceObbInIndexSR=p;e.visibilityObbInRenderSR=this._computeVisibilityObb(e);e.vertexCount=m?m.vertexCount:0;return new I(h,g,w.addWraparound(this._visibilityCacheVersion,-2),null,e)});b=new J(b,c);-1===a?this._clientNodePage=b:this._nodePages.set(a,b)}_updateParentsAndLevel(){const a=[],b=(c,d,e)=>{var f=this._getPage(c);if(null!=f){const h=x(c,this._pageSize);f=f.nodes[h];f.parent=null!=d?d:-1;d=f.node;null!=d&&(d.level=e,a.push(c))}};for(b(this._rootIndex,null,0);a.length;){const c=a.pop(),
d=this.getNode(c);if(null!=d)for(let e=0;e<d.childCount;e++){const f=this.getChildIndex(d.index,e);b(f,c,d.level+1);this._maxLevel=Math.max(this._maxLevel,d.level+1)}}}_getPage(a){a=A(a,this._pageSize);return this._getPageFromPageIndex(a)}_getPageFromPageIndex(a){return 0>a?this._clientNodePage:this._nodePages.get(a)}_getNodeInternal(a){const b=this._getPage(a);if(null==b)return null;b.lastTraversed=this._frameNumber;return b.nodes[x(a,this._pageSize)]}_addNode(a,b){a.children&&this.populateChildren(b,
a.children);var c=this.getParent(b);const d=null!=c?c.level+1:0;this._maxLevel=Math.max(this._maxLevel,a.children?d+1:d);const {lodMetric:e,maxError:f}=M(a.lodSelection);c=this._getNodeInternal(b);b=new r.Node(a.id,b,a.mbs,c.childCount,d,a.resources,a.version,e,f,a.numFeatures);c.node=b;a.obb&&(b.serviceObbInIndexSR=H.Obb.fromJSON(a.obb));b.visibilityObbInRenderSR=this._computeVisibilityObb(b);c=c.ref;null!=c&&(null==c.serviceMbsInIndexSR&&(c.serviceMbsInIndexSR=a.mbs),b.shareServiceBVsInRenderSRWith(c),
c.visibilityObbInRenderSR=b.visibilityObbInRenderSR);return b}_makeRefNode(a,b){const c=this._nodePages.get(0);if(-1>b)return this._makeClientRefNode(a,b);if(null==c)return-1;const d=c.nodes.length,e=new I(0,0,w.addWraparound(this._visibilityCacheVersion,-2),a,null);c.nodes.push(e);e.parent=b;a.invalidateServiceBVsInRenderSR();return d}_makeClientRefNode(a,b){const c=this._clientNodePage;if(null==c)return-1;if(0<=b)throw Error("I3SIndex::client side nodes can not be made children of service side nodes.");
const d=-(c.nodes.length+1),e=new I(0,0,w.addWraparound(this._visibilityCacheVersion,-2),a,null);c.nodes.push(e);e.parent=b;a.invalidateServiceBVsInRenderSR();return d}_linkChildToParentNode(a,b){const c=this._clientNodePage;if(!(null==c||0<=a)){var d=x(a,this._pageSize),e=x(b,this._pageSize);d=c.nodes[d];var f=d.childOffset;c.children.splice(d.childOffset+d.childCount,0,b);d.childCount+=1;null!=d.node&&(d.node.childCount+=1);for(const h of c.nodes)h.childOffset>f&&(h.childOffset+=1);c.nodes[e].parent=
a;this._updateParentBoundingInformation(a)}}_destroyClientRefNode(a,b,c){const d=this._clientNodePage;if(null!=d){var e=this.getParentIndex(a);if(null!=e){var f=new Set,h=new Map,g=B=>{var z=x(B,this._pageSize);z=d.nodes[z];if(0<z.childCount)for(var D=z.childOffset;D<z.childOffset+z.childCount;++D)g(d.children[D]);D=z.node?.id??z.ref?.id;if(null==D)throw Error("Node has no id");b(D,B);f.add(z)};g(a);a=d.nodes;var p=d.children,k=d.nodes.map(()=>-1),q=[],t=[];for(var m=0;m<a.length;++m){var l=a[m];
if(!f.has(l)){var n=q.length,u=E(m,-1,this._pageSize);n=E(n,-1,this._pageSize);l.node&&(l.node.index=n);k[m]=n;q.push(l);if(u!==n){l=l.node?.id??l.ref?.id;if(null==l)throw Error("Node has no id");c(l,u,n);h.set(u,n)}}}for(c=0;c<q.length;++c){h=E(c,-1,this._pageSize);m=q[c];u=t.length;for(l=m.childOffset;l<m.childOffset+m.childCount;++l)if(n=p[l],0<=n)t.push(n);else{n=x(n,this._pageSize);const B=a[n];f.has(B)||(t.push(k[n]),B.parent=h)}m.childOffset=u;m.childCount=t.length-u;m.node&&(m.node.childCount=
m.childCount)}d.nodes=q;d.children=t;this._updateParentBoundingInformation(k[x(e,this._pageSize)])}}}_updateParentBoundingInformation(a){do{let d=null;var b=this._clientNodeLoader.indexSR;const e=this._clientNodeLoader.renderSR,f=this._getNodeInternal(a);if(null==f)break;for(let h=0;h<f.childCount;h++){var c=this.getChildIndex(a,h);c=this._getNodeInternal(c);c=null!=c?c.ref||c.node:null;if(null!=c&&0<c.serviceMbsInIndexSR[3])if(null==d)d=y.copy(c.serviceMbsInIndexSR,W);else{const g=X,p=Y,k=Z;G.projectBoundingSphere(c.serviceMbsInIndexSR,
b,g,e);G.projectBoundingSphere(d,b,p,e);y.union(g,p,k);G.projectBoundingSphere(k,e,d,b)}}b=f.ref||f.node;if(null!=b){if(null!=d){let h;(h=b).serviceMbsInIndexSR??(h.serviceMbsInIndexSR=y.create());y.copy(d,b.serviceMbsInIndexSR)}else w.invalidateMbs(b.serviceMbsInIndexSR);b.invalidateServiceBVsInRenderSR();b.geometryObbInRenderSR=null}this.invalidateNodeVisibilityCacheInternal(f);a=this.getParentIndex(a)}while(null!=a)}populateChildren(a,b){var c=this._getNodeInternal(a);const d=this._getPage(a);
c.childOffset=d.children.length;c.childCount=b.length;for(c=0;c<b.length;c++){const e=this._makeRefNode(b[c],a);d.children.push(e)}}getNode(a){a=this._getNodeInternal(a);return null!=a?a.node:null}getIndexById(a){let b;this._forAllNodes((c,d)=>{null!=c.node&&c.node.id===a?b=d:null!=c.ref&&c.ref.id===a&&(b=d)});return b}getNodeById(a){a=this.getIndexById(a);return null!=a&&0<=a?this.getNode(a):null}getChildIndex(a,b){const c=this._getPage(a);if(null==c)return-1;a=c.nodes[x(a,this._pageSize)];return c.children[a.childOffset+
b]}getParentIndex(a){const b=this._getPage(a);return null!=b&&a!==this._rootIndex?b.nodes[x(a,this._pageSize)].parent:null}getParent(a){a=this.getParentIndex(a);return null!=a?this.getNode(a):null}isLeaf(a){a=this._getNodeInternal(a);return null!=a&&0===a.childCount}get rootNode(){return this.getNode(this._rootIndex)}get isEditable(){return this._isEditable}removeAllGeometryObbs(){this._forAllNodes(a=>{null!=a.node&&(a.node.geometryObbInRenderSR=null)})}invalidateVisibilityCache(){this._visibilityCacheVersion=
w.addWraparound(this._visibilityCacheVersion,2)}invalidateNodeVisibilityCache(a){a=this._getNodeInternal(a);null!=a&&this.invalidateNodeVisibilityCacheInternal(a)}invalidateNodeVisibilityCacheInternal(a){a.visibilityCache=w.addWraparound(this._visibilityCacheVersion,-2)}invalidateBoundingVolumeCache(a){a=this._getNodeInternal(a);null!=a&&(a?.invalidateBounds(),this.invalidateNodeVisibilityCacheInternal(a))}updateElevationChanged(a){const b=this._getNodeInternal(a);null!=b&&(this.needNodeElevationRange?
(a=null!=b.node?b.node:b.ref,null!=a&&a.invalidateElevationRange()):this.invalidateBoundingVolumeCache(a))}invalidateGeometryVisibility(a){if(a=this._getNodeInternal(a)?.node)a.geometryObbInRenderSR=null,a.invalidateServiceBVsInRenderSR()}invalidateVisibilityObbs(){null!=this.rootNode&&this.traverse(this.rootNode,a=>{a.visibilityObbInRenderSR=this._computeVisibilityObb(a);a.geometryObbInRenderSR=null;return!0})}_isElevationRangeUpToDate(a){return this.needNodeElevationRange?(a=a?.node??a?.ref)?a.elevationRangeValid:
!0:!0}updateElevationRange(a){this._updateElevationRangeInternal(a,null)}_updateElevationRangeInternal(a,b){const c=this._getNodeInternal(a);if(!c)return!1;const d=c?.node??c?.ref;if(!d)return!1;if(d.elevationRangeValid)return b?.expandElevationRange(d),!0;const e=new R.ElevationRange;var f=!1;for(let g=0;g<c.childCount;g++){var h=this.getChildIndex(a,g);h=this._updateElevationRangeInternal(h,e);f=f||!h}(0===c.childCount||f)&&this._viewportQueries.expandElevationRange(d,!c.node?.resources.isEmpty,
e);f=d.elevationRangeMax;if(d.elevationRangeMin===e.elevationRangeMin&&f===e.elevationRangeMax)return b?.expandElevationRange(d),!0;c.node?.setElevationRange(e);c.ref?.setElevationRange(e);this.invalidateBoundingVolumeCache(a);b?.expandElevationRange(d);return!0}isNodeVisible(a){const b=this._getNodeInternal(a);if(null==b)return!0;var c=b.ref;if(null!=c&&!c.serviceMbsInIndexSR)return!0;if(this._isElevationRangeUpToDate(b)&&(b.visibilityCache&-2)===this._visibilityCacheVersion)return 1===(b.visibilityCache&
1);const d=b.node,e=this._viewportQueries;if(d){var f=e.ensureElevationAgnosticBoundingVolume(d),h=e.isElevationAgnosticBoundingVolumeVisible(f);let g=h;this.needNodeElevationRange&&h&&(h=e.getNodeObbInRenderSRIndependentOfElevationOffset(d),null!=h&&(g=e.isObbVisibleIndependentOfElevation(f,h)));if(!g)return b.visibilityCache=this._visibilityCacheVersion+0,!1}this._layerHasFilter&&this._computeNodeFiltering&&(null!=d||null!=c)&&b.filterImpact===r.NodeFilterImpact.NotChecked&&(f=null!=d?d.serviceMbsInIndexSR:
null!=c?c.serviceMbsInIndexSR:null,b.filterImpact=null!=f?this._computeNodeFiltering(f):r.NodeFilterImpact.Unmodified);f=null!=d&&b.filterImpact===r.NodeFilterImpact.Culled;if(f=!(null!=d&&d.imModificationImpact===r.NodeIMModificationImpact.Culled)&&!f)c=!d||c&&!d.visibilityObbInRenderSR?c??null:d,null!=c&&(this.needNodeElevationRange&&this.updateElevationRange(a),f=e.isNodeVisible(c));b.visibilityCache=this._visibilityCacheVersion+(f?1:0);return f}isGeometryVisible(a){if(!this.isNodeVisible(a))return!1;
a=this._getNodeInternal(a);return null==a?.node?.geometryObbInRenderSR||this.layerHasModifications&&a.node.imModificationImpact===r.NodeIMModificationImpact.NotChecked?!0:this._viewportQueries.isGeometryVisible(a.node)}_traverseCoverage(a,b,c,d,e){a=this._getPage(a);if(null!=a&&0!==b.childCount){var f=b.childOffset+b.childCount,h=[];for(b=b.childOffset;b<f;++b){const g=a.children[b],p=this._getNodeInternal(g);null!=p?.node&&this.isGeometryVisible(g)&&h.push(p)}d/=h.length;for(const g of h)a=g.node.index,
this._isLoaded(a)||this._isReloading(a)?(e.delta=Math.max(e.delta,c),e.coverage+=d):this._traverseCoverage(a,g,c+1,d,e)}}useNodeAsHole(a){if("off"===this.holeFilling)return!1;const b=this._getNodeInternal(a);if(null==b)return!1;if("always"===this.holeFilling)return!0;if((b.useAsHole&-2)===this._version)return 1===(b.useAsHole&1);const c={delta:0,coverage:0};this._traverseCoverage(a,b,0,1,c);a=.5>=c.delta*c.coverage;b.useAsHole=this._version+(a?1:0);return a}get maxLevel(){return this._maxLevel}get dirty(){return this._dirty}destroy(){this._updates.add.prune();
this._updates.update.prune()}requestUpdate(){this._dirty=!0;this._indexMissing=1;this._version=w.addWraparound(this._version,2)}imModificationsChanged(a){this.layerHasModifications=a;this._forAllNodes(({node:b})=>{null!=b&&(b.imModificationImpact=r.NodeIMModificationImpact.NotChecked,b.visibilityObbInRenderSR=this._computeVisibilityObb(b),b.hasModifications&&this.invalidateGeometryVisibility(b.index))});this.invalidateVisibilityCache()}layerFilterChanged(a){this._layerHasFilter=a;this._forAllNodes(b=>
{null!=b&&(b.filterImpact=r.NodeFilterImpact.NotChecked,b=b.node,null!=b&&this.invalidateNodeVisibilityCache(b.index))});this.invalidateVisibilityCache()}update(a,b,c){if(this._dirty){0<this._pageQueue.length&&this._addQueuedPages(b);this._invalidateElevationRangeForNewPages(b);this._maxProcessingPrio=this._maxUnloadedPrio=Number.NEGATIVE_INFINITY;this._missingPagesAndNodes.clear();this._prefetchNodes.clear();this._updates.reset(a);v.clear();var d=!0,e=new K,f=new K,h=this._imModificationUncategorized;
h.clear();var g=new Set,p=0;this.traverseVisible((k,q,t)=>{var m=A(k,this._pageSize);if(null==q)k=this._entryPriority(k),Infinity===k&&(k=this._entryPriority(t)),v.set(m,Math.max(k,v.get(m)||0)),this._loadingPages.has(m)||this._failedPages.has(m)||(this._missingPagesAndNodes.push(m),++p),this._maxProcessingPrio=Math.max(this._maxProcessingPrio,k);else{var l=q.node;this._updateNodeFeatureEstimate(l,f);if(null==l)q=this._entryPriority(k),this._loadingNodes.has(k)||this._failedNodes.has(k)||(this._missingPagesAndNodes.push(k),
v.set(k,q)),this._maxProcessingPrio=Math.max(this._maxProcessingPrio,q);else{t=this._getPage(k);if(0===this._missingPagesAndNodes.length&&!this._useNodePages)for(m=0;m<q.childCount;m++){const n=t.children[q.childOffset+m],u=this._getNodeInternal(n);null==u||u.node||this._loadingNodes.has(n)||this._failedNodes.has(n)||(v.set(n,this._entryPriority(n)),this._prefetchNodes.push(n))}l.failed||l.resources.isEmpty?d&&0<q.childCount&&this._isSelected(l)&&(d=!1):this._isLoaded(k)?(e.known+=l.memory,++e.knownNodes,
this._isSelected(l)?0<q.childCount&&(d=!1):(e.unremoved+=l.memory,d=!1),this._needsUpdate(l)&&(q=this._entryPriority(k),v.set(k,q),this._maxProcessingPrio=Math.max(this._maxProcessingPrio,q),this._updates.update.push(k))):(l.memory&&(e.known+=l.memory,++e.knownNodes),this._isSelected(l)?(0<q.childCount&&(d=!1),l.memory?(e.missing+=l.memory,e.known+=l.memory,++e.knownNodes):++e.missingNodes,a.includes(l.index)?(this._maxProcessingPrio=Math.max(this._maxProcessingPrio,this._entryPriority(k)),this._updates.cancel=
this._updates.cancel.filter(n=>n!==l.index)):!b.done&&this._enable(l)?b.madeProgress():(q=this._entryPriority(k),v.set(k,q),this._maxProcessingPrio=Math.max(this._maxProcessingPrio,q),this._updates.add.push(k),this.layerHasModifications&&c&&null!=l&&l.imModificationImpact===r.NodeIMModificationImpact.NotChecked&&h.push(k))):this._isReloading(k)&&this._updates.remove.push(k))}}},g);this._frameNumber++;this._missingPagesAndNodes.sort((k,q)=>k-q);this._missingPagesAndNodes.filterInPlace((k,q)=>1>q||
this._missingPagesAndNodes.data[q-1]!==k);this._missingPagesAndNodes.sort((k,q)=>v.get(k)-v.get(q));0<this._missingPagesAndNodes.length&&(this._maxUnloadedPrio=v.get(this._missingPagesAndNodes.back()),this._prefetchNodes.clear());this._removeUnusedNodePages(g,p);g=this._updates.add;0<g.length&&this.layerHasModifications&&(0<h.length&&c?.(h),g.filterInPlace(k=>{var q=this._getNodeInternal(k);(q=null==q?.node||q.node.imModificationImpact!==r.NodeIMModificationImpact.Culled)||this.invalidateNodeVisibilityCache(k);
return q}));this._unloadedMemoryEstimate=e.missing-e.unremoved;3<e.knownNodes&&0<e.missingNodes&&(this._unloadedMemoryEstimate+=e.known/e.knownNodes*e.missingNodes);this._unloadedMemoryEstimate=.8*Math.max(0,this._unloadedMemoryEstimate);this._featureEstimate.estimate=this._computeFeatureEstimate(f);this._featureEstimate.leavesReached=d;this._updates.add.filterInPlace(k=>v.get(k)>=this._maxUnloadedPrio).sort((k,q)=>v.get(k)-v.get(q));this._updates.update.sort((k,q)=>v.get(k)-v.get(q));this._indexMissing=
this._loadingPages.size+this._loadingNodes.size+this._missingPagesAndNodes.length;this._dirty=0<this._indexMissing;v.clear()}}checkFeatureTarget(a,b){const c=this._viewportQueries.updateScreenSpaceErrorBias(b);let d=b,e=b,f=c,h=10;for(;h--;){const g=new K;this._updateFeatureEstimate(d,g);if(this._computeFeatureEstimate(g)<=a){if(d>=b||0<g.missingNodes||0===h)break;f=d;d=.5*(d+e)}else e=d,d=.5*(d+f)}this._version=w.addWraparound(this._version,2);this._viewportQueries.updateScreenSpaceErrorBias(c);
return Math.min(b,d)}_removeUnusedNodePages(a,b){if(this._useNodePages){var c=a.size,d=this._nodePages;b=d.size+this._loadingPages.size+b;if(b>N&&b>c){c=[];for(const [e,f]of d)0!==f.numNodesWithLoadedChildren||a.has(e)||c.push([f.lastTraversed,e]);c.sort((e,f)=>e[0]-f[0]).some(e=>{this._deleteNodePage(e[1]);return d.size<=N})}}}_updateFeatureEstimate(a,b){this._version=w.addWraparound(this._version,2);this._viewportQueries.updateScreenSpaceErrorBias(a);this.traverseVisible((c,d)=>this._updateNodeFeatureEstimate(null!=
d?d.node:void 0,b))}_updateNodeFeatureEstimate(a,b){null!=a&&!a.failed&&null!=a.numFeatures&&this._isSelected(a)&&(null!=a.numFeatures?(b.missing+=a.numFeatures,b.known+=a.numFeatures,++b.knownNodes):++b.missingNodes)}_computeFeatureEstimate(a){let b=a.known-a.unremoved;3<a.knownNodes&&0<a.missingNodes&&(b+=a.known/a.knownNodes*a.missingNodes);return Math.max(0,b)}load(){return this._load(this._missingPagesAndNodes)}prefetch(){this._prefetchNodes.sort((a,b)=>v.get(a)-v.get(b));return this._load(this._prefetchNodes)}_load(a){if(0===
a.length||!this._canRequest())return!1;for(;0<a.length&&this._canRequest();){const b=a.pop();this._useNodePages?0<=b?this._loadPage(b):this._loadNode(b):this._loadNode(b)}return!0}get isLoading(){return 0<this._indexMissing}get isPrefetching(){return 0<this._prefetchNodes.length}get indexLoading(){return this._loadingPages.size+this._loadingNodes.size}get indexMissing(){return this._indexMissing}get unloadedMemoryEstimate(){return this._unloadedMemoryEstimate}get updates(){return this._updates}get featureEstimate(){return this._featureEstimate}get maxPriority(){return Math.max(this._maxProcessingPrio,
this._maxUnloadedPrio)}nodeTraversalState(a){if(null==a)return null;const b=a.index,c=this._getNodeInternal(b);if(!c)return null;let d=c?.traversalState;if(d&&(d.version&-2)===this._version)return d;const e=this._viewportQueries.getLodLevel(a),f=this._viewportQueries.hasLOD(a);let h=!0;f?(a=this.getParentIndex(b),null!=a?(a=this._getNodeInternal(a)?.traversalState,h=!!a&&e>a.lodLevel):h=0<e):h=0===a.childCount;if(d)return d.lodLevel=e,d.isChosen=h,d.version=this._version+1,d;d=new r.NodeTraversalState(f,
h,e,this._version+1);return c.traversalState=d}async _loadNode(a){this._loadingNodes.add(a);var b=this._getNodeInternal(a).ref;if(null==b)this._failedNodes.add(a);else{b=b.id;var c=this._urlPrefix+b,d=()=>{this._loadingNodes.delete(a);0===this._missingPagesAndNodes.length&&0===this._loadingNodes.size&&this.requestUpdate()},e=null;try{e=0<=a?await this._streamDataController.request(c,"json"):await this._clientNodeLoader.loadNodeJSON(b)}catch(f){d();L.isAbortError(f)||(this._logger.error("#loadNode()",
this._layer,"Error loading node: "+c),this._failedNodes.add(a));return}d();b=this._validateNode(b,e);null!=b&&(b.obb&&this.invalidateNodeVisibilityCache(a),b=this._addNode(b,a),this.nodeTraversalState(b))}}_validateNode(a,b){if(null==b||"object"!==typeof b||b.id!==a)return this._logger.error("#validateNode()",this._layer,`Invalid node. Wrong type or wrong id "${a}"`),null;if(!Array.isArray(b.mbs))return this._logger.error("#validateNode()",this._layer,`Invalid bounding volume on node ${a}.`),null;
b.sharedResource&&"./shared"!==b.sharedResource.href&&"./shared/"!==b.sharedResource.href&&this._logger.warn("#validateNode()",this._layer,`Invalid shared resource href on node "${a}"`);var c=b.geometryData;null==c||Array.isArray(c)&&0===c.length||Array.isArray(c)&&1===c.length&&"./geometries/0"===c[0].href||this._logger.warn("#validateNode()",this._layer,`Invalid geometry data on node "${a}"`);c=b.attributeData;const d=this._layer.attributeStorageInfo;null==c||Array.isArray(c)&&!c.some((g,p)=>g.href!==
`./attributes/${d?.[p]?.key??`f_${p}`}/0`)||this._logger.warn("#validateNode()",this._layer,`Invalid attribute data on node "${a}"`);b.featureData&&1<b.featureData.length&&this._logger.warn("#validateNode()",this._layer,`Node ${a} has ${b.featureData.length} bundles. Only the first bundle will be loaded.`);c=b.hasOwnProperty("obb")&&!this.ignoreServiceObb?b.obb:void 0;const e=b.featureData&&1===b.featureData.length&&b.featureData[0].featureRange?b.featureData[0].featureRange[1]-b.featureData[0].featureRange[0]+
1:void 0;var f=g=>{if(null==g)return null;var p=k=>this._logger.error("#validateNode()",this._layer,`Invalid node reference on node ${a}: ${k}`);if("number"===typeof g.id)p(`id ${g.id} is a number instead of a string.`);else if("string"!==typeof g.id||!Array.isArray(g.mbs))return p("Missing or invalid id."),null;if(!Array.isArray(g.mbs))return p(`Invalid bounding volume on reference ${g.id}.`),null;g.href&&g.href!=="../"+g.id&&this._logger.error("#validateNode()",this._layer,`Invalid node href on node "${a}"`);
p=new r.NodeBase(`${g.id}`,g.mbs);p.serviceObbInIndexSR=!this.ignoreServiceObb&&g.hasOwnProperty("obb")&&g.obb?H.Obb.fromJSON(g.obb):null;p.visibilityObbInRenderSR=this._computeVisibilityObb(p);return p};f=Array.isArray(b.children)?b.children.map(f).filter(g=>null!=g):null;const h=!0===b.isEmpty;return new Q.ValidatedNode(a,b.mbs,c,"string"===typeof b.version?b.version:null,{isEmpty:!(b.featureData?.length??!1)&&h,hasSharedResource:null!=b.sharedResource,attributes:b.attributeData?a:void 0,texture:b.textureData&&
0<b.textureData.length?a:void 0,geometry:null!=b.geometryData?a:void 0},f,Array.isArray(b.lodSelection)?b.lodSelection:null,e)}resetFailedNodes(){this._failedNodes.clear();this._failedPages.clear();this._forAllNodes(a=>{null!=a.node&&(a.node.failed=!1)})}_entryPriority(a){var b=this._getNodeInternal(a),c=this.getParentIndex(a);if(null==b||null==c&&null==b.node)return null==c?Infinity:this._entryPriority(c);let d=0;b.node&&null!=c&&(c=this._getNodeInternal(c).traversalState,null!=c&&(d=c.lodLevel));
for(c=this.progressiveLoadPenalty;null!=a;a=this.getParentIndex(a))if(this._isLoaded(a)){c=0;break}b=null!=b.ref?this._viewportQueries.distToPOI(b.ref):null!=b.node?this._viewportQueries.distToPOI(b.node):0;return-b-d*(b+this.progressiveLoadPenalty)+c}traverseVisible(a,b){const c=this._getNodeInternal(this._rootIndex);null==c?a(this._rootIndex,null,null):this._traverseVisible(this._rootIndex,null,c,a,b)}_traverseVisible(a,b,c,d,e){var f=A(a,this._pageSize);e&&e.add(f);if(c.node&&0===c.childCount)this.isGeometryVisible(a)&&
d(a,c,b);else if(this.isNodeVisible(a)&&(d(a,c,b),null!=c.node&&(b=this.nodeTraversalState(c.node),!b?.nodeHasLOD||b.lodLevel!==this._maxLodLevel)))for(f=this._getPageFromPageIndex(f),b=0;b<c.childCount;b++){const g=f.children[c.childOffset+b];var h=this._getNodeInternal(g);h?this._traverseVisible(g,a,h,d,e):(e&&(h=A(g,this._pageSize),e.add(h)),d(g,null,a))}}traverse(a,b){b(a)&&this.traverseDescendants(a,b)}traverseDescendants(a,b){++this._traverseDescendantsNestingLevel;a=a.index;var c=this._pageSize,
d=A(a,c),e=this._getPageFromPageIndex(d);if(null!=e){var f=this._frameNumber,h=this._nodePages;e.lastTraversed=f;a=x(a,c);var g=e.nodes[a];({childCount:a}=g);if(0!==a){a=1===this._traverseDescendantsNestingLevel?this._traverseDescendantsQueue:[0];var p=0,k=[],{childOffset:q,childCount:t}=g;({children:g}=e);a.length=2**Math.ceil(Math.log2(p+t));for(var m=q;m<q+t;++m){var l=g[m];0<=l?(a[p]=l,++p):k.push(l)}if(0<k.length&&(g=this._clientNodePage))for(m=g.children,l=0;l<k.length;){var n=k[l];++l;n=g.nodes[-n-
1];var u=n.node;if(u&&b(u)&&({childCount:u}=n,0!==u))for({childOffset:n}=n,u=n+u;n<u;++n)k.push(m[n])}if(0<p)if(k=0,0<c)for(d*=c,g=e.nodes;k<p;){l=a[k];++k;if(d<=l&&l<d+c)m=e;else{n=l/c|0;m=h.get(n);if(void 0===m)continue;m.lastTraversed=f;e=m;g=e.nodes;d=c*n}l=g[l-d];n=l.node;if(null!=n&&!1!==b(n)&&({childCount:n}=l,0!==n)){a.length<p+n&&(a.length=2**Math.ceil(Math.log2(p+n)));for(;a.length<p+n;)a.length+=a.length;m=m.children;({childOffset:l}=l);for(n=l+n;l<n;++l)a[p]=m[l],++p}}else if(c=h.get(0))for(;k<
p;)if(f=a[k],++k,h=c.nodes[f],(f=h.node)&&b(f)&&({childCount:e}=h,0!==e))for(a.length=Math.max(a.length,2**Math.ceil(Math.log2(p+e))),f=c.children,{childOffset:h}=h,e=h+e;h<e;++h)a[p]=f[h],++p;--this._traverseDescendantsNestingLevel}}}updateChildrenLoaded(a,b){for(a=this.getNode(a);null!=a;){var c=a.childrenLoaded;const d=c+b;a.childrenLoaded=d;c=0===c?1:0===d?-1:0;a=a.index;0!==c&&(this._getPage(a).numNodesWithLoadedChildren+=c);a=this.getParent(a)}}checkChildrenLoadedInvariant(){if(null==this.rootNode)return!0;
const a=[],b=c=>{let d=this._isLoaded(c.index)||this._isReloading(c.index)?1:0;this.traverseDescendants(c,e=>{d+=b(e);return!1});c.childrenLoaded!==d&&a.push(c.index);return d};b(this.rootNode);a.length&&this._logger.error("childrenLoaded invariant broken at following nodes: "+a.join(","));return 0<a.length}updateElevationInfo(a,b){this.needNodeElevationRange=b&&!!a&&("relative-to-ground"===a.mode||"relative-to-scene"===a.mode||"on-the-ground"===a.mode);this._viewportQueries.updateElevationInfo(a);
this.invalidateAllElevationRanges()}invalidateAllElevationRanges(){this._forAllNodes(a=>{a?.invalidateBounds();a.node?.invalidateElevationRange();a.ref?.invalidateElevationRange()})}_forAllNodes(a){if(null!=this._clientNodePage){var b=this._clientNodePage;for(var c=0;c<b.nodes.length;c++)a(b.nodes[c],-(c+1))}for(const [d,e]of this._nodePages)for(b=d*this._pageSize,c=0;c<e.nodes.length;c++)a(e.nodes[c],b+c)}clearCaches(){if(this._useNodePages){const a=this._nodePages,b=new Set;this.traverseVisible(c=>
b.add(A(c,this._pageSize)));for(const [c,d]of a)if(0!==d.numNodesWithLoadedChildren||b.has(c))for(const e of d.nodes)e.traversalState=null;else this._deleteNodePage(c)}}_deleteNodePage(a){this._nodePages.delete(a)}get test(){}}const v=new Map;class V{constructor(a){this.missing=a;this.update=new C({deallocator:null});this.add=new C({deallocator:null});this.remove=new C({deallocator:null});this.cancel=[]}reset(a){this.add.clear();this.update.clear();this.cancel=a}}const S=[["maxScreenThreshold",r.LodMetric.MaxScreenThreshold],
["screenSpaceRelative",r.LodMetric.ScreenSpaceRelative],["removedFeatureDiameter",r.LodMetric.RemovedFeatureDiameter],["distanceRangeFromDefaultCamera",r.LodMetric.DistanceRangeFromDefaultCamera]];class K{constructor(){this.unremoved=this.missingNodes=this.missing=this.knownNodes=this.known=0}}const W=y.create(),X=y.create(),Y=y.create(),Z=y.create(),N=O("esri-mobile")?100:300;F.I3SIndex=U;F.selectErrorMetric=M;Object.defineProperty(F,Symbol.toStringTag,{value:"Module"})});