// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../geometry ../../../../request ../../../../core/arrayUtils ../../../../core/Error ../../../../core/has ../../../../core/typedArrayUtil ../../../../core/libs/gl-matrix-2/math/mat4 ../../../../core/libs/gl-matrix-2/factories/mat4f64 ../../../../chunks/vec32 ../../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../../geometry/projection ../../../../geometry/spatialReferenceEllipsoidUtils ../../../../geometry/projection/projectVectorToVector ../../../../geometry/support/aaBoundingRect ../../../../chunks/sphere ../../../../rest/support/Query ./I3SBinaryReader ./I3SProjectionUtil ../support/edgeUtils ../support/symbolColorUtils ../../support/orientedBoundingBox ../../../../geometry/SpatialReference".split(" "),
function(h,I,ba,J,r,ca,K,da,ea,x,v,fa,ha,L,w,ia,ja,ka,la,M,E,N,O){function F(a){return a?parseInt(a.substring(a.lastIndexOf("/")+1,a.length),10):void 0}function P(a,b){var c=b[0],f=b[1];b=b[3];const e=a[0]-c;c-=a[2];const d=a[1]-f;a=f-a[3];f=Math.max(e,c,0);const l=Math.max(d,a,0);f=f*f+l*l;return f>b*b?h.MbsIntersectResult.OUTSIDE:0<f?h.MbsIntersectResult.INTERSECTS_CENTER_OUTSIDE:-Math.max(e,c,d,a)>b?h.MbsIntersectResult.INSIDE:h.MbsIntersectResult.INTERSECTS_CENTER_INSIDE}function Q(a,b,c){const f=
[],e=c?.missingFields;c=c?.originalFields;for(const d of a){a=d.toLowerCase();let l=!1;for(const p of b)if(a===p.name.toLowerCase()){f.push(p.name);l=!0;c&&c.push(d);break}!l&&e&&e.push(d)}return f}function ma(a,b,c){const f=new Map,e=[];c=c();for(const p of a){var d=p.attributes[b];for(var l=0;l<c.length;l++){a=c[l];const m=a.featureIds.indexOf(d);if(0<=m){d=f.get(a.node);d||(d={node:a.node,indices:[],graphics:[]},e.push(d),f.set(a.node,d));d.indices.push(m);for(d.graphics.push(p);0<l;l--)c[l]=c[l-
1];c[0]=a;break}}}return e}async function na(a,b,c,f,e){b.sort((p,m)=>p.attributes[c]-m.attributes[c]);var d=b.map(p=>p.attributes[c]);const l=[];f=Q(f,a.fields,{originalFields:l});a=await R(a,d,f,e);for(e=0;e<b.length;e++){d=b[e];const p=a[e],m={};if(d.attributes)for(const q in d.attributes)m[q]=d.attributes[q];for(let q=0;q<l.length;q++)m[l[q]]=p[f[q]];d.attributes=m}return b}function R(a,b,c,f){var e=a.capabilities.query.maxRecordCount;if(null!=e&&b.length>e)return e=J.splitIntoChunks(b,e),Promise.all(e.map(d=>
R(a,d,c,f))).then(d=>d.flat());e=new ja({objectIds:b,outFields:c,orderByFields:[a.objectIdField]});return a.queryFeatures(e,f).then(d=>{if(d&&d.features&&d.features.length===b.length)return d.features.map(l=>l.attributes);throw new r("scenelayer:feature-not-in-associated-layer","Feature not found in associated feature layer");})}async function S(a,b,c,f,e,d,l,p){const m=[];for(const q of b)q&&e.includes(q.name)&&m.push({url:`${a}/nodes/${c}/attributes/${q.key}/0`,storageInfo:q});a=await Promise.allSettled(m.map(q=>
ba(q.url,{responseType:"array-buffer",query:{...l,token:d},signal:p?.signal}).then(t=>ka.readBinaryAttribute(q.storageInfo,t.data))));b=[];for(const q of f){f={};for(c=0;c<a.length;c++)e=a[c],"fulfilled"===e.status&&(f[m[c].storageInfo.name]=T(e.value,q));b.push(f)}return b}function T(a,b){if(!a)return null;b=a[b];return K.isInt16Array(a)?-32768===b?null:b:K.isInt32Array(a)?b===oa?null:b:b!==b?null:b}function U(a){var b=a.store,c=b.indexCRS||b.geographicCRS;if(b=void 0===c?b.indexWKT:void 0)if(a.spatialReference){if(b!==
a.spatialReference.wkt)throw new r("layerview:store-spatial-reference-wkt-index-incompatible","The indexWKT of the scene layer store does not match the WKT of the layer spatial reference",{});}else throw new r("layerview:no-store-spatial-reference-wkt-index-and-no-layer-spatial-reference","Found indexWKT in the scene layer store but no layer spatial reference",{});c=c?new O(F(c)):a.spatialReference;return c.equals(a.spatialReference)?a.spatialReference:c}function V(a){var b=a.store,c=b.vertexCRS||
b.projectedCRS;if(b=void 0===c?b.vertexWKT:void 0)if(a.spatialReference){if(b!==a.spatialReference.wkt)throw new r("layerview:store-spatial-reference-wkt-vertex-incompatible","The vertexWKT of the scene layer store does not match the WKT of the layer spatial reference",{});}else throw new r("layerview:no-store-spatial-reference-wkt-vertex-and-no-layer-spatial-reference","Found vertexWKT in the scene layer store but no layer spatial reference",{});c=c?new O(F(c)):a.spatialReference;return c.equals(a.spatialReference)?
a.spatialReference:c}function B(a,b,c){if(!fa.canProjectWithoutEngine(a,b))throw new r("layerview:spatial-reference-incompatible","The spatial reference of this scene layer is incompatible with the spatial reference of the view",{});if("local"===c&&!W(a,b))throw new r("layerview:spatial-reference-incompatible","The spatial reference of this scene layer is incompatible with the spatial reference of the view",{});}function W(a,b){return a.equals(b)||a.isWGS84&&b.isWebMercator||a.isWebMercator&&b.isWGS84}
function X(a,b,c){const f=U(a);a=V(a);B(f,b,c);B(a,b,c)}const z=w.create();h.MbsIntersectResult=void 0;(function(a){a[a.OUTSIDE=0]="OUTSIDE";a[a.INTERSECTS_CENTER_OUTSIDE=1]="INTERSECTS_CENTER_OUTSIDE";a[a.INTERSECTS_CENTER_INSIDE=2]="INTERSECTS_CENTER_INSIDE";a[a.INSIDE=3]="INSIDE"})(h.MbsIntersectResult||(h.MbsIntersectResult={}));const oa=-(2**31);I=M.createSolidEdgeMaterial({color:[0,0,0,0],opacity:0});class Y{constructor(){this.material=this.edgeMaterial=null;this.castShadows=!0}}const pa=[v.create(),
v.create(),v.create(),v.create(),v.create(),v.create(),v.create(),v.create()],G=w.create(),C=w.create(),Z=new N.Obb,k=v.create(),aa={data:Array(72),size:3,exclusive:!0,stride:3},D=ea.create();h.SymbolInfo=Y;h.addWraparound=function(a,b){return(a|0)+(b|0)|0};h.checkPointCloudLayerCompatibleWithView=function(a,b){B(a.spatialReference,b.spatialReference,b.viewingMode)};h.checkPointCloudLayerValid=function(a){var b;(b=null==a.store?.defaultGeometrySchema)||(a=a.store.defaultGeometrySchema,b=!!(null==
a.geometryType||"points"!==a.geometryType||null!=a.topology&&"PerAttributeArray"!==a.topology||null!=a.encoding&&""!==a.encoding&&"lepcc-xyz"!==a.encoding||null==a.vertexAttributes?.position));if(b)throw new r("pointcloud:unsupported-geometry-schema","The geometry schema of this point cloud scene layer is not supported.",{});};h.checkRecyclable=function(a,b,c){if(a.serviceUpdateTimeStamp?.lastUpdate!==b.serviceUpdateTimeStamp?.lastUpdate||!c.isEmpty||a.associatedLayer?.url!==b.associatedLayer?.url)throw new r("layerview:recycle-failed");
};h.checkSceneLayerCompatibleWithView=function(a,b){X(a,b.spatialReference,b.viewingMode)};h.checkSceneLayerValid=function(a){var b;(b=null==a.store?.defaultGeometrySchema)||(b=a.store.defaultGeometrySchema,b=!!(null!=b.geometryType&&"triangles"!==b.geometryType||null!=b.topology&&"PerAttributeArray"!==b.topology||null==b.vertexAttributes?.position));if(b)throw new r("scenelayer:unsupported-geometry-schema","The geometry schema of this scene layer is not supported.",{url:a.parsedUrl.path});};h.checkSpatialReference=
B;h.checkSpatialReferences=X;h.computeVisibilityObb=function(a,b,c,f,e,d,l){if(!d||0===d.length||null==b||!a.serviceMbsInIndexSR)return null;const p=la.computeGlobalTransformation(a.serviceMbsInIndexSR,e,"none",c,b);da.invert(D,p);let m=null;const q=()=>{if(!m)if(m=pa,w.empty(C),null!=a.serviceObbInIndexSR){a.serviceObbInIndexSR.transform(Z,c,b,e,l);Z.getCorners(m);for(var g of m)x.transformMat4(g,g,D),w.expandPointInPlace(C,g)}else{var n=a.serviceMbsInIndexSR;if(n)for(g=n[3],L.projectVectorToVector(ia.getCenter(n),
c,k,b),x.transformMat4(k,k,D),k[2]+=e,n=0;8>n;++n){const u=m[n];x.copy(u,[k[0]+(n&1?g:-g),k[1]+(n&2?g:-g),k[2]+(n&4?g:-g)]);w.expandPointInPlace(C,u)}}};let t=Infinity,y=-Infinity;const A=g=>{if("replace"===g.type&&(g=g.geometry,g?.hasZ)){w.empty(G);var n=g.spatialReference||f;g=g.rings.reduce((u,qa)=>qa.reduce((ra,H)=>{x.set(k,H[0],H[1],H[2]);L.projectVectorToVector(k,n,k,b);x.transformMat4(k,k,D);w.expandPointInPlace(G,k);return Math.min(k[2],ra)},u),Infinity);q();w.intersects(C,G)&&(t=Math.min(t,
g),y=Math.max(y,g))}};d.forEach(g=>A(g));if(Infinity===t)return null;d=(g,n,u)=>{x.transformMat4(k,u,p);g[n]=k[0];g[n+1]=k[1];g[n+2]=k[2];n+=24;u[2]=t;x.transformMat4(k,u,p);g[n]=k[0];g[n+1]=k[1];g[n+2]=k[2];n+=24;u[2]=y;x.transformMat4(k,u,p);g[n]=k[0];g[n+1]=k[1];g[n+2]=k[2]};for(let g=0;8>g;++g)d(aa.data,3*g,m[g]);return N.compute(aa)};h.containsDraco=function(a){if(ca("disable-feature:i3s-draco")||!a)return!1;for(const b of a)for(const c of b.geometryBuffers)if("draco"===c.compressedAttributes?.encoding)return!0;
return!1};h.extractWkid=F;h.filterInPlace=function(a,b,c){let f=0,e=0;for(let d=0;d<b.length&&f<a.length;d++)a[f]===b[d]&&(c(d)&&(a[e]=a[f],e++),f++);a.length=e};h.findFieldsCaseInsensitive=Q;h.findIntersectingNodes=function(a,b,c,f){c.traverse(b,e=>{const d=e.serviceMbsInIndexSR;if((null!=d&&P(a,d))===h.MbsIntersectResult.OUTSIDE)return!1;f(e);return!0})};h.getCacheKeySuffix=function(a,b){return null==b?"@null":b===ha.getSphericalPCPF(b)?"@ECEF":a.equals(b)?"":null!=b.wkid?"@"+b.wkid:null};h.getCachedAttributeValue=
T;h.getClipRect=function(a,b){if(0===b.rotationScale[1]&&0===b.rotationScale[2]&&0===b.rotationScale[3]&&0===b.rotationScale[5]&&0===b.rotationScale[6]&&0===b.rotationScale[7])return z[0]=(a[0]-b.position[0])/b.rotationScale[0],z[1]=(a[1]-b.position[1])/b.rotationScale[4],z[2]=(a[2]-b.position[0])/b.rotationScale[0],z[3]=(a[3]-b.position[1])/b.rotationScale[4],z};h.getIndexCrs=U;h.getSymbolInfo=function(a){const b=new Y;var c=!1;let f=!1;for(const d of a.symbolLayers.items)if("fill"===d.type&&d.enabled){var e=
d.material;a=d.edges;null==e||c||(c=e.color,e=E.parseColorMixMode(e.colorMixMode),b.material=null!=c?{color:[c.r/255,c.g/255,c.b/255],alpha:c.a,colorMixMode:e}:{color:[1,1,1],alpha:1,colorMixMode:E.ColorMixModeEnum.Multiply},b.castShadows=d.castShadows,c=!0);null==a||f||(b.edgeMaterial=M.createMaterialFromEdges(a,{}),f=!0)}b.material||(b.material={color:[1,1,1],alpha:1,colorMixMode:E.ColorMixModeEnum.Multiply});return b};h.getVertexCrs=V;h.intersectBoundingRectWithMbs=P;h.invalidateMbs=function(a){null!=
a&&(a[3]=-1)};h.isSupportedLocalModeProjection=W;h.isValidMbs=function(a){return 0<=a[3]};h.objectIdFilter=function(a,b,c){let f=0,e=0;for(;f<c.length;)0<=J.binaryIndexOf(a,c[f])===b&&(c[e]=c[f],e++),f++;c.length=e};h.queryAttributesFromCachedAttributesId=S;h.rendererNeedsTextures=function(a){if(null==a||"simple"!==a.type&&"class-breaks"!==a.type&&"unique-value"!==a.type||("unique-value"===a.type||"class-breaks"===a.type)&&null==a.defaultSymbol)return!0;a=a.getSymbols();if(0===a.length)return!0;for(const b of a){if("mesh-3d"!==
b.type||0===b.symbolLayers.length)return!0;for(const c of b.symbolLayers.items)if("fill"!==c.type||null==c.material?.color||"replace"!==c.material.colorMixMode)return!0}return!1};h.transparentEdgeMaterial=I;h.whenGraphicAttributes=async function(a,b,c,f,e,d){if(0===b.length)return[];const l=a.attributeStorageInfo;if(null!=a.associatedLayer)try{return await na(a.associatedLayer,b,c,f,d)}catch(p){if(a.associatedLayer.loaded)throw p;}if(l){b=ma(b,c,e);if(null==b)throw new r("scenelayer:features-not-loaded",
"Tried to query attributes for unloaded features");const p=a.parsedUrl.path;return(await Promise.all(b.map(m=>S(p,l,m.node.resources.attributes,m.indices,f,a.apiKey,a.customParameters,d).then(q=>{for(let t=0;t<m.graphics.length;t++){const y=m.graphics[t],A=q[t];if(y.attributes)for(const g in y.attributes)g in A||(A[g]=y.attributes[g]);y.attributes=A}return m.graphics})))).flat()}throw new r("scenelayer:no-attribute-source","This scene layer does not have a source for attributes available");};Object.defineProperty(h,
Symbol.toStringTag,{value:"Module"})});