// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../geometry/support/aaBoundingRect ../../../../layers/support/TileInfo ./decluttering/SymbolFader ./style/StyleDefinition ../webgl/enums ../webgl/RenderableTile ../webgl/TileContainer ../../tiling/TileCoverage ../../tiling/TileKey ../../../webgl/enums".split(" "),function(z,A,D,E,m,u,F,G,H,I,g){function B(a,b){if(a){const d=a.getLayoutProperty("visibility");if(!d||d.getValue()!==m.Visibility.NONE&&(void 0===a.minzoom||a.minzoom<b+1E-6)&&(void 0===a.maxzoom||a.maxzoom>=b-1E-6))return!0}return!1}
class J extends G{constructor(a){super(a);this._backgroundTiles=[];this._computeDisplayInfoView(a)}destroy(){this.removeAllChildren();this._spriteMosaic?.dispose();this._spriteMosaic=null;this._glyphMosaic?.dispose();this._glyphMosaic=null;null!=this._symbolFader&&(this._symbolFader.clear(),this._symbolFader=null);this._styleRepository=null;this._backgroundTiles=[]}get fading(){return this._symbolFader?.fading??!1}get symbolFader(){return this._symbolFader}get symbolRepository(){return this._symbolFader?.symbolRepository}setStyleResources(a,
b,d,c){this._spriteMosaic=a;this._glyphMosaic=b;this._styleRepository=d;this._tileInfoView=c;this._computeDisplayInfoView(c);null==this._symbolFader&&(this._symbolFader=new E.SymbolFader(this._styleRepository,this.children));this._symbolFader.styleRepository=d}setSpriteMosaic(a){this._spriteMosaic?.dispose();this._spriteMosaic=a}deleteStyleLayers(a){null!=this._symbolFader&&this._symbolFader.deleteStyleLayers(a)}createRenderParams(a){return{...super.createRenderParams(a),renderPass:null,styleLayer:null,
styleLayerUID:-1,glyphMosaic:this._glyphMosaic,spriteMosaic:this._spriteMosaic,hasClipping:!!this._clippingInfos}}doRender(a){!this.visible||a.drawPhase!==u.WGLDrawPhase.MAP&&a.drawPhase!==u.WGLDrawPhase.DEBUG||void 0===this._spriteMosaic||super.doRender(a)}addChild(a){super.addChild(a);null!=this._symbolFader?this._symbolFader.addTile(a):a.decluttered=!0;this.requestRender();return a}removeChild(a){null!=this._symbolFader&&this._symbolFader.removeTile(a);this.requestRender();return super.removeChild(a)}renderChildren(a){const {drawPhase:b}=
a;b===u.WGLDrawPhase.DEBUG?super.renderChildren(a):this._doRender(a)}removeAllChildren(){for(let a=0;a<this.children.length;a++){const b=this.children[a];null!=this._symbolFader&&this._symbolFader.removeTile(b);b.dispose()}super.removeAllChildren()}getStencilTarget(){return this.children.filter(a=>a.neededForCoverage&&a.hasData())}restartDeclutter(){null!=this._symbolFader&&this._symbolFader.restartDeclutter()}_doRender(a){const {context:b,state:d}=a;var c=this._styleRepository;if(c){var k=c.layers,
n=this._displayInfo.scaleToZoom(d.scale);0<c.backgroundBucketIds.length&&(a.renderPass="background",this._renderBackgroundLayers(a,c.backgroundBucketIds,n));super.renderChildren(a);a.drawPhase===u.WGLDrawPhase.MAP&&this._fade(n,d);if((c=this.children.filter(f=>f.visible&&f.hasData()))&&0!==c.length){for(var e of c)e.triangleCount=0;b.setStencilWriteMask(0);b.setColorMask(!0,!0,!0,!0);b.setStencilOp(g.StencilOperation.KEEP,g.StencilOperation.KEEP,g.StencilOperation.REPLACE);b.setStencilTestEnabled(!0);
b.setBlendingEnabled(!1);b.setDepthTestEnabled(!0);b.setDepthWriteEnabled(!0);b.setDepthFunction(g.CompareFunction.LEQUAL);b.setClearDepth(1);b.clear(b.gl.DEPTH_BUFFER_BIT);a.renderPass="opaque";for(e=k.length-1;0<=e;e--)this._renderStyleLayer(k[e],a,c);b.setDepthWriteEnabled(!1);b.setBlendingEnabled(!0);b.setBlendFunctionSeparate(g.BlendFactor.ONE,g.BlendFactor.ONE_MINUS_SRC_ALPHA,g.BlendFactor.ONE,g.BlendFactor.ONE_MINUS_SRC_ALPHA);a.renderPass="translucent";for(e=0;e<k.length;e++)this._renderStyleLayer(k[e],
a,c);b.bindVAO();b.setStencilTestEnabled(!0);b.setBlendingEnabled(!0);for(const f of c)f.debugInfo.display.triangleCount=f.triangleCount}else b.bindVAO(),b.setStencilTestEnabled(!0),b.setBlendingEnabled(!0)}}_fade(a,b){null!=this._symbolFader&&(this._symbolFader.update(a,b)||this.requestRender())}_renderStyleLayer(a,b,d){const {displayLevel:c,painter:k,renderPass:n}=b;if(void 0!==a){var e=a.getLayoutProperty("visibility");if(!e||e.getValue()!==m.Visibility.NONE){switch(a.type){case m.StyleLayerType.BACKGROUND:return;
case m.StyleLayerType.FILL:if("opaque"!==n&&"translucent"!==b.renderPass)return;var f="vtlFill";break;case m.StyleLayerType.LINE:if("translucent"!==n)return;f="vtlLine";break;case m.StyleLayerType.CIRCLE:if("translucent"!==n)return;f="vtlCircle";break;case m.StyleLayerType.SYMBOL:if("translucent"!==n)return;f="vtlSymbol"}d=a.type===m.StyleLayerType.SYMBOL?d.filter(l=>l.decluttered):d.filter(l=>l.neededForCoverage);if("vtlSymbol"===f||!(0===d.length||void 0!==a.minzoom&&a.minzoom>=c+1E-6||void 0!==
a.maxzoom&&a.maxzoom<c-1E-6)){e=a.uid;b.styleLayerUID=e;b.styleLayer=a;for(const l of d)if(l.layerData.has(e)){k.renderObjects(b,d,f);break}}}}}_renderBackgroundLayers(a,b,d){const {context:c,painter:k,state:n}=a,e=this._styleRepository;var f=!1;for(var l of b)if(e.getLayerById(l).type===m.StyleLayerType.BACKGROUND&&B(e.getLayerById(l),d)){f=!0;break}if(f){var r=this._tileInfoView;f=r.getTileCoverage(a.state,0,!0,"smallest");var {spans:K,lodInfo:t}=f,{level:v}=t,x=A.create();l=[];if(this._renderPasses){var p=
this._renderPasses[0];null!=this._clippingInfos&&(p.brushes[0].prepareState(a),p.brushes[0].drawMany(a,this._clippingInfos))}p=this._backgroundTiles;var y=0;for(const {row:w,colFrom:L,colTo:M}of K)for(let q=L;q<=M;q++){if(y<p.length){var h=p[y];h.key.set(v,w,t.normalizeCol(q),t.getWorldForColumn(q));r.getTileBounds(x,h.key,!1);h.x=x[0];h.y=x[3];h.resolution=r.getTileResolution(v)}else{h=new I(v,w,t.normalizeCol(q),t.getWorldForColumn(q));const C=r.getTileBounds(A.create(),h),N=r.getTileResolution(v);
h=new F.RenderableTile(h,N,C[0],C[3],512,512,4096,4096);p.push(h)}h.setTransform(n);l.push(h);y++}c.setStencilWriteMask(0);c.setColorMask(!0,!0,!0,!0);c.setStencilOp(g.StencilOperation.KEEP,g.StencilOperation.KEEP,g.StencilOperation.REPLACE);c.setStencilFunction(g.CompareFunction.EQUAL,0,255);c.setStencilTestEnabled(!0);for(const w of b)b=e.getLayerById(w),b.type===m.StyleLayerType.BACKGROUND&&B(b,d)&&(a.styleLayerUID=b.uid,a.styleLayer=b,k.renderObjects(a,l,"vtlBackground"));H.pool.release(f)}}_computeDisplayInfoView(a){let b=
a.tileInfo.lods[0].scale;const d=Math.max(25,a.tileInfo.lods.length),c=[];for(let k=0;k<=d;k++)c.push(b),b/=2;this._displayInfo=D.create({scales:c,size:512,spatialReference:a.spatialReference,numLODs:d})}}z.VectorTileContainer=J;Object.defineProperty(z,Symbol.toStringTag,{value:"Module"})});