// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("require exports ../../../Color ../../../chunks/componentsUtils ../../support/widgetUtils ../../support/jsxFactory ../css".split(" "),function(d,f,k,n,u,b,l){const m=new k([255,127,0]);let h=null;f.SettingsButton=function({viewModel:c,settings:a}){var {state:g}=c;g="not-ready"===g||"waiting"===g;const q=b.tsx("calcite-flow-item",{heading:"Playback Speed",key:"playback-speed",onCalciteFlowItemBack:()=>{a.active=null}},b.tsx("calcite-list",{selectionMode:"single-persist"},[{label:"0.25x",value:.25},
{label:"0.5x",value:.5},{label:"1x",value:1},{label:"1.5x",value:1.5},{label:"2x",value:2}].map(({label:e,value:p})=>b.tsx("calcite-list-item",{key:e,label:e,onclick:()=>{a.speed=e;c.changePlaybackSpeed(p)},selected:e===a.speed})))),r=b.tsx("calcite-flow-item",{heading:"Quality",key:`Quality (${a.quality})`,onCalciteFlowItemBack:()=>{a.active=null}},b.tsx("calcite-list",{selectionMode:"single-persist"},["Auto"].map(e=>b.tsx("calcite-list-item",{key:e,label:e,onclick:()=>{a.quality=e},selected:e===
a.quality})))),t=b.tsx("calcite-flow-item",{heading:"Graphics",key:`Graphics (${a.color})`,onCalciteFlowItemBack:()=>{a.active=null;a.color=h?new k(h):null;a.color&&c.changeGraphicsColor(a.color)}},b.tsx("calcite-block",{heading:"Color",open:!0},b.tsx("calcite-color-picker",{channelsDisabled:!0,format:"hex",savedDisabled:!0,scale:"s",value:a.color?.toHex()??m.toHex(),onCalciteColorPickerChange:e=>{h=e.target.value?.toString()}})));return b.tsx("div",{class:l.css.settings},b.tsx("calcite-popover",
{autoClose:!0,label:"Settings",placement:"top-end",pointerDisabled:!0,referenceElement:"settings-action",scale:"s"},b.tsx("calcite-flow",{class:l.css.settingsFlow,key:"root-flow"},b.tsx("calcite-flow-item",{closable:!1,heading:"Settings",key:"root-flow-item"},b.tsx("calcite-list",null,b.tsx("calcite-list-item",{key:`Speed (${a.speed})`,label:"Speed",onclick:()=>{a.active="speed"}},b.tsx("div",{slot:"content-end"},b.tsx("calcite-chip",{scale:"s",value:a.speed},a.speed)),b.tsx("calcite-icon",{icon:"chevron-right",
scale:"s",slot:"content-end"})),b.tsx("calcite-list-item",{key:`Quality (${a.quality})`,label:"Quality",onclick:()=>{a.active="quality"}},b.tsx("div",{slot:"content-end"},b.tsx("calcite-chip",{scale:"s",value:a.quality},a.quality)),b.tsx("calcite-icon",{icon:"chevron-right",scale:"s",slot:"content-end"})),b.tsx("calcite-list-item",{key:`Graphics (${a.color})`,label:"Graphics",onclick:()=>{a.active="color"}},b.tsx("calcite-color-picker-swatch",{color:a.color?.toString()??m.toString(),scale:"s",slot:"content-end"}),
b.tsx("calcite-icon",{icon:"chevron-right",scale:"s",slot:"content-end"})))),"speed"===a.active?q:null,"quality"===a.active?r:null,"color"===a.active?t:null)),b.tsx("calcite-action",{alignment:"center",bind:c,disabled:g,icon:"sliders",id:"settings-action",key:"settings",scale:"s",slot:"trigger",text:"Settings"}))};f.defaultSettings={active:null,speed:"1x",quality:"Auto",color:null};f.loadSettingsButtonComponents=()=>n.loadCalciteComponents({action:()=>new Promise((c,a)=>d(["../../../chunks/calcite-action"],
c,a)),flow:()=>new Promise((c,a)=>d(["../../../chunks/calcite-flow"],c,a)),"flow-item":()=>new Promise((c,a)=>d(["../../../chunks/calcite-flow-item"],c,a)),icon:()=>new Promise((c,a)=>d(["../../../chunks/calcite-icon"],c,a)),list:()=>new Promise((c,a)=>d(["../../../chunks/calcite-list"],c,a)),"list-item":()=>new Promise((c,a)=>d(["../../../chunks/calcite-list-item"],c,a)),popover:()=>new Promise((c,a)=>d(["../../../chunks/calcite-popover"],c,a)),block:()=>new Promise((c,a)=>d(["../../../chunks/calcite-block"],
c,a)),"color-picker":()=>new Promise((c,a)=>d(["../../../chunks/calcite-color-picker"],c,a)),chip:()=>new Promise((c,a)=>d(["../../../chunks/calcite-chip"],c,a)),"color-picker-swatch":()=>new Promise((c,a)=>d(["../../../chunks/calcite-color-picker-swatch"],c,a))});Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});