// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define(["require","exports","../../assets"],function(M,a,N){function G(b,c,d,f,e,g){const r=d.length,k=e.length;var n=Float64Array.BYTES_PER_ELEMENT,p=Uint32Array.BYTES_PER_ELEMENT;const l=a._lclib._malloc(16+r*(Uint8Array.BYTES_PER_ELEMENT+2*n)+2*k*p);try{const u=l+16-l%16,v=u+r*n,w=v+r*n,h=w+k*p,m=h+k*p;n=()=>[a._lclib.HEAPF64.subarray(u>>3,(u>>3)+r),a._lclib.HEAPF64.subarray(v>>3,(v>>3)+r),a._lclib.HEAPU32.subarray(w>>2,(w>>2)+k),a._lclib.HEAPU32.subarray(h>>2,(h>>2)+k),a._lclib.HEAPU8.subarray(m,
m+r)];const [q,t,D,y,z]=n();q.set(d);t.set(f);D.set(e);y.set(g);z.set(c);let x=b(r,m,u,v,k,w,h);p=b=null;if(x){const E=a._lclib.getLayoutLinksTypes(),F=a._lclib.getLayoutLinksVerticesEndIndices(),H=a._lclib.getLayoutLinksVertices(),K=a._lclib.countLayoutLinksVertices();!k||E&&F?K&&!H?x=!1:(b={types:new Uint8Array(a._lclib.HEAPU8.subarray(E,E+k)),vertexEndIndex:new Uint32Array(a._lclib.HEAPU32.subarray(F>>2,(F>>2)+k)),vertices:new Float64Array(a._lclib.HEAPF64.subarray(H>>3,(H>>3)+2*K))},p=a._lclib.getAuxiliaryGraphicElements()):
x=!1}const [A,B,C,I,J]=n();d.set(A);f.set(B);e.set(C);g.set(I);c.set(J);return{success:x,links:b,graphics:p}}finally{a._lclib._free(l),a._lclib.cleanupLayout()}}let L;a._lclib=null;a.NodeFlag=void 0;(function(b){b[b.None=0]="None";b[b.IsMovable=1]="IsMovable";b[b.IsGeographic=2]="IsGeographic";b[b.IsRoot=4]="IsRoot"})(a.NodeFlag||(a.NodeFlag={}));a.LinkType=void 0;(function(b){b[b.Regular=0]="Regular";b[b.Orthogonal=1]="Orthogonal";b[b.Curved=2]="Curved";b[b.Recursive=3]="Recursive"})(a.LinkType||
(a.LinkType={}));a.LCForceDirectedLayout=void 0;(function(b){b.getMinIdealEdgeLength=function(){return a._lclib.getMinIdealEdgeLength()};b.apply=function(c,d,f,e,g,r=2,k=1,n=-1){return G((p,l,u,v,w,h,m)=>a._lclib.applyForceDirectedLayout(p,l,u,v,w,h,m,r,k,n),c,d,f,e,g)}})(a.LCForceDirectedLayout||(a.LCForceDirectedLayout={}));a.LCCommunityLayout=void 0;(function(b){b.apply=function(c,d,f,e,g,r=2,k=1,n=-1){return G((p,l,u,v,w,h,m)=>a._lclib.applyCommunityLayout(p,l,u,v,w,h,m,r,k,n),c,d,f,e,g)}})(a.LCCommunityLayout||
(a.LCCommunityLayout={}));a.LCSimpleLayout=void 0;(function(b){b.apply=function(c,d,f,e,g){return G(a._lclib.applySimpleLayout,c,d,f,e,g)}})(a.LCSimpleLayout||(a.LCSimpleLayout={}));a.LCHierarchicalLayout=void 0;(function(b){b.apply=function(c,d,f,e,g){return G(a._lclib.applyHierarchicalLayout,c,d,f,e,g)}})(a.LCHierarchicalLayout||(a.LCHierarchicalLayout={}));a.LCRadialTreeLayout=void 0;(function(b){b.apply=function(c,d,f,e,g){return G(a._lclib.applyRadialTreeLayout,c,d,f,e,g)}})(a.LCRadialTreeLayout||
(a.LCRadialTreeLayout={}));a.LCSmartTreeLayout=void 0;(function(b){b.apply=function(c,d,f,e,g){return G(a._lclib.applySmartTreeLayout,c,d,f,e,g)}})(a.LCSmartTreeLayout||(a.LCSmartTreeLayout={}));a.LCChronologicalLayout=void 0;(function(b){b.apply=function(c,d,f,e,g,r,k,n,p){return G((l,u,v,w,h,m,q)=>{if(e.length!==l||g.length!==l||n.length!==h||p.length!==h)return!1;var t=Float64Array.BYTES_PER_ELEMENT;const D=a._lclib._malloc(16+l*t),y=a._lclib._malloc(16+l*t),z=a._lclib._malloc(16+h*t);t=a._lclib._malloc(16+
h*t);const x=D+16-D%16,A=y+16-y%16,B=z+16-z%16,C=t+16-t%16;try{return a._lclib.HEAPF64.subarray(x>>3,(x>>3)+l).set(e),a._lclib.HEAPF64.subarray(A>>3,(A>>3)+l).set(g),a._lclib.HEAPF64.subarray(B>>3,(B>>3)+h).set(n),a._lclib.HEAPF64.subarray(C>>3,(C>>3)+h).set(p),a._lclib.applyChronologicalLayout(l,u,v,w,x,A,h,m,q,B,C)}finally{a._lclib._free(D),a._lclib._free(y),a._lclib._free(z),a._lclib._free(t)}},c,d,f,r,k)}})(a.LCChronologicalLayout||(a.LCChronologicalLayout={}));a.RelationshipInterpretation=void 0;
(function(b){b[b.Undirected=0]="Undirected";b[b.Directed=1]="Directed";b[b.Reversed=2]="Reversed"})(a.RelationshipInterpretation||(a.RelationshipInterpretation={}));a.CentralityMode=void 0;(function(b){b[b.ByCC_Raw=0]="ByCC_Raw";b[b.ByCC_NormalizeGlobally=1]="ByCC_NormalizeGlobally";b[b.ByCC_NormalizeByCC=2]="ByCC_NormalizeByCC"})(a.CentralityMode||(a.CentralityMode={}));a.computeCentrality=function(b,c,d,f,e,g,r,k,n,p,l,u,v,w,h){const m=c.length;var q=Float64Array.BYTES_PER_ELEMENT;const t=Uint32Array.BYTES_PER_ELEMENT,
D=a._lclib._malloc(16+8*b*q+3*m*t);try{const y=D+16-D%16,z=y+b*q,x=z+b*q,A=x+b*q,B=A+b*q,C=B+b*q,I=C+b*q,J=I+b*q,E=J+b*q,F=E+m*t,H=F+m*t;q=()=>[a._lclib.HEAPF64.subarray(y>>3,(y>>3)+b),a._lclib.HEAPF64.subarray(z>>3,(z>>3)+b),a._lclib.HEAPF64.subarray(x>>3,(x>>3)+b),a._lclib.HEAPF64.subarray(A>>3,(A>>3)+b),a._lclib.HEAPF64.subarray(B>>3,(B>>3)+b),a._lclib.HEAPF64.subarray(C>>3,(C>>3)+b),a._lclib.HEAPF64.subarray(I>>3,(I>>3)+b),a._lclib.HEAPF64.subarray(J>>3,(J>>3)+b),a._lclib.HEAPU32.subarray(E>>
2,(E>>2)+m),a._lclib.HEAPU32.subarray(F>>2,(F>>2)+m),a._lclib.HEAPU32.subarray(H>>2,(H>>2)+m)];const [K,O,P,Q,R,S,T,U,V,W,X]=q();K.set(k);O.set(n);P.set(p);Q.set(l);R.set(u);S.set(v);T.set(w);U.set(h);V.set(c);W.set(d);X.set(f);const Y=a._lclib.computeCentrality(b,m,E,F,H,e,g,r,y,z,x,A,B,C,I,J),[Z,aa,ba,ca,da,ea,fa,ha,ia,ja,ka]=q();k.set(Z);n.set(aa);p.set(ba);l.set(ca);u.set(da);v.set(ea);w.set(fa);h.set(ha);c.set(ia);d.set(ja);f.set(ka);return Y}finally{a._lclib._free(D)}};a.defaultBudgetTheoreticalSeconds=
2;a.defaultIdealEdgeLengthMultiplier=1;a.defaultRepulsionRadiusMultiplier=-1;a.isLoaded=function(){return!!a._lclib};a.load=function(){return L?L:L=(new Promise((b,c)=>M(["../../chunks/lclayout"],b,c))).then(b=>b.lclayout).then(({default:b})=>b({locateFile:c=>N.getAssetUrl(`esri/libs/linkchartlayout/${c}`)})).then(b=>{a._lclib=b})};Object.defineProperty(a,Symbol.toStringTag,{value:"Module"})});