// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/handleUtils ../../../../core/mathUtils ../../../../core/reactiveUtils ../../../../core/signal ../../../../chunks/vec32 ../../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../../geometry/projection/projectPointToVector ../../../../geometry/projection/projectVectorToVector ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/aaBoundingRect ../../../../support/elevationInfoUtils ./GrabbingState ./manipulatedObjectUtils ./ManipulatorState ./settings ../visualElements/ExtendedLineVisualElement ../visualElements/LaserlineVisualElement ../visualElements/PointVisualElement ../../layers/graphics/elevationAlignmentUtils ../../layers/graphics/ElevationContext ../../webgl-engine/lib/Material".split(" "),
function(y,n,I,m,z,J,K,L,A,u,M,B,C,v,N,D,O,E,P,Q,R,S){function T(a,b,g){const {view:e,object:c}=a,f=new D.Settings({getTheme:()=>e.effectiveTheme}),p=new O.ExtendedLineVisualElement({view:e,extensionType:f.visualElements.zVerticalLine.extensionType,innerWidth:1,attached:!1,writeDepthEnabled:!1,renderOccluded:S.RenderOccludedFlag.OccludeAndTransparent,isDecoration:!0});b.push(m.watch(()=>f.visualElements.zVerticalLine,d=>d.apply(p),m.initial));const h=new E.LaserlineVisualElement({view:e,intersectsLineInfinite:!0,
attached:!1,isDecoration:!0});var q=I.deg2rad(f.visualElements.heightPlaneAngleCutoff);const r=new E.LaserlineVisualElement({view:e,attached:!1,angleCutoff:q,isDecoration:!0});q=c.elevationInfo;const U=R.ElevationContext.fromElevationInfo(q),V="on-the-ground"===q.mode||!q.offset&&"absolute-height"!==q.mode,w=new N.ManipulatorState,F=z.signal(1);b.push(m.watch(()=>({heightPlane:f.visualElements.heightPlane,alpha:F.value}),({heightPlane:d,alpha:l})=>d.apply(r,l),m.initial));const G=z.signal(1);b.push(m.watch(()=>
({shadowStyle:f.visualElements.pointObjects.shadowStyle,alpha:G.value}),({shadowStyle:d,alpha:l})=>d.apply(h,l),m.initial));const t=()=>{w.update(a);var d=x(v.manipulatedObjectGeometry(c)),l=V&&(c.isDraped||null==d||!d.hasZ);let H=!0;if(l||null==d)H=!1;else{B.featureExpressionInfoIsZero(c.elevationInfo)&&(d=d.clone(),d.z=0);const W=Q.evaluateElevationAlignmentAtPoint(d,e.elevationProvider,U,e.renderCoordsHelper);J.set(k,d.x,d.y,W);A.projectVectorToVector(k,d.spatialReference,k,e.renderCoordsHelper.spatialReference);
p.setStartEndFromWorldDownAtLocation(k);h.intersectsWorldUpAtLocation=k}F.value=w.grabbingState&C.GrabbingState.Z?f.visualElements.laserlineAlphaMultiplier:1;d=u.empty(X);!l&&c.visible&&g.calculateMapBounds(d)&&A.projectVectorToVector(u.getMin(d,k),e.spatialReference,k,e.renderCoordsHelper.spatialReference)?(r.heightManifoldTarget=k,r.attached=!0):r.attached=!1;G.value=w.grabbingState&C.GrabbingState.XY?f.visualElements.laserlineAlphaMultiplier:1;l=H&&c.visible&&!l;h.attached=l;p.attached=l};b.push(m.watch(()=>
[c.visible,c.isDraped],t),c.on("committed",t));a.forEachManipulator(d=>{b.push(d.events.on("grab-changed",t))});b.push(n.destroyHandle(h));b.push(n.destroyHandle(p));b.push(n.destroyHandle(r));t()}function Y(a,b){const {view:g,object:e}=a,c=new P.PointVisualElement({view:g,geometry:x(v.manipulatedObjectGeometry(e)),elevationInfo:e.elevationInfo,isDecoration:!0});Z(a,c,b);b.push(n.destroyHandle(c));return c}function x(a){return null==a?null:"point"===a.type?a:"mesh"===a.type?a.anchor.clone():null}
function Z(a,b,g){const {view:e,object:c}=a,f=new D.Settings({getTheme:()=>e.effectiveTheme});aa(a,b,g);f.visualElements.pointObjects.outline.apply(b);g.push(m.watch(()=>c.visible,()=>{b.attached=c.visible},m.initial))}function aa(a,b,g){const {view:e,object:c}=a;let f=null;const p=h=>{null!=f&&(f.remove(),f=null);c.isDraped&&null!=h&&(f=ba(e,h,()=>{b.geometry=h}))};a=()=>{const h=x(v.manipulatedObjectGeometry(c));null!=h&&B.featureExpressionInfoIsZero(c.elevationInfo)&&(h.z=0);p(h);b.geometry=h};
g.push(c.on("committed",a),n.refHandle(()=>f));a()}function ba(a,b,g){L.projectPointToVector(b,k,a.elevationProvider.spatialReference);const e=k[0],c=k[1];return a.elevationProvider.on("elevation-change",f=>{M.containsXY(f.extent,e,c)&&g()})}const k=K.create(),X=u.create();y.createVisualElements=function(a){const b=[],g=Y(a,b);T(a,b,g);return{visualElement:g,remove:()=>n.removeHandles(b)}};Object.defineProperty(y,Symbol.toStringTag,{value:"Module"})});