// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/tslib.es6 ../../../../../core/Evented ../../../../../core/handleUtils ../../../../../core/has ../../../../../core/reactiveUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/Logger ../../../../../core/RandomLCG ../../../../../core/accessorSupport/decorators/subclass ../../../../../geometry/support/aaBoundingRect ../../../../../geometry/support/vectorStacks ../../../analysis/Slice/sliceToolUtils ../../Manipulator3D ../manipulatedObjectUtils ../ManipulatorType ../manipulatorUtils ../visualElementUtils ./extentTransform/ExtentMove ./extentTransform/ExtentRotate ./extentTransform/ExtentScale ./extentTransform/extentUtils ./extentTransform/PreserveAspectRatio ./extentTransform/SnapRotation ../../visualElements/OutlineVisualElement ../../../../interactive/InteractiveToolBase ../../../../interactive/sketch/SketchOptions ../../../../interactive/tooltip/Tooltip".split(" "),
function(c,e,q,r,K,k,f,L,M,t,u,v,m,w,x,l,y,z,A,B,C,D,E,F,G,H,n,I){c.ExtentTransformTool=class extends H.InteractiveToolBase{get updating(){return!!this.object.updating}constructor(a){super(a);this.events=new q;this.enableRotation=this.enableScaling=this.enableZ=!0;this.sketchOptions=new n;this._preserveAspectRatio=new E.PreserveAspectRatio;this._snapRotation=new F.SnapRotation;this.grabbing=!1;this._attachmentOrigin=this.inputState=null;this.type="transform-3d";this._outlineVisualElement=null}initialize(){const {view:a,
object:g}=this,b=this._bounds=new D.TransformBounds(this,()=>this._updateManipulators());this._extentMove=new A.ExtentMove(this,b);this._extentScale=new C.ExtentScale(this,b,()=>this._preserveAspectRatio.createDragEventPipelineStep());this._extentRotate=new B.ExtentRotate(this,b,()=>this._snapRotation.createDragEventPipelineStep());this.addHandles([k.watch(()=>this.enableZ,()=>this._updateManipulatorAvailability(this._extentMove.moveZManipulator,l.ManipulatorType.TRANSLATE_Z)),k.watch(()=>this.enableScaling,
()=>this._extentScale.forEachManipulator(d=>this._updateManipulatorAvailability(d,l.ManipulatorType.SCALE))),k.watch(()=>this.enableRotation,()=>this._updateManipulatorAvailability(this._extentRotate.rotateManipulator,l.ManipulatorType.ROTATE))]);this._updateManipulators();this._updateAllManipulatorAvailability();const h=z.createVisualElements({view:a,object:g,forEachManipulator:d=>this._forEachManipulator(d),onManipulatorsChanged:()=>r.makeHandle()});if(null!=h){const {visualElement:d}=h;d instanceof
G.OutlineVisualElement&&(this._outlineVisualElement=d,this.addHandles(d.events.on("attachment-origin-changed",()=>this._bounds.updateDisplayBounds())));this.addHandles(h)}this.addHandles([g.on("committed",()=>this._onGeometryChanged()),k.watch(()=>this.object.visible,()=>this._updateAllManipulatorAvailability()),k.watch(()=>this.object.isDraped,()=>this._graphicDrapedChanged(),k.initial),k.watch(()=>a.pointsOfInterest?.centerOnSurfaceFrequent.location,()=>b.updateDisplayBounds())]);this._forEachManipulator(d=>
{this.addHandles(d.events.on("grab-changed",()=>{this.grabbing=d.grabbing;this._updateAllManipulatorAvailability()}))});this._forEachManipulator((d,J)=>{this.addHandles(d.events.on("immediate-click",p=>{J===l.ManipulatorType.TRANSLATE_XY&&this.events.emit("immediate-click",{...p,object:g});p.stopPropagation()}))});this._initializeTooltip();this.finishToolCreation()}destroy(){this._extentMove.destroy();this._extentScale.destroy();this._extentRotate.destroy();this.tooltip.destroy();this._set("view",
null);this._set("object",null)}_initializeTooltip(){const {view:a}=this,g=this.tooltip=new I.Tooltip({view:a}),b=()=>{g.info=this._getUpdatedTooltipInfo()};this.addHandles([k.watch(()=>this.sketchOptions.tooltips.effectiveEnabled,b),this.events.on("translate-start",b),this.events.on("translate",b),this.events.on("translate-stop",()=>this.tooltip.clear()),this.events.on("rotate-start",b),this.events.on("rotate",b),this.events.on("rotate-stop",b),this.events.on("scale-start",b),this.events.on("scale",
b),this.events.on("scale-stop",b)]);this._forEachManipulator(h=>{this.addHandles([h.events.on("focus-changed",b),h.events.on("grab-changed",b),h.events.on("drag",d=>{"cancel"===d.action?this.tooltip.clear():b()})])})}_getUpdatedTooltipInfo(){return this.sketchOptions.tooltips.effectiveEnabled?this._extentMove.getUpdatedTooltipInfo()??this._extentScale.getUpdatedTooltipInfo()??this._extentRotate.getUpdatedTooltipInfo():null}_onGeometryChanged(){this._bounds.updateDisplayBounds()}_graphicDrapedChanged(){this.removeHandles("draped-elevation-changes");
this._bounds.updateDisplayBounds();this.object.isDraped&&this.addHandles(this.view.elevationProvider.on("elevation-change",a=>{null!=this._attachmentOrigin&&u.containsXY(a.extent,this._attachmentOrigin.x,this._attachmentOrigin.y)&&this._bounds.updateDisplayBounds()}),"draped-elevation-changes")}_updateManipulators(){if(this.visible){var a=this._bounds.displayBounds,g=m.calculateBoundedPlaneTranslateRotate(a,v.sm4d.get());this._extentMove.updateManipulators(g,a);this._extentScale.updateManipulators(g,
a);this._extentRotate.updateManipulators(g,a)}}_updateAllManipulatorAvailability(){this._forEachManipulator((a,g)=>this._updateManipulatorAvailability(a,g))}_updateManipulatorAvailability(a,g){const b=this.grabbing&&!a.grabbing;a.interactive=!b;if(a instanceof w.Manipulator3D){const h=this.object.visible,d=this.enableZ&&y.canMoveZOperations(this.object.operations,this.object.elevationInfo);switch(g){case l.ManipulatorType.ROTATE:a.available=h&&this.enableRotation;break;case l.ManipulatorType.SCALE:a.available=
h&&(this.enableScaling||this.enableRotation||d);a.interactive=!b&&this.enableScaling;a.state=this.enableScaling?m.resizeNormal:m.resizeOutlineOnly;break;case l.ManipulatorType.TRANSLATE_Z:a.available=h&&d;break;default:a.available=h}}}_forEachManipulator(a){this._extentMove.forEachManipulator(a);this._extentScale.forEachManipulator(a);this._extentRotate.forEachManipulator(a)}get preserveAspectRatio(){return this._preserveAspectRatio.enabled}set preserveAspectRatio(a){this._preserveAspectRatio.enabled=
a;this._set("preserveAspectRatio",a)}get snapRotation(){return this._snapRotation.enabled}set snapRotation(a){this._snapRotation.enabled=a;this._set("snapRotation",a)}get attachmentOrigin(){return this._attachmentOrigin=(this.object.isDraped?null:this._outlineVisualElement?.attachmentOrigin)??this.object.origin??x.manipulatedObjectGeometry(this.object)?.extent?.center}reset(){}cancel(){if(this.canUndo){const a=this.object.operations?.undo();a&&this._bounds.updateMapBoundsFromOperationInverse(a)}this.inputState=
null}get canUndo(){return!!this.object.operations?.canUndo}undo(){if(null!=this.inputState)this.view.activeTool=null;else if(this.canUndo){const a=this.object.operations?.undo();a&&this._bounds.updateMapBoundsFromOperationInverse(a)}}get canRedo(){return!!this.object.operations?.canRedo}redo(){if(this.canRedo){const a=this.object.operations?.redo();a&&this._bounds.updateMapBoundsFromOperation(a)}}get test(){}};e.__decorate([f.property()],c.ExtentTransformTool.prototype,"updating",null);e.__decorate([f.property({constructOnly:!0,
nonNullable:!0})],c.ExtentTransformTool.prototype,"view",void 0);e.__decorate([f.property({constructOnly:!0,nonNullable:!0})],c.ExtentTransformTool.prototype,"object",void 0);e.__decorate([f.property()],c.ExtentTransformTool.prototype,"enableZ",void 0);e.__decorate([f.property()],c.ExtentTransformTool.prototype,"enableScaling",void 0);e.__decorate([f.property()],c.ExtentTransformTool.prototype,"enableRotation",void 0);e.__decorate([f.property({constructOnly:!0,type:n})],c.ExtentTransformTool.prototype,
"sketchOptions",void 0);e.__decorate([f.property()],c.ExtentTransformTool.prototype,"preserveAspectRatio",null);e.__decorate([f.property()],c.ExtentTransformTool.prototype,"snapRotation",null);e.__decorate([f.property()],c.ExtentTransformTool.prototype,"grabbing",void 0);e.__decorate([f.property()],c.ExtentTransformTool.prototype,"inputState",void 0);e.__decorate([f.property({readOnly:!0})],c.ExtentTransformTool.prototype,"type",void 0);e.__decorate([f.property()],c.ExtentTransformTool.prototype,
"tooltip",void 0);c.ExtentTransformTool=e.__decorate([t.subclass("esri.views.3d.interactive.editingTools.transform.ExtentTransformTool")],c.ExtentTransformTool);Object.defineProperty(c,Symbol.toStringTag,{value:"Module"})});