// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../Camera ../../../geometry ../../../Graphic ../../../Viewpoint ../../../core/asyncUtils ../../../core/has ../../../core/Cyclical ../../../core/Error ../../../core/promiseUtils ../../../core/libs/gl-matrix-2/math/mat3 ../../../core/libs/gl-matrix-2/factories/mat3f64 ../../../core/libs/gl-matrix-2/factories/mat4f64 ../../../chunks/vec32 ../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../geometry/projection ../../../geometry/projection/computeTranslationToOriginAndRotation ../../../geometry/projection/projectPointToVector ../../../geometry/projection/projectVectorToPoint ../../../geometry/projection/projectVectorToVector ../../../geometry/support/aaBoundingBox ../../../geometry/support/aaBoundingRect ../../../geometry/support/frustum ../../../geometry/support/scaleUtils ../camera/intersectionUtils ./cameraUtils ./ElevationProvider ../../../geometry/Point ../../../geometry/Extent ../../../geometry/SpatialReference ../../../geometry/Geometry ../../../geometry/Multipoint".split(" "),
function(y,Q,Ba,ea,H,R,Ca,v,S,T,U,fa,ha,m,B,t,ia,I,V,ja,q,W,ka,la,z,k,X,w,ma,Y,na,oa){async function Z(a,b,c,e){var d=b.camera;if(null!=d)return pa(d,k.getViewSR(a),e);({targetGeometry:d}=b);if(null==d)throw Error("Viewpoint has no targetGeometry!");const {camera:f,mode:g}=aa(a,b.rotation,c);if("point"===d.type)return qa(a,b,d,f,g,e);b=d.extent;if(null==b)throw Error("Target geometry has no extent!");return k.fromExtentAsync(a,b,f.heading,f.tilt,g,e)}async function pa(a,b,c){b=await t.projectWithZConversion(a.position,
b,{signal:c});T.throwIfAborted(c);a=a.clone();a.position=b.clone();return a}function aa(a,b,c){a=k.internalToExternal(a,a.state.camera);let e=k.OrientationMode.ADJUST;null!=b&&(a.heading=360-v.cyclicalDegrees.normalize(b),e=k.OrientationMode.LOCKED);null!=c&&(a.tilt=c);return{camera:a,mode:e}}async function qa(a,b,c,e,d,f){const g=a.spatialReference;c=await t.projectWithZConversion(c.clone(),g,{signal:f});T.throwIfAborted(f);b=null!=b.scale?k.scaleToDistance(a,b.scale,c.latitude):a.state.camera.distance;
return k.fromCenterDistanceAsync(a,c,b,e,d,f)}function J(a,b){return null==b.scale&&null!=b.zoom?k.zoomToScale(a,b.zoom):b.scale}function C(a,b){let c=!1;null!=b.heading?(a.heading=b.heading,c=!0):null!=b.rotation&&(a.heading=360-v.cyclicalDegrees.normalize(b.rotation),c=!0);null!=b.tilt&&(a.tilt=b.tilt,c=!0);null!=b.fov&&(a.fov=b.fov);return c}function K(a,b,c,e){var d=a.spatialReference||Y.WGS84;b??=k.externalToInternal(a,c);if(null==b)return e;d=new w({spatialReference:d});if(!V.projectVectorToPoint(b.center,
a.renderSpatialReference,d))return e;e.targetGeometry=d;({latitude:d}=d);e.scale=null!=d?k.distanceToScale(a,b.distance,d):k.computeScale(a,b);e.rotation=v.cyclicalDegrees.normalize(360-c.heading);e.camera=c;return e}async function D(a,b,c,e){const d=()=>new S("viewpointutils:invalid-geometry","The target is missing a valid geometry");if(!b)throw d();"mesh"===b.type&&(b=b.extent);const f=a.basemapTerrain.spatialReference;if(!b.hasZ&&a.basemapTerrain){let h;switch(b.type){case "point":h=b;break;case "multipoint":case "polyline":h=
b.extent?.center;break;case "extent":h=b.center;break;case "polygon":h=b.centroid}null!=h&&f&&a.elevationProvider?(h=await t.projectWithZConversion(h,f,{signal:e}),l[2]=X.getElevationAtPoint(a.elevationProvider,h)??0):l[2]=0}const g=[];(0,ra[b.type])(b,b.hasZ?h=>{g.push([h[0],h[1],h[2]])}:h=>{g.push([h[0],h[1]])},l);if(0===g.length)throw d();a=a.spatialReference;e=await t.projectWithZConversion(new oa({spatialReference:b.spatialReference,hasZ:b.hasZ,hasM:!1,points:g}),a,{signal:e});b.hasZ&&(c.hasZ=
!0);if(b.hasZ)for(const [h,n,p]of e.points)l[0]=h,l[1]=n,l[2]=p,q.expandWithVec3(c.boundingBox,l);else for(const [h,n]of e.points)l[0]=h,l[1]=n,q.expandWithVec3(c.boundingBox,l)}async function sa(a,b,c,e,d){const f=await R.result(a.whenViewForGraphic(b));if(!1!==f.ok&&null!=f.value&&"whenGraphicBounds"in f.value)if(c=await R.result(f.value.whenGraphicBounds(b,{minDemResolution:c})),!1!==c.ok&&c.value){var {screenSpaceObjects:g,boundingBox:h}=c.value;q.expandWithAABB(e.boundingBox,h);g&&g.forEach(n=>
{e.screenSpaceObjects.push(n)});isFinite(h[2])&&(e.hasZ=!0)}else await D(a,b.geometry,e,d);else await D(a,b.geometry,e,d)}async function ba(a,b,c,e,d){if(Array.isArray(b)&&2===b.length){const f=b[0],g=b[1];if("number"===typeof f&&"number"===typeof g){r.x=f;r.y=g;r.z=void 0;r.spatialReference=a.spatialReference?.isGeographic?a.spatialReference:Y.WGS84;await D(a,r,e,d);return}}b&&"map"in b&&"function"===typeof b.map?await Promise.allSettled(b.map(f=>ba(a,f,c,e,d))):b instanceof na?await D(a,b,e,d):
b instanceof ea&&await sa(a,b,c,e,d)}async function ta(a,b,c,e,d){if(b.camera)return ca(a,b.camera,e,d);d.scale=b.scale;d.rotation=b.rotation;d.targetGeometry=null!=b.targetGeometry?b.targetGeometry.clone():null;d.camera=null;null!=c.heading?d.rotation=v.cyclicalDegrees.normalize(360-c.heading):null!=c.rotation&&(d.rotation=c.rotation);b=J(a,c);null!=b&&(d.scale=b);d.camera=await Z(a,d,c.tilt,e);return d}async function ca(a,b,c,e){c=await t.projectWithZConversion(b.position,a.spatialReference,{signal:c});
b=b.clone();b.position=c;return K(a,null,b,e)}async function ua(a,b,c,e,d,f,g){const h=a.renderSpatialReference;await I.projectPointToVectorAsync(b,L,h,0,{signal:g});await I.projectPointToVectorAsync(c,E,h,0,{signal:g});f.targetGeometry=new w(b);d.position=new w(c);m.subtract(F,L,E);k.directionToHeadingTilt(a,E,F,e.up,d);f.scale=k.distanceToScale(a,m.distance(E,L),f.targetGeometry.latitude);f.rotation=v.cyclicalDegrees.normalize(360-d.heading);f.camera=d;return f}async function M(a,b,c,e,d,f){f.targetGeometry=
c.clone();const g=z.cameraOnContentAlongViewDirection(a);if(b.position)return ua(a,f.targetGeometry,b.position,g,e,f,d);if(b.zoomFactor){var h=g.distance/b.zoomFactor;const n=m.scale(l,g.viewForward,-h);g.eye=m.add(l,g.center,n);f.scale=k.distanceToScale(a,h,c.latitude)}k.internalToExternal(a,g,e);h=C(e,b)?k.OrientationMode.LOCKED:k.OrientationMode.ADJUST;b.zoomFactor||(b=J(a,b),null==b?(await I.projectPointToVectorAsync(c,l,a.renderSpatialReference,0,{signal:d}),ka.intersectsPoint(g.frustum,l)?f.scale=
k.distanceToScale(a,m.distance(g.eye,l),c.latitude):f.scale=k.computeScale(a,g)):f.scale=b,f.camera=await k.fromCenterScale(a,f.targetGeometry,f.scale,e,h,d));return f}async function va(a,b,c,e,d){var f=z.cameraOnContentAlongViewDirection(a);m.copy(F,f.viewForward);k.directionToHeadingTilt(a,f.eye,F,f.up,N);f=a.spatialReference;const {position:g}=b;g?(d=await t.projectWithZConversion(g,f,{signal:d}),c.position=d):c.position=new w;c.heading=null!=b.heading?b.heading:N.heading;c.tilt=null!=b.tilt?b.tilt:
N.tilt;return K(a,null,c,e)}async function wa(a,b,c,e,d){if(null!=b.heading||null!=b.rotation||null!=b.scale||null!=b.tilt||null!=b.zoom||null!=b.zoomFactor){const f=z.cameraOnContentAlongViewDirection(a),{spatialReference:g,renderSpatialReference:h}=a,n=new w({spatialReference:g});return V.projectVectorToPoint(f.center,h,n)?M(a,b,n,c,e,d):d}d.scale=a.scale;d.camera=a.camera.clone();C(d.camera,b);return d}async function xa(a,b,c,e,d,f){f.targetGeometry=c.clone();const g=z.cameraOnContentAlongViewDirection(a);
k.internalToExternal(a,g,e);b=C(e,b)?k.OrientationMode.LOCKED:k.OrientationMode.ADJUST;f.camera=await k.fromExtentAsync(a,c,e.heading,e.tilt,b,d);return f}async function ya(a,b,c,e,d,f,g,h){h.targetGeometry=c.clone();const n=z.cameraOnContentAlongViewDirection(a);var p=0;null!=c.z?p=c.z:a.basemapTerrain&&a.elevationProvider&&(p=X.getElevationAtPoint(a.elevationProvider,c));m.set(l,c.x,c.y,p);ia.computeTranslationToOriginAndRotation(a.spatialReference,l,da,a.renderSpatialReference);U.fromMat4(G,da);
U.transpose(G,G);q.empty(A);c=[[0,1,2],[3,1,2],[0,4,2],[3,4,2],[0,1,5],[3,1,5],[0,4,5],[3,4,5]];for(var x=0;x<c.length;x++){const O=c[x];let P=e[O[2]];isFinite(P)||(P=p);m.set(l,e[O[0]],e[O[1]],P);ja.projectVectorToVector(l,a.spatialReference,l,a.renderSpatialReference);q.expandWithVec3(A,m.transformMat3(l,l,G))}e=q.width(A);p=q.height(A);c=q.depth(A);x=1/Math.tan(n.fovY/2);d=Math.max(.5*Math.sqrt(e*e+c*c)*Math.max(x,1/Math.tan(n.fovX/2))+.5*p,.5*p*x+.5*Math.max(e,c))/d;k.internalToExternal(a,n,f);
b=C(f,b)?k.OrientationMode.LOCKED:k.OrientationMode.ADJUST;h.scale=k.distanceToScale(a,d,h.targetGeometry.latitude);h.camera=await k.fromCenterScale(a,h.targetGeometry,h.scale,f,b,g);return h}function u(a){null!=a?.camera&&(a.rotation=v.cyclicalDegrees.normalize(360-a.camera.heading));return a}class za{constructor(){this.hasZ=!1;this.boundingBox=q.empty();this.screenSpaceObjects=[]}}const l=B.create(),da=ha.create(),G=fa.create(),A=q.create(),Aa=W.create(),F=B.create(),E=B.create(),L=B.create(),N=
{heading:0,tilt:0},r=new w,ra={point(a,b,c){c[0]=a.x;c[1]=a.y;null!=a.z&&(c[2]=a.z);b(c)},polygon(a,b,c){const e=a.hasZ;for(let d=0;d<a.rings.length;d++){const f=a.rings[d];for(let g=0;g<f.length;g++)c[0]=f[g][0],c[1]=f[g][1],e&&(c[2]=f[g][2]),b(c)}},polyline(a,b,c){const e=a.hasZ;for(let d=0;d<a.paths.length;d++){const f=a.paths[d];for(let g=0;g<f.length;g++)c[0]=f[g][0],c[1]=f[g][1],e&&(c[2]=f[g][2]),b(c)}},multipoint(a,b,c){const e=a.points;a=a.hasZ;for(let d=0;d<e.length;d++)c[0]=e[d][0],c[1]=
e[d][1],a&&(c[2]=e[d][2]),b(c)},extent(a,b,c){null!=a.zmin&&null!=a.zmax?(b(m.set(c,a.xmin,a.ymin,a.zmin)),b(m.set(c,a.xmax,a.ymin,a.zmin)),b(m.set(c,a.xmin,a.ymax,a.zmin)),b(m.set(c,a.xmax,a.ymax,a.zmin)),b(m.set(c,a.xmin,a.ymin,a.zmax)),b(m.set(c,a.xmax,a.ymin,a.zmax)),b(m.set(c,a.xmin,a.ymax,a.zmax)),b(m.set(c,a.xmax,a.ymax,a.zmax))):(b(m.set(c,a.xmin,a.ymin,c[2])),b(m.set(c,a.xmax,a.ymin,c[2])),b(m.set(c,a.xmin,a.ymax,c[2])),b(m.set(c,a.xmax,a.ymax,c[2])))}};y.create=async function(a,b,c){if(b&&
a.spatialReference){var e={target:void 0};"declaredClass"in b||Array.isArray(b)?e.target=b:(Object.assign(e,b),!e.target&&"center"in b&&b.center&&(e.target=b.center));b=e}else b=null;if(!b)throw new S("viewpointutils-create:no-target","Missing target for creating viewpoint");e=new Q({fov:a.camera.fov});const d=new H({camera:e});if(b.target instanceof H)return a=await ta(a,b.target,b,c,d),u(a);if(b.target instanceof Q)return u(await ca(a,b.target,c,d));var f=null!=b.scale||null!=b.zoom;if(b.target instanceof
ma){var g=b.target.xmin===b.target.xmax||b.target.ymin===b.target.ymax;return f||g?u(await M(a,b,b.target.center,e,c,d)):u(await xa(a,b,b.target,e,c,d))}g=new za;var h=f?(h=J(a,b))?la.getResolutionInMetersForScale(h):void 0:void 0;await ba(a,b.target,h,g,c);if(isFinite(g.boundingBox[0])){q.center(g.boundingBox,l);r.x=l[0];r.y=l[1];r.z=l[2];r.spatialReference=a.spatialReference;isFinite(r.z)&&g.hasZ?h=q.isPoint(g.boundingBox):(r.z=void 0,h=W.isPoint(q.toRect(g.boundingBox,Aa)));if(f||h)return u(await M(a,
b,r,e,c,d));f=g.screenSpaceObjects;if(f.length){h=Number.NEGATIVE_INFINITY;for(let n=0;n<f.length;n++){const p=f[n].screenSpaceBoundingRect;h=Math.max(h,Math.abs(p[0]),Math.abs(p[1]),Math.abs(p[2]),Math.abs(p[3]))}f=.66-h/Math.min(a.width,a.height)*2}else f=.66;return u(await ya(a,b,r,g.boundingBox,f,e,c,d))}return b.position?u(await va(a,b,e,d,c)):u(await wa(a,b,e,c,d))};y.fromCamera=function(a,b,c=null){null==c&&(c=new H);return K(a,null,b.clone(),c)};y.toCameraAsync=Z;y.toCameraSync=function(a,
b,c){var e=b.camera;if(null!=e){a:{a=k.getViewSR(a);var d=e.position;try{var f=t.tryProjectWithZConversion(d,a)}catch(n){a=null;break a}f?(a=e.clone(),a.position=f.clone()):a=null}return a}({targetGeometry:f}=b);if(null==f)return null;const {camera:g,mode:h}=aa(a,b.rotation,c);if("point"===f.type){a:{e=a.spatialReference;try{d=t.tryProjectWithZConversion(f.clone(),e)}catch(n){a=null;break a}d?(f=null!=b.scale?k.scaleToDistance(a,b.scale,d.latitude):a.state.camera.distance,a=k.fromCenterDistanceSync(a,
d,f,g,h)):a=null}return a}f=f.extent;return null==f?null:k.fromExtentSync(a,f,g.heading,g.tilt,h)};Object.defineProperty(y,Symbol.toStringTag,{value:"Module"})});