// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/mathUtils ../../../../core/libs/gl-matrix-2/math/mat3 ../../../../core/libs/gl-matrix-2/factories/mat3f64 ../../../../chunks/vec32 ../../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../ViewingMode ../../support/mathUtils".split(" "),function(v,q,z,w,c,h,u,r){class A{get pitch(){return this._pitch}get yaw(){return this._yaw}get distance(){return this._distance}get fov(){return this._fov}get size(){return this._size}constructor(a){this.viewingMode=a;this.center=
h.create();this._distance=this._yaw=this._pitch=0;this.direction=h.clone(x);this._fov=55;this._size=1}pixelsPerPanAtZoom(a){return this._size/2/(this._zoomToPanScale*a)}zoomAtPixelsPerPan(a){return this._size/2/(this._zoomToPanScale*a)}pixelsPerRotateAtZoom(){return this._size/2/Math.max(Math.cos(Math.abs(this._pitch)),.5)}compareTo(a,b){if(this.viewingMode===u.ViewingMode.Global){var d=c.length(this.center);const k=c.length(a.center);d=(d+k)/2;b.pan=r.angle(this.center,a.center)*d}else b.pan=c.distance(this.center,
a.center);d=Math.abs(a._yaw-this._yaw);d>=Math.PI&&(d=2*Math.PI-d);b.rotate=Math.max(d,Math.abs(a._pitch-this._pitch));b.fov=a.fov-this.fov;b.sourceZoom=this._distance;b.targetZoom=a._distance}interpolate(a,b,d){this.viewingMode===u.ViewingMode.Global?r.slerp(a.center,b.center,d.pan,this.center):c.lerp(this.center,a.center,b.center,d.pan);this._distance=isFinite(b.distance)?q.lerp(a.distance,b.distance+d.zoomOffset,d.zoom):a.distance;this._pitch=q.lerp(a.pitch,b.pitch,d.rotate);let k=a._yaw;const p=
b._yaw;Math.abs(p-k)>=Math.PI&&(k+=2*(k<p?1:-1)*Math.PI);this._yaw=q.lerp(k,p,d.rotate);this._fov=q.lerp(a.fov,b.fov,d.fov)}copyFrom(a){c.copy(this.center,a.center);this._pitch=a.pitch;this._yaw=a.yaw;this._distance=a.distance;c.copy(this.direction,a.direction);this._size=a.size;this._fov=a.fov;this._zoomToPanScale=Math.atan(.5*this._fov);this.viewingMode=a.viewingMode}copyFromRenderCamera(a){var b=this._lookAtOrientation(a.center,y);c.copy(this.center,a.center);c.subtract(e,a.center,a.eye);c.transformMat3(e,
e,b);c.transformMat3(l,a.up,b);this._distance=c.length(e);0!==this._distance&&(e[0]/=this._distance,e[1]/=this._distance,e[2]/=this._distance);this._pitch=this._eyeUpToPitch(e);b=e;const d=B;.5>Math.abs(l[2])?(c.copy(d,l),0<b[2]&&c.scale(d,d,-1)):c.copy(d,b);c.cross(f,d,n);c.normalize(f,f);this._yaw=r.angle(t,f,n);this._size=Math.sqrt(a.width*a.width+a.height*a.height);this._fov=a.fov;this._zoomToPanScale=Math.atan(.5*this._fov)}copyToRenderCamera(a){const b=this._lookAtOrientation(this.center,y);
z.transpose(b,b);this._axisAngleVec3(t,this._pitch-Math.PI/2,x,e);this._axisAngleVec3(n,this._yaw,e,e);this._axisAngleVec3(t,this._pitch-Math.PI/2,n,l);this._axisAngleVec3(n,this._yaw,l,l);c.scale(e,e,this._distance);c.transformMat3(e,e,b);c.transformMat3(l,l,b);a.center=this.center;a.eye=c.subtract(e,this.center,e);a.up=l;a.fov=this._fov}_axisAngleVec3(a,b,d,k){const p=Math.cos(b);b=Math.sin(b);c.scale(g,d,p);c.cross(f,a,d);c.scale(f,f,b);c.scale(m,a,(1-p)*c.dot(a,d));return c.add(k,c.add(k,g,f),
m)}_lookAtOrientation(a,b=w.create()){this._upAtLookAt(a,m);c.cross(g,this.direction,m);c.normalize(g,g);0===g[0]&&0===g[1]&&0===g[2]&&c.copy(g,t);c.cross(f,m,g);c.normalize(f,f);b[0]=g[0];b[1]=f[0];b[2]=m[0];b[3]=g[1];b[4]=f[1];b[5]=m[1];b[6]=g[2];b[7]=f[2];b[8]=m[2];return b}_upAtLookAt(a,b){return this.viewingMode===u.ViewingMode.Local?c.copy(b,n):c.normalize(b,a)}_eyeUpToPitch(a){return Math.PI-r.angle(n,a)}}const g=h.create(),f=h.create(),m=h.create(),e=h.create(),l=h.create(),B=h.create(),n=
h.UNIT_Z,x=h.UNIT_Y,t=h.UNIT_X,y=w.create();v.Camera=A;Object.defineProperty(v,Symbol.toStringTag,{value:"Module"})});