// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../../../../core/screenUtils ../../../../../../../core/libs/gl-matrix-2/math/mat2d ../../../../../../../core/libs/gl-matrix-2/factories/mat2df32 ../../../../../../../core/libs/gl-matrix-2/math/vec2 ../../../../../../../geometry/GeometryCursor ../../../../../../../symbols/cim/constants ../../../../../../../symbols/cim/enums ../../../../../../../symbols/cim/placements/CIMMarkerPlacementHelper ../../../definitions ../fill/meshWriterUtils ./ComputedMarkerParams ./markerConstants ../mesh/loadGeometryEngine ../mesh/MeshWriter ../../../../../../webgl/enums".split(" "),
function(u,x,v,y,r,z,t,A,B,C,k,D,q,E,F,l){function G(a,b,c,e,f=!1){a=y.create();f=f?1:-1;v.identity(a);(b||c)&&v.translate(a,a,[b,-c]);e&&v.rotate(a,a,f*H*-e);return a}const H=3.14159265359/180,I=128/Math.PI,w={createComputedParams:a=>D.ComputedMarkerParams.from(a),optionalAttributes:{zoomRange:{type:l.DataType.SHORT,count:2,packPrecisionFactor:C.minMaxZoomPrecisionFactor,pack:({scaleInfo:a},{tileInfo:b})=>k.getMinMaxZoom(a,b)}},attributes:{pos:{type:l.DataType.SHORT,count:2,pack:"position",packPrecisionFactor:10},
id:{type:l.DataType.UNSIGNED_BYTE,count:3,pack:"id"},bitset:{type:l.DataType.UNSIGNED_BYTE,count:1,pack:({sprite:a,alignment:b,scaleSymbolsProportionally:c,overrideOutlineColor:e,colorLocked:f})=>{let d=0;a.sdf&&(d|=k.getBitMask(q.MarkerConstants.bitset.isSDF));b===A.Alignment.MAP&&(d|=k.getBitMask(q.MarkerConstants.bitset.isMapAligned));c&&(d|=k.getBitMask(q.MarkerConstants.bitset.scaleSymbolsProportionally));e&&(d|=k.getBitMask(q.MarkerConstants.bitset.overrideOutlineColor));f&&(d|=k.getBitMask(q.MarkerConstants.bitset.colorLocked));
return d}},offset:{type:l.DataType.SHORT,count:2,packPrecisionFactor:4,packAlternating:{count:4,pack:({angle:a,computedWidth:b,computedHeight:c,anchorX:e,anchorY:f,offsetX:d,offsetY:g,rotateClockwise:h})=>{a=G(0,d,g,-a,h);e=-(.5+e)*b;h=-(.5-f)*c;f=[e,h];d=[e+b,h];g=[e,h+c];b=[e+b,h+c];r.transformMat2d(f,f,a);r.transformMat2d(d,d,a);r.transformMat2d(g,g,a);r.transformMat2d(b,b,a);return[f,d,g,b]}}},textureUV:{type:l.DataType.SHORT,count:2,packPrecisionFactor:4,packAlternating:{count:4,pack:({texXmax:a,
texXmin:b,texYmax:c,texYmin:e})=>[[b,e],[a,e],[b,c],[a,c]]}},color:{type:l.DataType.UNSIGNED_BYTE,count:4,normalized:!0,pack:({color:a})=>k.processColorInput(a)},outlineColor:{type:l.DataType.UNSIGNED_BYTE,count:4,normalized:!0,pack:({outlineColor:a})=>k.processColorInput(a)},sizing:{type:l.DataType.UNSIGNED_BYTE,count:4,pack:({rawWidth:a,rawHeight:b,outlineSize:c,referenceSize:e})=>[k.packByteSqrt(Math.max(a,b),128),k.packByteSqrt(c,128),k.packByteSqrt(e,128),0]},placementAngle:{type:l.DataType.UNSIGNED_BYTE,
count:1,packTessellation:({placementAngle:a})=>{a*=I;a%=256;return Math.abs(0<=a?a:a+256)}},sizeRatio:{type:l.DataType.UNSIGNED_SHORT,count:1,packPrecisionFactor:64,pack:({sizeRatio:a})=>a}}};class J extends F.MeshWriter{constructor(){super(...arguments);this.vertexSpec=w}getBoundsInfo(){return this.evaluatedMeshParams.boundsInfo}_write(a,b,c){var e=this.evaluatedMeshParams.sprite?.textureBinding;const f=b.getDisplayId();a.recordStart(this.instanceId,this.attributeLayout,e);e=this.evaluatedMeshParams.minPixelBuffer;
const d=Math.max(this.evaluatedMeshParams.computedWidth,e),g=Math.max(this.evaluatedMeshParams.computedHeight,e),h=this.evaluatedMeshParams.offsetX,n=-this.evaluatedMeshParams.offsetY;if(null!=this.evaluatedMeshParams.placement)this._writePlacedMarkers(a,b,c,d,g);else if(c?.nextPath())c.nextPoint(),b=c.x,c=c.y,a.recordBounds(b+h,c+n,d,g),this._writeQuad(a,f,b,c);else if("esriGeometryPolygon"===b.geometryType){b=b.readCentroidForDisplay();if(!b)return;const [m,p]=b.coords;a.recordBounds(m+h,p+n,d,
g);this._writeQuad(a,f,m,p)}else"esriGeometryPoint"===b.geometryType?(c=b.readXForDisplay(),b=b.readYForDisplay(),a.recordBounds(c+h,b+n,d,g),this._writeQuad(a,f,c,b)):b.readGeometryForDisplay()?.forEachVertex((m,p)=>{a.recordBounds(m+h,p+n,d,g);Math.abs(m)>t.maxTileCoordValue||Math.abs(p)>t.maxTileCoordValue||this._writeQuad(a,f,m,p)});a.recordEnd()}_writePlacedMarkers(a,b,c,e,f){if(c=c??z.GeometryCursor.fromFeatureSetReaderCIM(b)?.clone())if(c=B.CIMMarkerPlacementHelper.getPlacement(c,-1,this.evaluatedMeshParams.placement,
x.pt2px(1),a.id,E.getGeometryEngine())){b=b.getDisplayId();for(var d=c.next(),g=this.evaluatedMeshParams.offsetX,h=-this.evaluatedMeshParams.offsetY;null!=d;){const n=d.tx,m=-d.ty;Math.abs(n)>t.maxTileCoordValue||Math.abs(m)>t.maxTileCoordValue?d=c.next():(d=-d.getAngle(),a.recordBounds(n+g,m+h,e,f),this._writeQuad(a,b,n,m,d),d=c.next())}}}_writeQuad(a,b,c,e,f){const d=a.vertexCount();this._writeVertex(a,b,c,e,null==f?null:{placementAngle:f});a.indexWrite(d+0);a.indexWrite(d+1);a.indexWrite(d+2);
a.indexWrite(d+1);a.indexWrite(d+3);a.indexWrite(d+2)}}u.MarkerMeshWriter=J;u.MarkerVertexSpec=w;Object.defineProperty(u,Symbol.toStringTag,{value:"Module"})});