// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/Evented ../../../../core/has ../../../../core/Logger ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/scheduling ../../../../core/time ../../../../core/accessorSupport/decorators/property ../../../../core/RandomLCG ../../../../core/accessorSupport/decorators/subclass ../collections/Component/ComponentObjectCollection ../core/shaderTechnique/ShaderTechniqueRepository ../effects/highlight/Highlight ../effects/highlight/ShadowHighlight ../effects/magnifier/MagnifierRenderNode ../effects/smaa/SMAA ../effects/ssao/SSAO ../lib/basicInterfaces ../lib/CompositingHelper ../lib/depthRangeUtils ../lib/GLMaterialRepository ../lib/Material ../lib/ObjectAndLayerIdRenderHelper ../lib/Renderer ../lib/RenderingContext ../lib/TextureRepository ../materials/markerTextureRepository ../materials/stippleTextureRepository ../materials/internal/WaterTextureRepository ./contextCache ./requireUtils ./ScreenshotManager ./testUtils ../../../support/RenderState ../../../webgl/contextUtils".split(" "),
function(f,h,z,A,t,u,m,p,B,v,k,aa,C,D,E,F,G,H,I,J,n,K,L,M,N,O,P,w,Q,R,S,T,U,V,x,W,X,Y){function Z(a,d){const b={disabledExtensions:d.options.deactivatedWebGLExtensions||{},debugWebGLExtensions:d.options.debugWebGLExtensions||{},maxAnisotropy:8},e=(c,g)=>d.view.resourceController.memoryController.newCache(c,g);if(W.contextCache.enabled){let c=y.get(a);if(c)return c.configure(b),c.newCache=e,c.ref(),c;c=new w.RenderingContext(a,b,e);y.set(a,c);c.ref();return c}return new w.RenderingContext(a,b,e)}f.RenderView=
class extends z{constructor(a){super({});this.events=new A;this.waterTextures=new T.WaterTextureRepository;this.objectAndLayerIdRenderHelper=t("enable-feature:objectAndLayerId-rendering")?new O.ObjectAndLayerIdRenderHelper:null;this._idleSuspend=this._needsRender=this._needsUpdate=!0;this._needsWaterReflectionUpdate=!1;this._lastAnimationUpdate=0;this._container=a.container;this._viewingMode=a.viewingMode;try{this._initializeContext(a)}catch(b){console.error("Failed to initialize context",b);return}const {memoryController:d}=
a.view.resourceController;this.stippleTextures=S.createStippleTextureRepository(this._rctx,d);this.markerTextures=R.createMarkerTextureRepository(this._rctx,d);this._techniques=new E.ShaderTechniqueRepository({rctx:this._rctx,viewingMode:a.viewingMode,stippleTextures:this.stippleTextures,waterTextures:this.waterTextures,markerTextures:this.markerTextures});this._textures=new Q.TextureRepository(a,this._techniques,this._rctx);this.addHandles(this._textures.events.on("changed",b=>this.requestRender(b)));
this._materials=new M.GLMaterialRepository(this._textures,this._techniques,()=>this.requestRender(),()=>this.requestRender());this._compositingHelper=new K(this._rctx,this._techniques);this.renderer=new P.Renderer(a,this._materials,this._techniques,this._rctx,this._compositingHelper,b=>this.requestRender(b));this.addHandles([p.watch(()=>a.view.ready,b=>{b&&this._createRenderNodes(a.view,a.viewingMode)},p.initial),p.watch(()=>this.waterTextures?.updating,()=>this.requestRender(),p.initial),p.watch(()=>
a.view.qualityProfile,b=>this.renderer?.updateRenderFeatures(b),p.syncAndInitial)]);this._screenshotManager=new x.ScreenshotManager(this._rctx,{renderScene:(b,e,c,g)=>this.renderer.render(b,e,c,g),requestRenderScene:b=>this.requestRender(b),prepareOverlay:()=>a.options.screenshot.prepareOverlay(),renderOverlay:(b,e,c)=>a.options.screenshot.renderOverlay(b,e,c)},b=>this.events.emit("force-camera-for-screenshot",b));this._registerFrameTask(a)}normalizeCtorArgs(){return{}}destroy(){this._container.contains(this._canvas)&&
this._container.removeChild(this._canvas);this._frameTask=m.removeMaybe(this._frameTask);this._techniques=m.destroyMaybe(this._techniques);this._componentObjects=m.destroyMaybe(this._componentObjects);this._screenshotManager=m.destroyMaybe(this._screenshotManager);m.destroyMaybe(this.renderer);this._textures=m.destroyMaybe(this._textures);m.destroyMaybe(this.waterTextures);m.destroyMaybe(this.markerTextures);m.destroyMaybe(this.stippleTextures);this._container=this._canvas=null;this._rctx=m.destroyMaybe(this._rctx)}_createRenderNodes(a,
d){new J.SSAO({view:a,isEnabled:()=>this.renderer.hasSSAO,techniques:this._techniques});new I.SMAA({view:a,isEnabled:()=>this.renderer.hasSMAA,techniques:this._techniques});new H.MagnifierRenderNode({view:a,techniques:this._techniques});new F.Highlight({view:a,techniques:this._techniques});new G.ShadowHighlight({view:a,viewingMode:d,techniques:this._techniques})}requestRender(a=n.RenderRequestType.UPDATE){this._needsRender=!0;a===n.RenderRequestType.UPDATE&&(this._needsUpdate=!0)}get updating(){return this._needsUpdate||
this._needsWaterReflectionUpdate||this.renderer.updating||this._textures.updating||this.waterTextures.updating}get textures(){return this._textures}get compositingHelper(){return this._compositingHelper}setIdleSuspend(a){this._idleSuspend!==a&&(this._idleSuspend=a,this.requestRender())}get renderingContext(){return this._rctx}get capabilities(){return this._rctx.capabilities}get canvas(){return this._canvas}takeScreenshot(a){return this._screenshotManager.takeScreenshot(a).then(d=>d[0])}takeScreenshotWithOID(a){a.objectAndLayerIdColor=
!0;return this._screenshotManager.takeScreenshot(a)}getAlpha(){return!!this._rctx.contextAttributes.alpha}getMinimalDepthForArea(a,d,b,e,c,g=c){g=e.constrainWindowSize(d,b,c*e.pixelRatio,g*e.pixelRatio);const l=this._ensureDepthBuffer(g);this.renderer.readDepthPixels(g,l);c=Number.MAX_VALUE;for(let r=0;r<g[2]*g[3];r++){const q=L.textureToDepth(4*r,l,e.nearFar);c>q&&q!==e.nearFar[0]&&q!==e.nearFar[1]&&(c=q)}a&&(a=a.pickDepth(d*e.pixelRatio,b*e.pixelRatio,e),null!=a&&c>a&&a!==e.nearFar[0]&&a!==e.nearFar[1]&&
(c=a));return c===Number.MAX_VALUE?void 0:c}_ensureDepthBuffer(a){a=4*a[2]*a[3];if(null==this._tmpDepthBuffer||this._tmpDepthBuffer.byteLength<a)this._tmpDepthBuffer=new Uint8Array(a);return this._tmpDepthBuffer}async reloadShaders(){V.removeLoadedShaderModules();await this._techniques.reloadAll();this.requestRender()}_registerFrameTask(a){const d=a.view.state;let b=!1,e=n.RenderRequestType.BACKGROUND,c=!1;this._frameTask=B.addFrameTask({preRender:({time:g})=>{b=this.updating;e=this._needsUpdate?
n.RenderRequestType.UPDATE:n.RenderRequestType.BACKGROUND;a.commitSyncLayers();var l=v.Milliseconds(g-this._lastAnimationUpdate);if(l>this.renderer.animationTimestep||null!=d.forcedAnimationTime||b||this._needsRender)l=v.Milliseconds(l/this.renderer.animationTimeDilation),l=new N.UpdateParameters(d.camera,l,d.forcedAnimationTime),this.renderer.updateAnimation(l)&&this.requestRender(n.RenderRequestType.BACKGROUND),this._lastAnimationUpdate=g},render:({time:g})=>{if((this._needsRender||!this._idleSuspend||
!this.renderer.isCameraFinal||this._needsWaterReflectionUpdate)&&0<d.camera.fullWidth&&0<d.camera.fullHeight){const l=this._needsUpdate&&this._idleSuspend&&this.renderer.isCameraFinal;this._needsWaterReflectionUpdate=this._needsUpdate=this._needsRender=!1;this.renderer.render(d,g);c=!0;l&&this.renderer.hasReflections&&(this.requestRender(n.RenderRequestType.BACKGROUND),this._needsWaterReflectionUpdate=!0)}},update:({time:g})=>{const l=new x.ScreenshotContext(d,this.renderer.hasSlicePlane||this.renderer.hasDecorations||
this.renderer.hasHighlights,this.renderer.fboCache);this._textures.update();this._screenshotManager.update(l,g)},finish:()=>{c&&(this.renderer.finish(d.mode===X.RenderState.IDLE?e:n.RenderRequestType.UPDATE),c=!1)}})}_initializeContext(a){const d=a.options;this._canvas=d.canvas;this._canvas||(this._canvas=document.createElement("canvas"));this._canvas.setAttribute("style","width: 100%; height:100%; display:block;");const b=Y.createContext(this._canvas,{alpha:d.alpha||!1,premultipliedAlpha:!0,antialias:!1,
depth:!0,stencil:d.stencil??!0,powerPreference:"high-performance",preserveDrawingBuffer:d.preserveDrawingBuffer??!1});null==b?u.getLogger(this).error("A WebGL2 context could not be created."):(this._rctx=Z(b,a),this._loadShaderOnlyExtensions(),!d.alpha&&this._rctx.contextAttributes.alpha&&u.getLogger(this).error("WebGL context has alpha channel even though no alpha channel was requested"),!this._rctx.contextAttributes.alpha&&11<=t("safari")&&(this._container.style.backgroundColor="black"),this._container.appendChild(this._canvas))}_loadShaderOnlyExtensions(){this._rctx.capabilities.enable("textureFloatLinear")}getObjectAndLayerIdColor(a){return null!=
this.objectAndLayerIdRenderHelper?this.objectAndLayerIdRenderHelper.getObjectAndLayerIdColor(a):null}get componentObjectCollection(){null==this._componentObjects&&(this._componentObjects=new D.ComponentObjectCollection(this.renderer.renderPassManager,this._viewingMode));return this._componentObjects}set componentObjectCollection(a){this._componentObjects=a}};h.__decorate([k.property({type:Boolean,readOnly:!0})],f.RenderView.prototype,"updating",null);h.__decorate([k.property()],f.RenderView.prototype,
"_rctx",void 0);h.__decorate([k.property()],f.RenderView.prototype,"_container",void 0);h.__decorate([k.property()],f.RenderView.prototype,"_canvas",void 0);h.__decorate([k.property()],f.RenderView.prototype,"stippleTextures",void 0);h.__decorate([k.property()],f.RenderView.prototype,"markerTextures",void 0);h.__decorate([k.property()],f.RenderView.prototype,"waterTextures",void 0);h.__decorate([k.property({readOnly:!0})],f.RenderView.prototype,"objectAndLayerIdRenderHelper",void 0);h.__decorate([k.property()],
f.RenderView.prototype,"_textures",void 0);h.__decorate([k.property({readOnly:!0})],f.RenderView.prototype,"renderer",void 0);h.__decorate([k.property()],f.RenderView.prototype,"_screenshotManager",void 0);h.__decorate([k.property()],f.RenderView.prototype,"componentObjectCollection",null);h.__decorate([k.property()],f.RenderView.prototype,"_componentObjects",void 0);h.__decorate([k.property()],f.RenderView.prototype,"_needsUpdate",void 0);h.__decorate([k.property()],f.RenderView.prototype,"_needsWaterReflectionUpdate",
void 0);f.RenderView=h.__decorate([C.subclass("esri.views.3d.webgl-engine.parts.RenderView")],f.RenderView);const y=U.getContextCache();Object.defineProperty(f,Symbol.toStringTag,{value:"Module"})});