// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/libs/gl-matrix-2/math/vec2 ../../../../core/libs/gl-matrix-2/factories/vec2f64 ../../../../chunks/vec32 ../../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../../core/libs/gl-matrix-2/factories/vec4f64 ../../../../geometry/support/FloatArray ../../../../geometry/support/Indices ./Attribute ./Normals ./RayIntersections ./VertexAttribute".split(" "),function(z,f,D,x,A,K,F,L,l,M,N,m){class E{constructor(a){this.builder=a}onPathChanged(a){this.builder.onPathChanged()}}
class G extends E{constructor(a){super(a);this.vertexAttributeColor=K.fromValues(255,255,255,255);this.size=[];this.vertexAttributePosition=F.newFloatArray(3*this.builder.numVerticesTotal);this.vertexAttributeNormal=new Int16Array(2*this.builder.numVerticesTotal)}bakeVertexColors(a){this.vertexAttributeColor[0]=255*a[0];this.vertexAttributeColor[1]=255*a[1];this.vertexAttributeColor[2]=255*a[2];this.vertexAttributeColor[3]=255*(3<a.length?a[3]:1)}bake(a){this.size=a;const {numVerticesTotal:h,pathVertexData:k,
path:p,positions:n,profileRightAxes:g,profileUpAxes:r,profileVertexAndNormals:v}=this.builder;for(let w=0;w<h;++w){var c=k[w],b=0===c||c===p.vertices.length-1;c*=3;const q=O;let B=0,C=0;const d=4*w,t=x.set(P,g[d],g[d+1],g[d+2]),u=x.set(Q,r[d],r[d+1],r[d+2]);var e=f.set(H,v[d]*a[0],v[d+1]*a[1]);if(b)x.cross(q,u,t),B=g[d+3]*a[0],C=r[d+3];else{b=R;const y=S;f.set(b,g[d+3],r[d+3]);const I=f.length(b);f.normalize(b,b);const J=f.dot(e,b);if(Math.abs(J)>I){f.set(y,-b[1],b[0]);const T=f.dot(e,y);f.scale(b,
b,I*Math.sign(J));f.scale(y,y,T);f.add(e,b,y)}x.set(q,0,0,0)}e=x.set(U,t[0]*e[0]+u[0]*e[1],t[1]*e[0]+u[1]*e[1],t[2]*e[0]+u[2]*e[1]);b=3*w;this.vertexAttributePosition[b]=n[c]+e[0]+q[0]*B;this.vertexAttributePosition[b+1]=n[c+1]+e[1]+q[1]*B;this.vertexAttributePosition[b+2]=n[c+2]+e[2]+q[2]*B;c=f.set(H,v[d+2],v[d+3]);M.compressNormal(this.vertexAttributeNormal,w,t[0]*c[0]+u[0]*c[1]+q[0]*C,t[1]*c[0]+u[1]*c[1]+q[1]*C,t[2]*c[0]+u[2]*c[1]+q[2]*C)}}createGeometryData(){const a=this.builder.vertexIndices.length,
{normalIndices:h,vertexIndices:k}=this.builder;return[[m.VertexAttribute.POSITION,new l.Attribute(this.vertexAttributePosition,k,3,!0)],[m.VertexAttribute.NORMALCOMPRESSED,new l.Attribute(this.vertexAttributeNormal,h,2,!0)],[m.VertexAttribute.COLOR,new l.Attribute(this.vertexAttributeColor,L.getZeroIndexArray(a),4)]]}onPathChanged(a){super.onPathChanged(a);this.bake(this.size)}intersect(a,h,k,p){const n=this.builder.vertexIndices,g=new l.Vertices(this.vertexAttributePosition,3);N.intersectTriangles(a,
h,0,n.length/3,n,g,void 0,k,(r,v,c)=>{p(r,c,v,!1)})}}class V extends E{constructor(a,h,k,p){super(a);this.sizeAttributeValue=h;this.colorAttributeValue=k;this.opacityAttributeValue=p;this.vvData=null;this.baked=new G(a);this.vvData=F.newFloatArray(4*this.builder.path.vertices.length);for(a=0;a<this.builder.path.vertices.length;++a)this.vvData[4*a]=h,this.vvData[4*a+1]=k,this.vvData[4*a+2]=p,this.vvData[4*a+3]=0===a||a===this.builder.path.vertices.length-1?1:0}createGeometryData(){const {positions:a,
profileRightAxes:h,profileUpAxes:k,profileVertexAndNormals:p,pathVertexIndices:n,vertexIndices:g}=this.builder;return[[m.VertexAttribute.POSITION,new l.Attribute(a,n,3,!0)],[m.VertexAttribute.PROFILERIGHT,new l.Attribute(h,g,4,!0)],[m.VertexAttribute.PROFILEUP,new l.Attribute(k,g,4,!0)],[m.VertexAttribute.PROFILEVERTEXANDNORMAL,new l.Attribute(p,g,4,!0)],[m.VertexAttribute.FEATUREVALUE,new l.Attribute(this.vvData,n,4,!0)]]}onPathChanged(a){super.onPathChanged(a);if(a=a.getMutableAttribute(m.VertexAttribute.POSITION))a.data=
this.builder.positions}}const H=D.create(),R=D.create(),S=D.create(),U=A.create(),O=A.create(),P=A.create(),Q=A.create();z.FastUpdatePathGeometry=V;z.PathGeometryData=E;z.StaticPathGeometry=G;Object.defineProperty(z,Symbol.toStringTag,{value:"Module"})});