// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/Logger ../../../core/promiseUtils ../../../layers/FeatureLayer ./featureUtils ../../support/globalCss".split(" "),function(x,n,r,y,z,k,A){function B(a){return`<ul class="esri-widget__list">${a.map(b=>`<li>${"string"===typeof b?k.applyTextFormattingHTML(k.htmlEntities(b)):b}</li>`).join("")}</ul>`}function C(a){const b=a.keys().map(c=>{var e=a.field(c);e="string"===typeof e?k.applyTextFormattingHTML(k.htmlEntities(e)):e;return`<tr><th>${c}</th><td>${e}</td></tr>`}).join("");
return`<table class="${A.globalCss.table}">${b}</table>`}function t(){return new Promise((a,b)=>x(["../../../arcade"],a,b))}async function D({graphic:a,view:b,options:c}){const {isAggregate:e,layer:g}=a;if(!e||!g||"2d"!==b?.type)return[];b=await b.whenLayerView(g);if(!("createQuery"in b&&"queryFeatures"in b))return[];const f=b.createQuery();a=a.getObjectId();f.aggregateIds=null!=a?[a]:[];({features:c}=await b.queryFeatures(f,c));return c}function E({layer:a,aggregatedFeatures:b,interceptor:c}){const {fields:e,
objectIdField:g,geometryType:f,spatialReference:m,displayField:l}=a;return new z({fields:e,objectIdField:g,geometryType:f,spatialReference:m,displayField:l,interceptor:c,...("feature"===a.type?{templates:a.templates,typeIdField:a.typeIdField,types:a.types}:null),source:b})}async function u({expressionInfo:a,arcade:b,interceptor:c,spatialReference:e,map:g,graphic:f,location:m,view:l,options:p}){if(!a?.expression)return null;var {isAggregate:h}=f;const d=(f.sourceLayer||f.layer)??void 0;h=h?"feature-reduction-popup":
"popup";const F=b.createArcadeProfile(h);b=b.createArcadeExecutor(a.expression,F).catch(q=>r.getLogger("esri.widgets.Feature.support.arcadeFeatureUtils").error("arcade-executor-error",{error:q,expressionInfo:a}));const [G,v]=await Promise.all([D({graphic:f,view:l,options:p}),b]);if(!v)return null;const w="feature-reduction-popup"===h?E({layer:d,aggregatedFeatures:G,interceptor:c}):void 0;return await v.executeAsync({...("feature-reduction-popup"===h?{$aggregatedFeatures:w}:{$datastore:d?.url,$layer:"feature"===
d?.type||"subtype-sublayer"===d?.type||"catalog-footprint"===d?.type||"oriented-imagery"===d?.type?d:"scene"===d?.type&&null!=d.associatedLayer?d.associatedLayer:void 0,$map:g,$userInput:m,$graph:"knowledge-graph-sublayer"===d?.type?d?.parentCompositeLayer?.knowledgeGraph:void 0}),$feature:f},{abortSignal:p?.signal??void 0,interceptor:c??void 0,rawOutput:!0,spatialReference:e??void 0,timeZone:l?.timeZone}).catch(q=>r.getLogger("esri.widgets.Feature.support.arcadeFeatureUtils").error("arcade-execution-error",
{error:q,graphic:f,expressionInfo:a})).finally(()=>w?.destroy())}n.createCompiledExpression=u;n.createCompiledExpressions=async function({expressionInfos:a,spatialReference:b,graphic:c,interceptor:e,map:g,view:f,location:m,options:l}){if(!a?.length)return{};const p=await t(),h={};for(const d of a)h[`expression/${d.name}`]=u({expressionInfo:d,arcade:p,interceptor:e,spatialReference:b,map:g,graphic:c,location:m,view:f,options:l});a=await y.eachAlways(h);b={};for(const d in a)c=a[d].value,c="string"===
typeof c?k.applyTextFormattingHTML(k.htmlEntities(c)):Array.isArray(c)?B(c):"esri.arcade.Dictionary"===c?.declaredClass?C(c):c,b[d]=c;return b};n.loadArcade=t;Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});