// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../kernel ../request ../core/jsonMap ../core/screenUtils ../core/urlUtils ../geometry/Polygon ../layers/support/fieldUtils ../layers/support/floorFilterUtils ../renderers/visualVariables/support/visualVariableUtils ./utils ./geoprocessor/execute ./geoprocessor/submitJob ./support/fileFormat ./support/layoutTemplate ./support/printTaskUtils ./support/PrintTemplate ./support/reportTemplate".split(" "),function(w,C,J,K,x,z,R,S,T,U,D,V,W,X,Y,t,Z,aa){async function H(a,b){a=L(a);const c=
E.get(a)??{gpServerUrl:a,legendLayerNameMap:{},legendLayers:[]};c.gpMetadata??(c.gpMetadata=(await J(a,D.asValidOptions({f:"json"},b))).data);c.cimVersion=c.gpMetadata.cimVersion;E.set(a,c);return c}async function M(a,b){a=await H(a,b);return a.gpMetadata?.executionType?ba.fromJSON(a.gpMetadata.executionType):"sync"}async function N(a,b){b=b||{is11xService:!1,legendLayerNameMap:{},legendLayers:[]};var c=a.template||new Z;null==c.showLabels&&(c.showLabels=!0);var d=c.exportOptions,g=Y.toJSON(c.layout);
if(d){var h={dpi:d.dpi};if("map_only"===g.toLowerCase()||""===g){var e=d.width;d=d.height;h.outputSize=null!=e&&null!=d?[e,d]:void 0}}e=c.layoutOptions;let f;if(e){if("Miles"===e.scalebarUnit||"Kilometers"===e.scalebarUnit){var m="Kilometers";var l="Miles"}else if("Meters"===e.scalebarUnit||"Feet"===e.scalebarUnit)m="Meters",l="Feet";f={titleText:e.titleText,authorText:e.authorText,copyrightText:e.copyrightText,customTextElements:e.customTextElements,elementOverrides:e.elementOverrides,scaleBarOptions:{metricUnit:O.toJSON(m),
metricLabel:m?P[m]:void 0,nonMetricUnit:O.toJSON(l),nonMetricLabel:l?P[l]:void 0}}}m=null;e?.legendLayers&&(m=e.legendLayers.map(k=>{var n=k.layerId;b.legendLayerNameMap[n]=k.title;n={id:n};k.subLayerIds&&(n.subLayerIds=k.subLayerIds);return n}));l=await ca(a,c,b);if(l.operationalLayers){const k=RegExp("[\\u4E00-\\u9FFF\\u0E00-\\u0E7F\\u0900-\\u097F\\u3040-\\u309F\\u30A0-\\u30FF\\u31F0-\\u31FF]"),n=/[\u0600-\u06FF]/;e=q=>{const p=q.text;q=q.font;const r=q?.family?.toLowerCase();p&&q&&("arial"===r||
"arial unicode ms"===r)&&(q.family=k.test(p)?"Arial Unicode MS":"Arial","normal"!==q.style&&n.test(p)&&(q.family="Arial Unicode MS"))};for(const q of l.operationalLayers)if(q.featureCollection?.layers)for(const p of q.featureCollection.layers)if(p.layerDefinition?.drawingInfo?.renderer?.symbol&&(d=p.layerDefinition.drawingInfo.renderer,"esriTS"===d.symbol.type&&e(d.symbol)),p.featureSet?.features)for(const r of p.featureSet.features)r.symbol&&"esriTS"===r.symbol.type&&e(r.symbol)}a.outSpatialReference&&
(l.mapOptions.spatialReference=a.outSpatialReference.toJSON());Object.assign(l,{exportOptions:h,layoutOptions:f||{}});Object.assign(l.layoutOptions,{legendOptions:{operationalLayers:null!=m?m:b.legendLayers.slice()}});b.legendLayers.length=0;E.set(b.gpServerUrl,b);h={Web_Map_as_JSON:JSON.stringify(l),Format:X.toJSON(c.format),Layout_Template:g,Layout_Item_ID:void 0,Report_Template:aa.toJSON(c.report),Report_Item_ID:void 0};c.layoutItem&&(delete h.Layout_Template,g=c.layoutItem,await g.load(),"public"!==
g.access&&C.id&&await C.id.getCredential(b.gpServerUrl),h.Layout_Item_ID=JSON.stringify({id:g.id}));c.reportItem&&(delete h.Report_Template,c=c.reportItem,await c.load(),"public"!==c.access&&C.id&&await C.id.getCredential(b.gpServerUrl),h.Report_Item_ID=JSON.stringify({id:c.id}));a.extraParameters&&Object.assign(h,a.extraParameters);return h}async function ca(a,b,c){var d=a.view;let g=d.spatialReference;const h={operationalLayers:await da(d,b,c)};b.includeTables&&(h.tables=await ea(d));a=a.extent||
c.ssExtent||d.extent;g?.isWrappable&&(a=a.clone()._normalize(!0),g=a.spatialReference);h.mapOptions={extent:a&&a.toJSON(),spatialReference:g&&g.toJSON(),showAttribution:b.attributionVisible};c.ssExtent=null;d.background&&(h.background=d.background.toJSON());d.rotation&&(h.mapOptions.rotation=-d.rotation);b.scalePreserved&&(h.mapOptions.scale=b.outScale||d.scale);null!=d.timeExtent&&(c=null!=d.timeExtent.start?d.timeExtent.start.getTime():null,d=null!=d.timeExtent.end?d.timeExtent.end.getTime():null,
h.mapOptions.time=[c,d]);b.reportOptions&&(h.reportOptions=b.reportOptions);return h}function L(a){const b=a.lastIndexOf("/GPServer/");0<b&&(a=a.slice(0,b+9));return a}async function da(a,b,c){const d=[],g={layerView:null,printTemplate:b,view:a};let h=0;b.scalePreserved&&(h=b.outScale||a.scale);var e=t.getVisibleLayerViews(a,h);for(const k of e)if(e=k.layer,e.loaded&&!("layers"in e)){var f=void 0;g.layerView=k;if(t.isScreenshotRequired(k))f=await A(e,g,c);else if(t.isBingMapsLayer(e))f={culture:e.culture,
key:e.key,type:`BingMaps${"aerial"===e.style?"Aerial":"hybrid"===e.style?"Hybrid":"Road"}`};else if(t.isCSVLayer(e))f=await fa(e,g,c);else if("catalog-footprint"===e?.type)f=await ha(e,g,c);else if("feature"===e?.type)f=await ia(e,g,c);else if("geojson"===e?.type)f=await ja(e,g,c);else if("graphics"===e?.type)f=await ka(e,g,c);else if("imagery"===e?.type){var m=void 0,l=void 0;f=e;f.legendEnabled&&c.legendLayers.push({id:f.id});l=u(f);l={layerType:l.layerType,customParameters:l.customParameters};
l.bandIds=f.bandIds;l.compressionQuality=f.compressionQuality;l.format=f.format;l.interpolation=f.interpolation;if(f.mosaicRule||f.definitionExpression)l.mosaicRule=f.exportImageServiceParameters.mosaicRule.toJSON();f.rasterFunction&&(l.renderingRule=f.rasterFunction.toJSON());f.renderer&&(l.layerDefinition??(l.layerDefinition={}),(m=l.layerDefinition).drawingInfo??(m.drawingInfo={}),l.layerDefinition.drawingInfo.renderer=f.renderer.toJSON());y(l,f);f=l}else"imagery-tile"===e?.type?f=await la(e,g,
c):"kml"===e?.type?f=await ma(e,g,c):"map-image"===e?.type?f=na(e,g,c):"map-notes"===e?.type?f=await oa(g,c):"open-street-map"===e?.type?f={type:"OpenStreetMap"}:"stream"===e?.type?f=await pa(e,g,c):"tile"===e?.type?(m=void 0,f=e,f.legendEnabled&&c.legendLayers.push({id:f.id}),m=u(f),m={layerType:m.layerType,customParameters:m.customParameters},y(m,f),f=m):"vector-tile"===e?.type?f=await qa(e,g,c):"web-tile"===e?.type?(f={type:"WebTiledLayer",urlTemplate:e.urlTemplate?.replace(/\${/g,"{"),credits:e.copyright},
e.subDomains&&0<e.subDomains.length&&(f.subDomains=e.subDomains)):"wms"===e?.type?f=ra(e,c):"wmts"===e?.type?(f=e.activeLayer,f={type:"wmts",customLayerParameters:e.customLayerParameters,customParameters:e.customParameters,format:f.imageFormat,layer:f.id,style:f.styleId,tileMatrixSet:f.tileMatrixSetId,url:z.normalize(e.url)}):f=await A(e,g,c);f&&(Array.isArray(f)?d.push(...f):(f.id=e.id,f.title=c.legendLayerNameMap[e.id]||e.title,f.opacity=k.fullOpacity,f.minScale=e.minScale||0,f.maxScale=e.maxScale||
0,t.isBlendLayer(e)&&e.blendMode&&"normal"!==e.blendMode&&(f.blendMode=e.blendMode),d.push(f)))}if(h)for(const k of d)k.minScale=0,k.maxScale=0;a.graphics?.length&&(a=await v(null,a.graphics,b,c))&&d.push(a);return d}async function ha(a,{layerView:b,printTemplate:c},d){if(3.1>parseFloat(d.cimVersion))return b=await B(b),v(a,b,c,d);a=a.parent;c=u(a,"web-map");c={id:c.id,url:c.url,layerType:c.layerType,customParameters:c.customParameters,dynamicGroupLayer:{visibility:!1},footprintLayer:c.footprintLayer,
layerDefinition:c.layerDefinition};y(c,a);return c}async function fa(a,b,c){a.legendEnabled&&c.legendLayers.push({id:a.id});var d=b.layerView;b=b.printTemplate;if(!(d.filter||a.portalItem&&"public"!==a.portalItem.access))return c=u(a,"web-map"),c.type="CSV",delete c.popupInfo,delete c.layerType,c.showLabels=b.showLabels&&a.labelsVisible,c;d=await B(d);return v(a,d,b,c)}async function v(a,b,c,d){let g;var h=t.createPolygonLayer();const e=t.createPolylineLayer(),f=t.createPointLayer(),m=t.createMultipointLayer(),
l=t.createPointLayer();l.layerDefinition.name="textLayer";delete l.layerDefinition.drawingInfo;if(a){"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass?h.layerDefinition.name=e.layerDefinition.name=f.layerDefinition.name=m.layerDefinition.name=d.legendLayerNameMap[a.id]||a.get("arcgisProps.title")||a.title:"esri.layers.GraphicsLayer"===a.declaredClass&&(b=a.graphics.items);if(a.renderer){var k=a.renderer.toJSON(),n=h.layerDefinition.drawingInfo;n&&(n.renderer=
k);if(n=e.layerDefinition.drawingInfo)n.renderer=k;if(n=f.layerDefinition.drawingInfo)n.renderer=k;if(n=m.layerDefinition.drawingInfo)n.renderer=k}if(c.showLabels&&a.labelsVisible&&"function"===typeof a.write&&(k=u(a,"web-map").layerDefinition?.drawingInfo?.labelingInfo)){g=!0;if(n=h.layerDefinition.drawingInfo)n.labelingInfo=k;if(n=e.layerDefinition.drawingInfo)n.labelingInfo=k;if(n=f.layerDefinition.drawingInfo)n.labelingInfo=k;if(n=m.layerDefinition.drawingInfo)n.labelingInfo=k}}a?.renderer||g||
(delete h.layerDefinition.drawingInfo,delete e.layerDefinition.drawingInfo,delete f.layerDefinition.drawingInfo,delete m.layerDefinition.drawingInfo);k=a?.fieldsIndex;n=a?.renderer;if(k){var q=new Set;g&&await S.collectLabelingFields(q,a);n&&"function"===typeof n.collectRequiredFields&&await n.collectRequiredFields(q,k);q=Array.from(q);a=k.fields.map(p=>p.toJSON());h.layerDefinition.fields=a;e.layerDefinition.fields=a;f.layerDefinition.fields=a;m.layerDefinition.fields=a}a=b?.length;for(n=0;n<a;n++){const p=
b[n]||b.at(n);if(!1!==p.visible&&p.geometry){k=p.toJSON();k.hasOwnProperty("popupTemplate")&&delete k.popupTemplate;k.geometry?.z&&delete k.geometry.z;k.symbol&&(k.symbol.angle||delete k.symbol.angle,F(k.symbol)?k.symbol=await G(k.symbol,d):k.symbol.text&&delete k.attributes);if((!c||!c.forceFeatureAttributes)&&q?.length){const r={};for(const I of q)k.attributes?.hasOwnProperty(I)&&(r[I]=k.attributes[I]);k.attributes=r}"polygon"===p.geometry.type?h.featureSet.features.push(k):"polyline"===p.geometry.type?
e.featureSet.features.push(k):"point"===p.geometry.type?k.symbol?.text?l.featureSet.features.push(k):f.featureSet.features.push(k):"multipoint"===p.geometry.type?m.featureSet.features.push(k):"extent"===p.geometry.type&&(k.geometry=R.fromExtent(p.geometry).toJSON(),h.featureSet.features.push(k))}}b=[h,e,m,f,l].filter(p=>0<p.featureSet.features.length);for(const p of b){if((h=p.featureSet.features.every(r=>r.symbol))&&(!c||!c.forceFeatureAttributes))for(const r of p.featureSet.features)delete r.attributes;
h&&delete p.layerDefinition.drawingInfo;p.layerDefinition.drawingInfo?.renderer&&await Q(p.layerDefinition.drawingInfo.renderer,d)}return b.length?{featureCollection:{layers:b},showLabels:g}:null}async function ia(a,b,c){const d=a.renderer;var g=parseFloat(c.cimVersion);if("binning"===a.featureReduction?.type||"cluster"===a.featureReduction?.type&&2.9>g||"pie-chart"===d?.type||"dot-density"===d?.type&&2.6>g)return A(a,b,c);a.legendEnabled&&c.legendLayers.push({id:a.id});g=b.layerView;const {printTemplate:h,
view:e}=b;b="feature-layer"!==a.source?.type&&"ogc-feature"!==a.source?.type;if(g.filter||b||!d||"field"in d&&null!=d.field&&!a.getField(d.field)){var f=await B(g);b=await v(a,f,h,c)}else{b=u(a);b={id:b.id,title:b.title,url:b.url,layerType:b.layerType,customParameters:b.customParameters,layerDefinition:b.layerDefinition,charts:h.includeCharts?b.charts:void 0};b.showLabels=h.showLabels&&a.labelsVisible;y(b,a);b.layerDefinition?.drawingInfo?.renderer&&(delete b.layerDefinition.minScale,delete b.layerDefinition.maxScale,
await Q(b.layerDefinition.drawingInfo.renderer,c),"visualVariables"in d&&d.visualVariables&&d.visualVariables[0]&&(c=d.visualVariables[0],"size"===c.type&&c.maxSize&&"number"!==typeof c.maxSize&&c.minSize&&"number"!==typeof c.minSize&&(c=U.getSizeRangeAtScale(c,e.scale),b.layerDefinition.drawingInfo.renderer.visualVariables[0].minSize=c.minSize,b.layerDefinition.drawingInfo.renderer.visualVariables[0].maxSize=c.maxSize)));if(c=T.getFloorFilterClause(g))(f=b).layerDefinition??(f.layerDefinition={}),
b.layerDefinition.definitionExpression=b.layerDefinition.definitionExpression?`(${b.layerDefinition.definitionExpression}) AND (${c})`:c;if(a.gdbVersion){let m;(m=b).layerDefinition??(m.layerDefinition={});b.layerDefinition.gdbVersion=a.gdbVersion}g.hasHighlight?.()&&"getHighlightIds"in g&&(b.selectionObjectIds=g.getHighlightIds(),b.selectionSymbol=t.getSelectionSymbol(a.geometryType,g.highlightOptions??e.highlightOptions))}return b}async function ja(a,b,c){if("binning"===a.featureReduction?.type||
"cluster"===a.featureReduction?.type)return A(a,b,c);a.legendEnabled&&c.legendLayers.push({id:a.id});const d=await B(b.layerView);return v(a,d,b.printTemplate,c)}async function ka(a,{printTemplate:b},c){return v(a,null,b,c)}async function la(a,b,c){if("flow"===a.renderer?.type)return A(a,b,c);a.legendEnabled&&c.legendLayers.push({id:a.id});b=u(a);b={bandIds:b.bandIds,customParameters:b.customParameters,interpolation:b.interpolation,layerDefinition:b.layerDefinition,layerType:"ArcGISImageServiceLayer"};
y(b,a);return b}async function ma(a,b,c){const d=b.printTemplate;if(!a.portalItem||"public"===a.portalItem.access)return c=u(a,"web-map"),c.type="kml",delete c.layerType,c.url=z.normalize(a.url),c;const g=[],h=b.layerView;h.allVisibleMapImages.forEach((e,f)=>{f={id:`${a.id}_image${f}`,type:"image",title:a.id,minScale:a.minScale||0,maxScale:a.maxScale||0,opacity:h.fullOpacity,extent:e.extent};"data:image/png;base64,"===e.href.substr(0,22)?f.imageData=e.href.substr(22):f.url=e.href;g.push(f)});b=[...h.allVisiblePoints.items,
...h.allVisiblePolylines.items,...h.allVisiblePolygons.items];c={id:a.id,...(await v(null,b,d,c))};g.push(c);return g}function na(a,{view:b},c){let d;const g={id:a.id,subLayerIds:[]};let h=[];const e=b.scale,f=m=>{var l=0===e;const k=0===m.minScale||e<=m.minScale,n=0===m.maxScale||e>=m.maxScale;m.visible&&(l||k&&n)&&(m.sublayers?m.sublayers.forEach(f):(l=m.toExportImageJSON(),h.unshift({id:m.id,name:m.title,layerDefinition:{drawingInfo:l.drawingInfo,definitionExpression:l.definitionExpression,source:l.source}}),
g.subLayerIds.push(m.id)))};a.sublayers&&a.sublayers.forEach(f);h.length&&(h=h.map(({id:m,name:l,layerDefinition:k})=>({id:m,name:l,layerDefinition:k})),d=(m=>({layerType:m.layerType,customParameters:m.customParameters}))(u(a)),d.layers=h,d.visibleLayers=a.capabilities?.exportMap?.supportsDynamicLayers?void 0:g.subLayerIds,a.gdbVersion&&(d.gdbVersion=a.gdbVersion),y(d,a),a.legendEnabled&&c.legendLayers.push(g));return d}async function oa({layerView:a,printTemplate:b},c){const d=[];a=a.layer;if(null!=
a.featureCollections)for(var g of a.featureCollections){var h=await v(g,g.source,b,c);h&&d.push(...h.featureCollection.layers)}else if(null!=a.sublayers)for(h of a.sublayers)(g=await v(null,h.graphics,b,c))&&d.push(...g.featureCollection.layers);return{featureCollection:{layers:d}}}async function A(a,{printTemplate:b,view:c},d){const g={type:"image"};a={format:"png",ignoreBackground:!0,ignorePadding:!0,layers:[a]};0!==c.rotation&&(a.rotation=0);const h=d.ssExtent||c.state.extent.clone();let e=96,
f=!0,m=!0;if(b.exportOptions){const l=b.exportOptions;null!=l.dpi&&0<l.dpi&&(e=l.dpi);null!=l.width&&0<l.width&&(f=l.width%2===c.width%2);null!=l.height&&0<l.height&&(m=l.height%2===c.height%2)}"map-only"!==b.layout||!b.scalePreserved||b.outScale&&b.outScale!==c.scale||96!==e||f&&m||!c.state.extent.equals(c.extent)||(a.area={x:0,y:0,width:c.width,height:c.height},f||--a.area.width,m||--a.area.height,d.ssExtent||(b=c.toMap(x.createScreenPoint(a.area.width,a.area.height)),h.ymin=b.y,h.xmax=b.x,d.ssExtent=
h));g.extent=h.clone()._normalize(!0).toJSON();c=await c.takeScreenshot(a);g.imageData=z.dataComponents(c.dataUrl)?.data;return g}async function pa(a,{layerView:b,printTemplate:c},d){a.legendEnabled&&d.legendLayers.push({id:a.id});b=await B(b);return v(a,b,c,d)}async function ea(a){const b=[],c=[];for(const d of a.map.allTables)"feature"!==d.type||d.loaded||c.push(d.load());c.length&&await Promise.allSettled(c);for(const d of a.map.allTables)"feature"===d.type&&d.loaded&&d.isTable&&"feature-layer"===
d.source?.type&&(a=u(d),a={id:a.id,title:a.title,customParameters:a.customParameters,layerDefinition:{definitionExpression:a.layerDefinition?.definitionExpression},url:a.url},y(a,d),b.push(a));return b.length?b:void 0}async function qa(a,b,c){if(a.serviceUrl&&a.styleUrl){const d=D.getToken(a.styleUrl,a.apiKey),g=D.getToken(a.serviceUrl,a.apiKey);if(!d&&!g||"2.1.0"!==c.cimVersion)return b={type:"VectorTileLayer"},b.styleUrl=z.normalize(a.styleUrl),b.token=d,g!==d&&(b.additionalTokens=[{url:a.serviceUrl,
token:g}]),b}return A(a,b,c)}function ra(a,b){let c;const d=[],g=h=>{h.visible&&(h.sublayers?h.sublayers.forEach(g):h.name&&d.unshift(h.name))};a.sublayers&&a.sublayers.forEach(g);d.length&&(a.legendEnabled&&b.legendLayers.push({id:a.id,subLayerIds:d}),c={type:"wms",customLayerParameters:a.customLayerParameters,customParameters:a.customParameters,transparentBackground:a.imageTransparency,visibleLayers:d,url:z.normalize(a.url),version:a.version});return c}function y(a,b){b.url&&(a.url=z.normalize(a.url||
b.url),a.token=D.getToken(a.url,b.apiKey))}async function G(a,b){b.canvas||(b.canvas=document.createElement("canvas"));b.canvas.width=1024;b.canvas.height=1024;b=b.canvas.getContext("2d");if(a.path){var c=new Path2D(a.path);c.closePath();b.fillStyle=Array.isArray(a.color)?`rgba(${a.color[0]},${a.color[1]},${a.color[2]},${a.color[3]/255})`:"rgb(0,0,0)";b.fill(c);var d=t.getContextBoundingBox(b);if(!d)return null;b.clearRect(0,0,1024,1024);var g=x.pt2px(a.size)/Math.max(d.width,d.height);b.scale(g,
g);var h=1024/g;b.translate(h/2-d.width/2-d.x,h/2-d.height/2-d.y);Array.isArray(a.color)&&b.fill(c);a.outline?.width&&Array.isArray(a.outline.color)&&(h=a.outline,b.lineWidth=x.pt2px(h.width)/g,b.lineJoin="round",b.strokeStyle=`rgba(${h.color[0]},${h.color[1]},${h.color[2]},${h.color[3]/255})`,b.stroke(c),d.width+=b.lineWidth,d.height+=b.lineWidth);d.width*=g;d.height*=g;g=b.getImageData(512-d.width/2,512-d.height/2,Math.ceil(d.width),Math.ceil(d.height));c=g.width;d=g.height;b.canvas.width=c;b.canvas.height=
d;b.putImageData(g,0,0)}else g=(await J("image/svg+xml"===a.contentType?"data:image/svg+xml;base64,"+a.imageData:a.url,{responseType:"image"})).data,c=x.pt2px(a.width),d=x.pt2px(a.height),b.canvas.width=c,b.canvas.height=d,b.drawImage(g,0,0,b.canvas.width,b.canvas.height);return{type:"esriPMS",imageData:b.canvas.toDataURL("image/png").substr(22),angle:a.angle,contentType:"image/png",height:x.px2pt(d),width:x.px2pt(c),xoffset:a.xoffset,yoffset:a.yoffset}}async function Q(a,b){const c=a.type;if("simple"===
c&&F(a.symbol))a.symbol=await G(a.symbol,b);else if("uniqueValue"===c||"classBreaks"===c)if(F(a.defaultSymbol)&&(a.defaultSymbol=await G(a.defaultSymbol,b)),a=a["uniqueValue"===c?"uniqueValueInfos":"classBreakInfos"])for(const d of a)F(d.symbol)&&(d.symbol=await G(d.symbol,b))}async function B(a){return a.queryFeatures(a.createQuery()).then(b=>b.features)}function u(a,b){return a.write({},{ignorePersistenceEnabled:!0,origin:b})??{}}function F(a){return a&&(a.path||"image/svg+xml"===a.contentType||
a.url?.endsWith(".svg"))}const P={Feet:"ft",Kilometers:"km",Meters:"m",Miles:"mi"},O=new K.JSONMap({esriFeet:"Feet",esriKilometers:"Kilometers",esriMeters:"Meters",esriMiles:"Miles"}),ba=new K.JSONMap({esriExecutionTypeSynchronous:"sync",esriExecutionTypeAsynchronous:"async"}),E=new Map;w.execute=async function(a,b,c){var d=await H(a,c);d=await N(b,d);if("sync"===await M(a,c))return{results:b}=await V.execute(a,d,void 0,c),b?.[0]?.value;a=await W.submitJob(a,d,void 0,c);await a.waitForJobCompletion({interval:b.updateDelay});
({value:b}=await a.fetchResultData("Output_File",null,c));return b};w.getGpPrintParams=N;w.getGpServerUrl=L;w.getMode=M;w.getTasks=async function(a,b){return(await H(a,b)).gpMetadata.tasks};w.printCacheMap=E;Object.defineProperty(w,Symbol.toStringTag,{value:"Module"})});