// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../geometry ../../../core/compilerUtils ../../../core/Evented ../../../core/handleUtils ../../../core/has ../../../core/mathUtils ../../../core/maybe ../../../core/screenUtils ../../../core/libs/gl-matrix-2/math/mat3 ../../../core/libs/gl-matrix-2/factories/mat3f64 ../../../core/libs/gl-matrix-2/math/mat4 ../../../core/libs/gl-matrix-2/factories/mat4f64 ../../../core/libs/gl-matrix-2/math/vec2 ../../../chunks/vec32 ../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../geometry/ellipsoidUtils ../../../geometry/projection ../../../geometry/projection/localRotationUtils ../../../geometry/projection/projectors ../../../geometry/support/aaBoundingRect ../../../geometry/support/lineSegment ../../../geometry/support/plane ../../../geometry/support/ray ../../../geometry/support/vectorStacks ../../../layers/graphics/hydratedFeatures ../../../support/elevationInfoUtils ../support/ElevationProvider ../support/geometryUtils/ray ../webgl/RenderCamera ../webgl-engine/lib/Object3D ../webgl-engine/lib/UpdatePolicy ../webgl-engine/lib/WebGLLayer ../../interactive/interfaces ../../../geometry/Point".split(" "),
function(E,oa,Q,R,S,pa,F,T,n,G,U,p,v,V,h,m,W,H,X,Y,Z,q,r,aa,w,A,ba,B,C,ca,da,ea,fa,k,x){function I(a){return 0!==a[12]||0!==a[13]||0!==a[14]}class ha{constructor(a){this.metadata=void 0;this._camera=new ca;this._elevation={offset:0,override:null};this.collisionType={type:"point"};this.collisionPriority=0;this._renderObjects=[];this._available=this.autoScaleRenderObjects=!0;this._noDisplayCount=0;this._radius=10;this._worldSized=!1;this.focusMultiplier=2;this.touchMultiplier=2.5;this.worldOriented=
!1;this._modelTransform=v.create();this._worldFrame=null;this._renderLocation=m.create();this._renderLocationDirty=!0;this._location=new x({x:0,y:0,z:0});this._elevationAlignedLocation=new x;this.interactive=this._elevationAlignedLocationDirty=!0;this.selectable=!1;this.consumesClicks=this.grabbable=!0;this.grabCursor=this.cursor=null;this._selected=this._hovering=this.dragging=this._grabbing=!1;this._state=k.ManipulatorStateCustomFlags.None;this._focused=!1;this.events=new R.EventEmitter;this._screenLocation=
{screenPointArray:n.createScreenPointArray(),renderScreenPointArray:n.createRenderScreenPointArray3(),pixelSize:0};this._screenLocationDirty=!0;this._attached=this._engineResourcesAddedToStage=!1;this._location.spatialReference=a.view.spatialReference;Object.assign(this,a);(a=this.view.state?.camera)&&this._camera.copyFrom(a)}destroy(){this._applyObjectTransform=ia;this._removeResourcesFromStage();this._camera=this.view=this._engineResources=null}get _stage(){return this.view?._stage}get elevationInfo(){return this._elevationInfo}set elevationInfo(a){this._elevationInfo=
a;this._renderLocationDirty=this._elevationAlignedLocationDirty=!0;this._updateEngineObject()}get renderObjects(){return this._renderObjects}set renderObjects(a){this._removeResourcesFromStage();this._engineResources=null;this._renderObjects=a.slice();this._updateEngineObject()}set available(a){a!==this._available&&(this._available=a,this._updateEngineObject())}get available(){return this._available}disableDisplay(){this._noDisplayCount++;1===this._noDisplayCount&&this._updateEngineObject();return S.makeHandle(()=>
{this._noDisplayCount--;0===this._noDisplayCount&&this._updateEngineObject()})}set radius(a){a!==this._radius&&(this._radius=a,this._updateEngineObject())}get radius(){return this._radius}set worldSized(a){a!==this._worldSized&&(this._worldSized=a,this._updateEngineObject())}get worldSized(){return this._worldSized}get modelTransform(){return this._modelTransform}set modelTransform(a){I(a)&&(this._screenLocationDirty=!0);p.copy(this._modelTransform,a);this._updateEngineObject()}get renderLocation(){if(this._renderLocationDirty)if(this._renderLocationDirty=
!1,this.view.renderCoordsHelper.toRenderCoords(this.elevationAlignedLocation,this._renderLocation),this.worldOriented){this._worldFrame||(this._worldFrame=v.create());a:{var a=this.view,b=this._renderLocation,e=this._worldFrame;switch(a.viewingMode){case "local":p.identity(e);break a;case "global":a=W.getReferenceEllipsoid(a.renderCoordsHelper.spatialReference),Y.sphericalPCPFtoLonLatElevation(b,0,t,0,a.radius),X.computeENUToSphericalPCPFLocalRotation(F.deg2rad(t[0]),F.deg2rad(t[1]),e)}}}else this._worldFrame&&
(this._worldFrame=null);return this._renderLocation}set renderLocation(a){this.view.renderCoordsHelper.fromRenderCoords(a,this._location);this.elevationAlignedLocation=this._location}get location(){return this._location}set location(a){A.clonePoint(a,this._location);this._notifyLocationChanged()}_notifyLocationChanged(){this._elevationAlignedLocationDirty=this._screenLocationDirty=this._renderLocationDirty=!0;this._updateEngineObject();this.events.emit("location-update",{location:this._location})}get elevationAlignedLocation(){if(!this._elevationAlignedLocationDirty)return this._elevationAlignedLocation;
this._evaluateElevationAlignment();this._updateElevationAlignedLocation();return this._elevationAlignedLocation}set elevationAlignedLocation(a){A.clonePoint(a,this._location);this._evaluateElevationAlignment();this._location.z-=this._elevation.offset;this._updateElevationAlignedLocation();this._updateEngineObject();this.events.emit("location-update",{location:this._location})}_updateElevationAlignedLocation(){const a=null!=this._elevation.override?this._elevation.override:this.location.z||0;this._elevationAlignedLocation.x=
this.location.x;this._elevationAlignedLocation.y=this.location.y;this._elevationAlignedLocation.z=a+this._elevation.offset;this._elevationAlignedLocation.spatialReference=A.hydratedSpatialReference(this.location.spatialReference);this._screenLocationDirty=this._renderLocationDirty=!0;this._elevationAlignedLocationDirty=!1}grabbableForEvent(){return!0}get grabbing(){return this._grabbing}set grabbing(a){a!==this._grabbing&&(this._grabbing=a,this._setFocused(this._hovering||this._grabbing),this._updateEngineObject())}get hovering(){return this._hovering}set hovering(a){a!==
this._hovering&&(this._hovering=a,this._setFocused(this._hovering||this._grabbing),this._updateEngineObject())}get selected(){return this._selected}set selected(a){a!==this._selected&&(this._selected=a,this._updateEngineObject(),this.events.emit("select-changed",{action:a?"select":"deselect"}))}get state(){return this._state}set state(a){a!==this._state&&(this._state=a,this._updateEngineObject())}updateStateEnabled(a,b){this.state=b?this.state|a:this.state&~a}_setFocused(a){a!==this._focused&&(this._focused=
a,this.events.emit("focus-changed",{action:!0===a?"focus":"unfocus"}))}get focused(){return this._focused}get screenLocation(){this._ensureScreenLocation();return this._screenLocation}_ensureScreenLocation(){if(this._screenLocationDirty){this._screenLocation.pixelSize=this._camera.computeScreenPixelSizeAt(this.renderLocation);this._screenLocationDirty=!1;if(I(this._modelTransform)){var a=this._calculateModelTransformOffset(ja);a=h.add(a,a,this.renderLocation)}else a=this.renderLocation;this._camera.projectToRenderScreen(a,
this._screenLocation.renderScreenPointArray);this._camera.renderToScreen(this._screenLocation.renderScreenPointArray,this._screenLocation.screenPointArray)}}get applyObjectTransform(){return this._applyObjectTransform}set applyObjectTransform(a){this._applyObjectTransform=a;this._screenLocationDirty=!0;this._updateEngineObject()}get attached(){return this._attached}intersectionDistance(a,b){if(!this.available)return null;a=n.screenPointObjectToArray(a,ka);var e=this._getCollisionRadius(b);b=-1*this.collisionPriority;
switch(this.collisionType.type){case "point":if(V.squaredDistance(this.screenLocation.screenPointArray,a)<e*e)return this.screenLocation.renderScreenPointArray[2]+b;break;case "line":var g=this.collisionType.paths,c=this._getWorldToScreenObjectScale();c=this._calculateObjectTransform(c,y);e*=this.screenLocation.pixelSize;a=C.fromScreen(this._camera,a,D);if(null==a)break;for(var d of g)if(0!==d.length){g=h.transformMat4(t,d[0],c);for(var f=1;f<d.length;f++){var l=h.transformMat4(J,d[f],c),u=q.closestRayDistance2(q.fromPoints(g,
l,K),a);if(null!=u&&u<e*e)return c=h.add(w.sv3d.get(),g,l),h.scale(c,c,.5),a=n.castRenderScreenPointArray(w.sv3d.get()),this._camera.projectToRenderScreen(c,a),a[2]+b;h.copy(g,l)}}break;case "disc":g=this.collisionType.direction;c=this.collisionType.offset??m.ZEROS;d=this._getWorldToScreenObjectScale();f=this._calculateObjectTransform(d,y);d=e*this.screenLocation.pixelSize;a=C.fromScreen(this._camera,a,D);if(null==a)break;e=G.fromMat4(L,f);e=h.transformMat3(M,g,e);c=h.transformMat4(N,c,f);r.fromPositionAndNormal(c,
e,z);e=O;if(r.intersectRay(z,a,e)&&h.squaredDistance(e,c)<d*d)return this.screenLocation.renderScreenPointArray[2]+b;break;case "ribbon":const {paths:la,direction:ma}=this.collisionType;d=this._getWorldToScreenObjectScale();d=this._calculateObjectTransform(d,y);e*=this._camera.computeScreenPixelSizeAt(this.renderLocation);g=C.fromScreen(this._camera,a,D);if(null==g)break;a=G.fromMat4(L,d);a=h.transformMat3(M,ma,a);f=this._calculateModelTransformPosition(N);r.fromPositionAndNormal(f,a,z);a=O;if(!r.intersectRay(z,
g,a))break;for(c of la)if(0!==c.length)for(g=h.transformMat4(t,c[0],d),f=1;f<c.length;f++){l=h.transformMat4(J,c[f],d);u=q.distance2(q.fromPoints(g,l,K),a);if(null!=u&&u<e*e)return c=h.add(w.sv3d.get(),g,l),h.scale(c,c,.5),a=n.castRenderScreenPointArray(w.sv3d.get()),this._camera.projectToRenderScreen(c,a),a[2]+b;h.copy(g,l)}break;default:Q.neverReached(this.collisionType)}return null}attach(a={manipulator3D:{}}){const b=this._stage;b&&(a=a.manipulator3D,null==a.engineLayerId?(this._engineLayer=new fa.WebGLLayer(b,
{pickable:!1,updatePolicy:ea.UpdatePolicy.SYNC}),a.engineLayerId=this._engineLayer.id):b?.getObject&&(this._engineLayer=b.getObject(a.engineLayerId)),a.engineLayerReferences=(a.engineLayerReferences||0)+1,this._materialIdReferences=a.materialIdReferences,null==this._materialIdReferences&&(this._materialIdReferences=new Map,a.materialIdReferences=this._materialIdReferences),this._camera.copyFrom(this.view.state.camera),this._attached=!0,this._updateEngineObject(),H.canProjectWithoutEngine(this._location.spatialReference,
this.view.spatialReference)||(this.location=new x({x:0,y:0,z:0,spatialReference:this.view.spatialReference})))}detach(a={manipulator3D:{}}){a=a.manipulator3D;a.engineLayerReferences--;const b=0===a.engineLayerReferences;this._removeResourcesFromStage();b&&(a.engineLayerId=null,T.destroyMaybe(this._engineLayer));this._materialIdReferences=this._engineLayer=this._engineResources=null;this._attached=!1}onViewChange(){this._camera.copyFrom(this.view.state.camera);this._screenLocationDirty=!0;this._updateEngineObject()}onElevationChange(a){H.projectPoint(this.location,
P,a.spatialReference)&&Z.containsPointObject(a.extent,P)&&this._notifyLocationChanged()}_evaluateElevationAlignment(){if(null!=this.elevationInfo){var a=null,b=0,e=ba.getElevationOffset(this.elevationInfo,this.location.spatialReference??this.view.elevationProvider.spatialReference);switch(this.elevationInfo.mode){case "on-the-ground":a=B.getElevationAtPoint(this.view.elevationProvider,this.location,"ground")??0;break;case "relative-to-ground":b=(B.getElevationAtPoint(this.view.elevationProvider,this.location,
"ground")??0)+e;break;case "relative-to-scene":b=(B.getElevationAtPoint(this.view.elevationProvider,this.location,"scene")??0)+e;break;case "absolute-height":b=e}if(b!==this._elevation.offset||a!==this._elevation.override)this._elevation.offset=b,this._elevation.override=a}}_updateEngineObject(){if(this._attached)if(this.available){var a=this._getWorldToScreenObjectScale(),b=y;!0===this.autoScaleRenderObjects?(a*=this._getFocusedSize(this._radius,this.focused),this._calculateObjectTransform(a,b)):
this._calculateObjectTransform(a,b);var {objectsByState:e}=this._ensureEngineResources();a=(this.focused?k.ManipulatorStateFlags.Focused:k.ManipulatorStateFlags.Unfocused)|(this.selected?k.ManipulatorStateFlags.Selected:k.ManipulatorStateFlags.Unselected);var g=0<this._noDisplayCount;for(const {stateMask:c,objects:d}of e)if(g)for(const f of d)f.visible=!1;else if(e=(c&k.ManipulatorStateCustomFlags.All)===k.ManipulatorStateCustomFlags.None||(this.state&c)===(c&k.ManipulatorStateCustomFlags.All),(c&
k.ManipulatorStateFlags.All)!==k.ManipulatorStateFlags.None&&(a&c)!==(c&k.ManipulatorStateFlags.All)||!e)for(const f of d)f.visible=!1;else for(const f of d)f.visible=!0,f.transformation=b}else this._removeResourcesFromStage()}_ensureEngineResources(){if(null==this._engineResources){const a=this._engineLayer,b=[],e=new Set;this.renderObjects.forEach(({geometry:{material:d}})=>{e.has(d)||(b.push(d),e.add(d))});const g=new Map;this._renderObjects.forEach(d=>{const f=new da.Object3D({castShadow:!1,geometries:[d.geometry]}),
l=g.get(d.stateMask)||[];l.push(f);g.set(d.stateMask,l)});const c=[];g.forEach((d,f)=>c.push({stateMask:f,objects:d}));this._engineResources={objectsByState:c,layer:a,materials:b}}this._addResourcesToStage();return this._engineResources}_addResourcesToStage(){const a=this._stage;if(!this._engineResourcesAddedToStage&&null!=this._engineResources&&a){var {objectsByState:b,layer:e,materials:g}=this._engineResources;g.forEach(c=>{const d=this._materialIdReferences,f=d.get(c.id)||0;0===f&&a.add(c);d.set(c.id,
f+1)});b.forEach(({objects:c})=>{e.addMany(c);a.addMany(c)});this._engineResourcesAddedToStage=!0}}_removeResourcesFromStage(){const a=this._stage;if(this._engineResourcesAddedToStage&&null!=this._engineResources&&a){var {objectsByState:b,layer:e,materials:g}=this._engineResources;b.forEach(({objects:c})=>{e.removeMany(c);a.removeMany(c)});g.forEach(c=>{const d=this._materialIdReferences,f=d.get(c.id);1===f?(a.remove(c),d.delete(c.id)):d.set(c.id,f-1)});this._engineResourcesAddedToStage=!1}}_getCollisionRadius(a){return this._getFocusedSize(this.radius,
!0)*("touch"===a?this.touchMultiplier:1)}_getFocusedSize(a,b){return a*(b?this.focusMultiplier:1)}_getWorldToScreenObjectScale(){return this._worldSized?1:this.screenLocation.pixelSize}_calculateModelTransformPosition(a){var b=this._getWorldToScreenObjectScale();b=this._calculateObjectTransform(b,na);return h.set(a,b[12],b[13],b[14])}_calculateModelTransformOffset(a){const b=this._calculateModelTransformPosition(a);return h.subtract(a,b,this.renderLocation)}_calculateObjectTransform(a,b){p.set(b,
a,0,0,0,0,a,0,0,0,0,a,0,0,0,0,1);this._worldFrame&&p.multiply(b,b,this._worldFrame);p.multiply(b,b,this._modelTransform);b[12]+=this.renderLocation[0];b[13]+=this.renderLocation[1];b[14]+=this.renderLocation[2];b[15]=1;null!=this._applyObjectTransform&&this._applyObjectTransform(b);return b}get test(){}}const ka=n.createScreenPointArray(),K=q.create(),D=aa.create(),L=U.create(),na=v.create(),y=v.create(),z=r.create(),t=m.create(),J=m.create(),O=m.create(),M=m.create(),N=m.create(),ja=m.create(),P=
new x({x:0,y:0,z:0,spatialReference:null}),ia=()=>{};E.Manipulator3D=ha;Object.defineProperty(E,Symbol.toStringTag,{value:"Module"})});