// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../../core/handleUtils ../../../../../core/quantityUtils ../../../../../core/reactiveUtils ../../../../../core/unitUtils ../../../../../geometry/support/plane ../../../../../geometry/support/vectorStacks ../manipulatedObjectUtils ../tooltipUtils3D ../manipulations/MoveManipulation ../manipulations/moveUtils ../../../../interactive/editGeometry/interfaces ../../../../interactive/tooltip/tooltipCommonUtils ../../../../interactive/tooltip/infos/MovePointTooltipInfo ../../../../interactive/tooltip/infos/ReshapeEdgeOffsetTooltipInfo ../../../../interactive/tooltip/infos/SelectedVertexTooltipInfo ../../../../interactive/tooltip/infos/TranslateTooltipInfo ../../../../interactive/tooltip/infos/TranslateXYTooltipInfo ../../../../interactive/tooltip/infos/TranslateZTooltipInfo ../../../../support/automaticAreaMeasurementUtils ../../../../support/automaticLengthMeasurementUtils ../../../../support/euclideanLengthMeasurementUtils ../../../../support/geodesicLengthMeasurementUtils".split(" "),
function(l,z,k,m,A,B,C,t,n,q,D,E,u,F,G,H,I,J,K,v,p,L,M){function N(b,a,{selectedVertexManipulatorInfo:f,callbacks:d}){const e=t.manipulatedObjectGeometry(a);switch(e?.type){case "mesh":"move-point"===b.type&&n.updateXYZFromTooltipInfo(b,e.origin,a,d);break;case "point":"move-point"===b.type&&n.updateXYZFromTooltipInfo(b,e,a,d);break;case "polyline":case "polygon":if("selected-vertex"===b.type&&"vertex"===f?.type){var {dx:g,dy:c,dz:h}=u.getXYZDeltasFromTooltipInfo(b,f.manipulator.location);if(0!==
g||0!==c||0!==h)d.onReshapeStart?.(),a.operations?.moveVertices([f.handle],g,c,h,E.AccumulationBehavior.NEW_STEP),d.onReshape?.(),d.onReshapeStop?.()}}}function O(b,{activeTooltipInfo:a,selectedVertexManipulatorInfo:f,sketchOptions:d}){if(a)switch(a.sketchOptions=d,a?.type){case "move-point":n.updateTooltipInfoFromManipulatedObject(a,b);break;case "selected-vertex":if(a&&"selected-vertex"===a.type)switch(f=f?.manipulator.location,a.setLocationFromPoint(f),n.updateElevationFromPoint(a,f,b),b=b.operations?.data.geometry,
b?.type){case "polygon":a.geometryType="polygon";a.totalLength.visible=!1;a.area.actual=v.autoArea2D(b);break;case "polyline":a.geometryType="polyline",a.totalLength.actual=p.autoLength2D(b),a.area.visible=!1}}}function r(b,a,f){if(null!=a&&"end"!==a.action){const {mapStart:d,mapEnd:e}=a;a=f(d,e);b.distance=null!=a?a:k.zeroMeters}else b.distance=k.zeroMeters}l.connectTooltipToManipulatedObject=function(b,a,f){function d(){const c=f();return{...c,activeTooltipInfo:c.sketchOptions.tooltips.effectiveEnabled?
c.activeTooltipInfo:null}}function e(c){g=!0;O(a,c);b.info=c.activeTooltipInfo;g=!1}let g=!1;return z.handlesGroup([m.watch(d,e,m.syncAndInitial),m.watch(()=>{const c=d(),{activeTooltipInfo:h}=c;if(h&&"key"in h)return{context:c,activeTooltipInfo:h,key:h.key,geometry:t.manipulatedObjectGeometry(a)}},(c,h)=>{c&&!g&&h&&h.key!==c.key&&N(c.activeTooltipInfo,a,c.context)},m.sync),a.on("committed",()=>e(d())),u.connectPasteEvent(b)])};l.createTooltipInfos=function(b,a){a=a?.type;return{edgeOffset:new G.ReshapeEdgeOffsetTooltipInfo({sketchOptions:b,
viewType:a}),movePoint:new F.MovePointTooltipInfo({sketchOptions:b,viewType:a}),selectedVertex:new H.SelectedVertexTooltipInfo({sketchOptions:b,viewType:a}),translate:new I.TranslateTooltipInfo({sketchOptions:b,viewType:a}),translateXY:new J.TranslateXYTooltipInfo({sketchOptions:b,viewType:a}),translateZ:new K.TranslateZTooltipInfo({sketchOptions:b,viewType:a})}};l.getUpdatedEdgeOffsetTooltipInfo=function(b,a,{sketchOptions:f,tooltipInfos:d}){d=d.edgeOffset;d.distance=k.zeroMeters;if(null!=a&&"end"!==
a.action){var e=b.operations;const {mapEnd:h,signedDistance:w,operation:x}=a;if(null!=w&&null!=e){a:{a=w*x.selectedArrow;var g=h,c=x.plane;e=e.data.coordinateHelper;if(b.isDraped){const y=e.toXYZ(e.pointToVector(g));c=B.projectPoint(c,y,C.sv3d.get());c=M.geodesicDistance(c,y,e.spatialReference);if(null!=c){a=k.createLength(c.value*Math.sign(a),c.unit);break a}}a=k.createLength(a*A.getMetersPerUnitForSR(g.spatialReference),"meters")}d.distance=a}}b=b.operations?.data.geometry;d.area="polygon"===b?.type?
v.autoArea2D(b):null;d.totalLength="polyline"===b?.type?p.autoLength2D(b):null;d.sketchOptions=f;return d};l.getUpdatedTranslateObjectTooltipInfo=function(b,a,{sketchOptions:f,tooltipInfos:d}){let e=null;switch(b){case q.ManipulationType.XY:e=d.translate;r(e,a,(g,c)=>p.autoDistanceBetweenPoints2D(g,c));break;case q.ManipulationType.XY_AXIS:e=d.translateXY;r(e,a,(g,c)=>k.scale(p.autoDistanceBetweenPoints2D(g,c),D.axisConstrainedDragSign(a)));break;case q.ManipulationType.Z:e=d.translateZ,r(e,a,L.verticalSignedDistanceBetweenPoints)}e.sketchOptions=
f;return e};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});