// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("../../../../core/Error ../../../../core/events ../../../../core/Logger ../../../../core/maybe ../../../../core/perspectiveUtils ../../../../core/reactiveUtils ../../../../core/libs/gl-matrix-2/factories/mat3f64 ../../../../core/libs/gl-matrix-2/math/vec2 ../../../../core/libs/gl-matrix-2/factories/vec2f64 ../../../../symbols/cim/enums ../DisplayObject ./animatedFormats/utils ../../../webgl/BufferObject ../../../webgl/enums ../../../webgl/Texture ../../../webgl/TextureDescriptor ../../../webgl/VertexArrayObject".split(" "),
function(C,D,E,r,F,f,G,H,I,q,J,K,t,m,u,L,M){function N(a){return a?{...a,playAnimation:a.playing,repeatType:a.repeatType?O[a.repeatType]:void 0}:{}}const P=[1,1],k=G.create(),O={none:q.AnimatedSymbolRepeatType.None,loop:q.AnimatedSymbolRepeatType.Loop,oscillate:q.AnimatedSymbolRepeatType.Oscillate};class Q extends J.DisplayObject{constructor(a){super();this.elementView=a;this.isWrapAround=!1;this.wrapAroundShift=0;this.perspectiveTransform=I.create();this._playHandle=null;this._vertices=new Float32Array(20);
this._handles=[];this._handles.push(f.watch(()=>this.elementView.element.opacity,c=>this.opacity=c,f.initial),f.watch(()=>[this.elementView.coords],()=>{this.requestRender()},f.initial),f.watch(()=>["animationOptions"in this.elementView.element&&this.elementView.element.animationOptions],()=>{this._playHandle?.remove();this.texture=r.disposeMaybe(this.texture);this.requestRender()},f.initial),f.when(()=>this.elementView.element.loaded,()=>{const c=this.elementView.element;this.ready();"video"===c.type&&
null!=c.content&&this._handles.push(D.on(c.content,"play",()=>this.requestRender()))},f.initial));a.element.load().catch(c=>{E.getLogger("esri.views.2d.layers.MediaLayerView2D").error(new C("element-load-error","Element cannot be displayed",{element:a,error:c}))})}getMesh(a){throw Error("Method not implemented.");}destroy(){this._playHandle?.remove();this._handles.forEach(a=>a.remove());this.texture=r.disposeMaybe(this.texture)}get textureSize(){return P}get dvsMat3(){return this.parent.dvsMat3}beforeRender(a){const {context:c}=
a,b=this.elementView.element.content;if(null!=b){var d=b instanceof HTMLImageElement;const g=b instanceof HTMLVideoElement;var h=d?b.naturalWidth:g?b.videoWidth:b.width;d=d?b.naturalHeight:g?b.videoHeight:b.height;this._updatePerspectiveTransform(h,d);if(this.texture)g&&!b.paused&&(this.texture.setData(b),this.requestRender(),this.texture.generateMipmap());else{const e=new L.TextureDescriptor;e.wrapMode=m.TextureWrapMode.CLAMP_TO_EDGE;e.preMultiplyAlpha=!0;e.width=h;e.height=d;"getFrame"in b?(h=l=>
{this.texture?this.texture.setData(l):this.texture=new u.Texture(c,e,l);this.requestRender()},"animationOptions"in this.elementView.element&&(this._playHandle=K.play(b,N(this.elementView.element.animationOptions),null,h))):this.texture=new u.Texture(c,e,b);this.texture.generateMipmap();g&&!b.paused&&this.requestRender()}}super.beforeRender(a)}_createTransforms(){return null}draw(a){a.drawArrays(m.PrimitiveType.TRIANGLE_STRIP,0,4)}updateDrawCoords(a,c,b,d){const {coords:h,bounds:g}=this.elementView;
if(null!=h&&null!=g){var [e,l,v,w]=h.rings[0];b=this._vertices;var {x:n,y:p}=a;b.set([l[0]-n,l[1]-p,e[0]-n,e[1]-p,v[0]-n,v[1]-p,w[0]-n,w[1]-p]);a=c;if(d){const [x,,y]=g,{worldWidth:z,xBounds:R}=d,[A,B]=R;x<A&&y>A?a=z:y>B&&x<B&&(a=-z)}this.wrapAroundShift=a;this.isWrapAround=0!==a}}getVAO(a,c,b){if(null==this.elementView.coords)return null;var d=this._vertices;this._vao?this._geometryVbo.setData(d):(this._geometryVbo=t.BufferObject.createVertex(a,m.Usage.DYNAMIC_DRAW,d),d=t.BufferObject.createVertex(a,
m.Usage.STATIC_DRAW,new Uint16Array([0,0,0,1,1,0,1,1,1,1,0,0,0,0,0,1,1,0,1,1])),this._vao=new M.VertexArrayObject(a,b,c,{geometry:this._geometryVbo,tex:d}));return this._vao}_updatePerspectiveTransform(a,c){const b=this._vertices;F.getProjectiveTransform(k,[0,0,a,0,0,c,a,c],[b[0],b[1],b[4],b[5],b[2],b[3],b[6],b[7]]);H.set(this.perspectiveTransform,k[6]/k[8]*a,k[7]/k[8]*c)}}return Q});