// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../core/asyncUtils ../../../core/handleUtils ../../../core/mathUtils ../../../core/quantityUtils ../../../core/unitUtils ../../../chunks/vec32 ../../../core/libs/gl-matrix-2/factories/vec3f64 ../../../geometry/coordinateFormatter ../../../geometry/Point ../../../geometry/support/MeshTransform ../../../geometry/support/meshVertexSpaceUtils ../../../geometry/support/spatialReferenceUtils ../../../geometry/support/webMercatorUtils ../keybindings ./fields/parsingAndFormattingUtils ../../support/angularMeasurementUtils".split(" "),
function(h,x,y,p,q,G,m,k,r,H,I,t,J,u,K,z,v){function A(a,b){const {x:c,y:d,z:e}=b,{x:f,y:g,z:l}=B(a,b.spatialReference);a=null==f||p.floatEqualUlp(f,c)?0:f-c;b=null==g||p.floatEqualUlp(g,d)?0:g-d;const n=null==l||null==e||p.floatEqualUlp(l,e)?0:l-e;return{dx:a,dy:b,dz:n}}function B(a,b){let c,d;a.geographic?(c=v.getDegreesGeographic(a.longitude.actual),d=v.getDegreesGeographic(a.latitude.actual),J.isWebMercator(b)&&(null!=c&&null!=d?[c,d]=u.lngLatToXY(c,d,w):null!=c?c=u.lngLatToXY(c,0,w)[0]:null!=
d&&(d=u.lngLatToXY(0,d,w)[1])),a=a.elevation.actual,b=G.verticalLengthUnitFromSpatialReference(b),b=null!=b&&null!=a?q.valueInUnit(a,b):void 0):(c=a.x.actual?.value,d=a.y.actual?.value,b=a.elevation.actual?.value);return{x:c,y:d,z:b}}function C(a){return m.equals(a,k.UNIT_Z)?1:m.equals(a,L)?-1:null}function M(a){const b=a?.sketchOptions;if(!b)return!1;const {inputEnabled:c,visibleElements:d}=b.tooltips;return c&&!0===a.editableFields.some(({name:e})=>"x"===e||"y"===e?d.coordinates:d[e])}function D(a,
b){if(b&&"geographic"in b){var c=a.clipboardData?.getData("text");if(c)if(b.geographic){if(c=z.parseLatitudeLongitude(c))b.longitude.applyValue(c.longitude),b.latitude.applyValue(c.latitude),a.stopPropagation(),a.preventDefault()}else if(c=z.parseXY(c))b.x.applyValue(c.x),b.y.applyValue(c.y),a.stopPropagation(),a.preventDefault()}}const w=[0,0],L=m.negate(k.create(),k.UNIT_Z);h.connectPasteEvent=function(a){let b=null;return y.handlesGroup([a.on("paste",async c=>{b?.abort();b=x.createTask(async()=>
{r.isLoaded()||await r.load();D(c,a.info)})}),x.createTask(()=>r.load()),y.makeHandle(()=>b?.abort())])};h.enterInputModeIfAvailable=function(a,b){return"key-down"===a.type&&a.key===K.tooltipKeys.enterInputMode&&b&&M(b.info)?(b.enterInputMode(),a.stopPropagation(),!0):!1};h.getXYZDeltasFromTooltipInfo=A;h.pasteLocation=D;h.updateMeshOriginFromTooltipInfo=function(a,b,c){if(b&&t.isRelativeVertexSpace(b.vertexSpace)){var {origin:d,spatialReference:e}=b,{x:f,y:g,z:l}=B(a,e),{dx:n,dy:E,dz:F}=A(a,d);if(0!==
n||0!==E||0!==F)c.onMoveStart?.(),b.centerAt(new H({x:f??d.x,y:g??d.y,z:l??d.z,spatialReference:e})),c.onMove?.(n,E,F),c.onMoveStop?.()}};h.updateMeshTransformFromTooltipInfo=function(a,b,c){if(b&&t.isRelativeVertexSpace(b.vertexSpace)){b=b.transform??(b.transform=new I);var {rotationAngle:d,rotationAxis:e}=b,f=v.getDegreesArithmetic(a.orientation.actual),g=C(e);null!=f&&null!=g&&f!==d&&(c?.onRotateStart?.(d),f*=g,b.rotationAngle=f,c?.onRotate?.(f),c?.onRotateStop?.(f));f=a.scale.actual?.value;g=
b?Math.max(...b.scale):1;null!=f&&f!==g&&({scale:a}=b,c?.onScaleStart?.(a[0],a[1],a[2]),0===g?a=k.clone(k.ONES):(f/=g,a=m.scale(k.create(),a,f)),b.scale=a,c?.onScale?.(a[0],a[1],a[2]),c?.onScaleStop?.(a[0],a[1],a[2]))}};h.updateTooltipInfoFromMeshTransform=function(a,b){const c=t.isRelativeVertexSpace(b.vertexSpace),{scale:d,orientation:e}=a;({transform:a}=b);a?(b=C(a.rotationAxis),b=null!=b?b*a.rotationAngle:null):b=0;c&&null!=b?(e.actual=q.createAngle(b,"degrees","arithmetic"),e.visible=!0):(e.actual=
null,e.visible=!1);c?(d.actual=q.createScalar(a?Math.max(...a.scale):1),d.visible=!0):(d.actual=null,d.visible=!1)};Object.defineProperty(h,Symbol.toStringTag,{value:"Module"})});