// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../../core/has ../../../../../core/lang ../../../../../layers/support/arcgisLayerUrl ./featureReductionUtils ./featureServiceUtils ./floorFilterUtils ./geometryUtils ./labelingUtils ../schema/SourceSchema ../schema/processor/SimpleProcessorSchema ../support/rendererUtils".split(" "),function(u,l,y,z,v,A,m,B,n,C,D,E){class F{constructor(b){this.layer=b}getLabelingDeconflictionInfo(b){const a=this.layer;b=n.getFeatureReductionDeconflictionEnabled(a,b)??n.getLayerDeconflictionEnabled(a);
return[{vvEvaluators:{0:n.createLabelVVEvaluator(a.renderer)},deconflictionEnabled:b}]}async createServiceOptions(b){var a=this.layer;const {capabilities:c,objectIdField:d,globalIdField:e,orderBy:f,refreshInterval:k}=a,g=a.fieldsIndex.toJSON(),p=g.fields,q=B.getEffectiveGeometryType(a),r=a.timeInfo?.toJSON(),t=a.spatialReference.toJSON(),w=y.clone(this.layer.parsedUrl);let x=this.layer.objectIdField;if(f?.length){var h=!f[0].valueExpression&&f[0].field;h&&(x=h)}h=0<k;a=(h=l("featurelayer-snapshot-enabled")&&
"point"===a.geometryType&&c?.query.supportsPagination&&!c?.operations.supportsEditing&&!h)&&A.exceedsMinimumSnapshotCoverage(b,a.fullExtent);const G=z.isHostedAgolService(w.path);return{type:"feature-service",source:w,isSourceHosted:G,orderByFields:x,outSpatialReference:b.spatialReference.toJSON(),metadata:{globalIdField:e,fields:p,fieldsIndex:g,geometryType:q,objectIdField:d,timeInfo:r,spatialReference:t,timeReferenceUnknownClient:!1,subtypeField:null,subtypes:null,typeIdField:null,types:null},queryMetadata:{maxRecordCount:c.query.maxRecordCount,
supportsCompactGeometry:c.query.supportsCompactGeometry,supportsDefaultSpatialReference:c.query.supportsDefaultSpatialReference,supportsFormatPBF:c.query.supportsFormatPBF,supportsMaxRecordCountFactor:c.query.supportsMaxRecordCountFactor,supportsQuantization:c.query.supportsQuantization,lastEditDate:null,snapshotInfo:{supportsSnapshotMinThreshold:h,supportsSnapshotMaxThreshold:a,snapshotCountThresholds:{min:l("featurelayer-snapshot-point-min-threshold"),max:l("featurelayer-snapshot-point-max-threshold")}}}}}createSourceSchema(b,
a){const {definitionExpression:c,customParameters:d,timeExtent:e}=this.layer;return C.createFeatureSourceSchema({definitionExpression:c,customParameters:d,timeExtent:e},b,a,null)}createProcessorSchema(b,a,c){const {fields:d,renderer:e,geometryType:f,labelingInfo:k,labelsVisible:g,orderBy:p,objectIdField:q}=this.layer,r={fields:d.map(t=>t.toJSON()),renderer:e?.clone(),featureReduction:v.getEffectiveFeatureReduction(this.layer,a),geometryType:f,labelingInfo:k,labelsVisible:g,objectIdField:q,orderBy:p??
"default"};return D.createSimpleProcessorSchema(b,a,r,c)}get hasRequiredSupport(){return E.isRendererSupported(this.layer.renderer)}get timeOptions(){return this.layer}hasFilters(b){return m.hasFloorFilter(this.layer,b)}addFilters(b,a){return m.addFloorFilter(this.layer,b,a)}getUpdateHashProperties(b){var a=this.layer;const {definitionExpression:c,renderer:d,outFields:e}=a,f=this.layer.labelsVisible?this.layer.labelingInfo:null,k=JSON.stringify(a.customParameters),g=v.getEffectiveFeatureReduction(a,
b);a=JSON.stringify(a.orderBy);b=m.hasFloorFilter(this.layer,b)?b.floors:null;return{outFields:e,orderBy:a,definitionExpression:c,renderer:d,labelingInfo:f,featureReduction:g,customParameters:k,floors:b}}}u.OrientedImageryLayerAdapter=F;Object.defineProperty(u,Symbol.toStringTag,{value:"Module"})});