// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/tslib.es6 ../../../../Graphic ../../../../arcade/functions/hash ../../../../core/Accessor ../../../../core/compilerUtils ../../../../core/handleUtils ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/Logger ../../../../core/RandomLCG ../../../../core/accessorSupport/decorators/subclass ../../../../core/accessorSupport/diffUtils ../../../../core/support/UpdatingHandles ../../../../geometry/support/webMercatorUtils ../../../../renderers/support/randomRotationExpression ../../../../renderers/support/renderingInfoUtils ../../../../rest/support/Query ../interfaces ./constants ./DisplayFeatureLimit ./Graphics3DCore ./Graphics3DElevationAlignment ./Graphics3DFrustumVisibility ./Graphics3DObjectStates ./Graphics3DScaleVisibility ./graphicUtils ../support/attributeUtils ../support/FeatureVisibilityFilter ../../webgl-engine/lib/basicInterfaces ../../webgl-engine/lib/UpdatePolicy".split(" "),
function(d,e,p,x,y,z,m,q,r,k,f,P,Q,A,t,B,u,C,v,D,E,F,G,H,I,J,K,L,M,w,N,l,O){d.Graphics3DFeatureProcessor=class extends y{constructor(a){super(a);this.type="graphics-3d";this._randomRotationRenderers=null;this._updatingHandles=new B.UpdatingHandles;this.timeExtentEnabled=this.elevationAlignmentEnabled=this.frustumVisibilityEnabled=this.filterVisibilityEnabled=this.scaleVisibilityEnabled=this.elevationFeatureExpressionEnabled=!1;this.setUidToIdOnAdd=!0;this.dataExtent=null;this.drapeSourceType=E.DrapeSourceType.Features;
this.preferredUpdatePolicy=O.UpdatePolicy.ASYNC;this._suspendResumeExtent=null}initialize(){const a=this.owner,b=new H.Graphics3DCore({owner:this,layer:this.layer,preferredUpdatePolicy:this.preferredUpdatePolicy,elevationFeatureExpressionEnabled:this.elevationFeatureExpressionEnabled,graphicSymbolSupported:!1,hasZ:a.hasZ,hasM:a.hasM,setUidToIdOnAdd:this.setUidToIdOnAdd,componentFactories:{deconflictor:c=>a.view.deconflictor.addGraphicsOwner(c),labeler:(c,g)=>a.view.labeler.addGraphicsOwner(c,g),elevationAlignment:this.elevationAlignmentEnabled?
(c,g)=>new I.Graphics3DElevationAlignment({graphicsCoreOwner:this,graphicsCore:c,queryGraphicUIDsInExtent:g,elevationProvider:a.view.elevationProvider}):null,scaleVisibility:this.scaleVisibilityEnabled?(c,g)=>new L.Graphics3DScaleVisibility({graphicsCoreOwner:this,layer:this.layer,queryGraphicUIDsInExtent:g,graphicsCore:c,basemapTerrain:a.view.basemapTerrain}):null,filterVisibility:(this.filterVisibilityEnabled||this.timeExtentEnabled)&&"multipatch"!==a.layer.geometryType?c=>new N.FeatureVisibilityFilter({context:{...c,
configuration:a}}):null,objectStates:c=>new K.Graphics3DObjectStates(c)}});this._set("graphicsCore",b);this.frustumVisibilityEnabled&&this._set("frustumVisibility",new J.Graphics3DFrustumVisibility({graphicsCoreOwner:this}));this.elevationAlignment&&this._updatingHandles.add(()=>this.layer.elevationInfo,(c,g)=>{t.diff(c,g)&&this._updatingHandles.addPromise(this.graphicsCore.elevationInfoChange())});this._updatingHandles.add(()=>this.layer.labelsVisible,()=>this.graphicsCore.updateVisibilityInfo());
this._updatingHandles.add(()=>this.layer.labelingInfo,(c,g)=>{t.diff(c,g)&&this.graphicsCore.updateLabelingInfo()});this._updatingHandles.add(()=>this.preferredUpdatePolicy,c=>this.graphicsCore.preferredUpdatePolicy=c);this._set("initializePromise",this._initializeAsync());this._updatingHandles.addPromise(this.initializePromise)}async _initializeAsync(){await r.logOnError(this.graphicsCore.initializePromise);const a=this.owner;this._updatingHandles.add(()=>this.renderer,b=>this._updatingHandles.addPromise(this.graphicsCore.rendererChange(b)));
this._updatingHandles.add(()=>a.fullOpacity,()=>this.graphicsCore.opacityChange());this._setupSuspendResumeExtent();this.updateClippingExtent&&(this._updatingHandles.add(()=>a.view.clippingArea,()=>this._updateClippingExtent()),this._updateClippingExtent());this.graphicsCore.startCreateGraphics();this.graphicsCore.labelsEnabled&&await r.logOnError(this.graphicsCore.updateLabelingInfo())}destroy(){this._updatingHandles.destroy();this._set("frustumVisibility",q.destroyMaybe(this.frustumVisibility));
this._set("graphicsCore",q.destroyMaybe(this.graphicsCore));this._set("owner",null)}get layer(){return this.owner.layer}get dataUpdating(){return this.graphicsCore?.dataUpdating??!1}get renderer(){const {renderer:a,objectIdField:b}=this.layer;if(!a||!b||"heatmap"===a.type||!a.visualVariables)return a;const c=a.visualVariables.findIndex(h=>"rotation"===h.type&&null!=h.valueExpression&&C.matchRandomRotationExpression(h.valueExpression)===b&&(null==h.axis||"heading"===h.axis)&&"geographic"===h.rotationType);
if(0>c)return a;const g=a.clone();g.visualVariables.splice(c,1);this._randomRotationRenderers||(this._randomRotationRenderers=new WeakMap);this._randomRotationRenderers.set(g,b);return g}get scaleVisibility(){return this.graphicsCore?.scaleVisibility}get filterVisibility(){return this.graphicsCore?.filterVisibility}get elevationAlignment(){return this.graphicsCore?.elevationAlignment}get suspendResumeExtentMode(){return this.owner.suspendResumeExtentMode??"computed"}get scaleVisibilitySuspended(){return null!=
this.scaleVisibility&&this.scaleVisibility.suspended}get suspended(){return this.owner.suspended}get legendEnabled(){return null==this.frustumVisibility||!this.frustumVisibility.suspended}get suspendInfo(){const a={};this.scaleVisibilitySuspended&&(a.outsideScaleRange=!0);null!=this.frustumVisibility&&this.frustumVisibility.suspended&&(a.outsideOfView=!0);return a}get updating(){return!!(this.graphicsCore?.updating||this.frustumVisibility?.updating||this._updatingHandles.updating)}get updatingRemaining(){return this.graphicsCore?.updatingRemaining??
0}get featureStore(){return this.graphicsCore?.featureStore}get view(){return this.owner.view}get loadedGraphics(){return this.owner.loadedGraphics}get fullOpacity(){return this.owner?.fullOpacity}get filter(){return"filter"in this.owner?this.owner.filter:null}get slicePlaneEnabled(){return this.owner.slicePlaneEnabled}get updatePolicy(){return this.owner.updatePolicy}get featureSpatialReference(){return"featureSpatialReference"in this.owner?this.owner.featureSpatialReference:this.owner.view.spatialReference}get graphics3DGraphics(){return this.graphicsCore?.graphics3DGraphics}get graphics3DGraphicsByObjectID(){return this.graphicsCore?.graphics3DGraphicsByObjectID}get symbolUpdateType(){return this.graphicsCore?.symbolUpdateType}get displayFeatureLimit(){const a=
this.view.quality,b=this.graphicsCore?.displayFeatureLimit;return 1===a?b:new G.DisplayFeatureLimit(b.maximumTotalNumberOfVertices,Math.ceil(b.maximumNumberOfFeatures*a),b.averageSymbolComplexity)}get usedMemory(){return this.graphicsCore?.usedMemory??0}get loadedFeatures(){return this.graphicsCore?.numberOfGraphics??0}get usedMemoryPerFeature(){return this.graphicsCore?.usedMemoryPerGraphic??0}get unprocessedMemoryEstimate(){return this.graphicsCore?.unprocessedMemoryEstimate??0}get performanceInfo(){return this.graphicsCore.performanceInfo}maskOccludee(a){const b=
this.graphicsCore?.objectStates;if(!b)return m.makeHandle();const {set:c,handle:g}=b.acquireSet(l.Object3DState.MaskOccludee,null);b.setUid(c,a.uid);return g}highlight(a,b){const c=this.graphicsCore?.objectStates;if(!c)return m.makeHandle();if(a instanceof D){const {set:g,handle:h}=c.acquireSet(l.Object3DState.Highlight,b);this.owner.queryObjectIds(a).then(n=>c.setObjectIds(g,n));return h}if("number"===typeof a||"string"===typeof a||a instanceof p)return this.highlight([a],b);"toArray"in a&&(a=a.toArray());
if(Array.isArray(a)&&0<a.length){if(a[0]instanceof p)if(null!=w.attributeLookup(this.layer.fieldsIndex,a[0].attributes,b))a=a.map(g=>w.attributeLookup(this.layer.fieldsIndex,g.attributes,b));else{a=a.map(n=>n.uid);const {set:g,handle:h}=c.acquireSet(l.Object3DState.Highlight,null);c.setUids(g,a);return h}if(Array.isArray(a)&&("number"===typeof a[0]||"string"===typeof a[0])){const {set:g,handle:h}=c.acquireSet(l.Object3DState.Highlight,b);c.setObjectIds(g,a);return h}}return m.makeHandle()}resetObjectStates(){this.graphicsCore?.objectStates?.reset()}whenGraphicBounds(a,
b){return this.graphicsCore?.whenGraphicBounds(a,b)}computeAttachmentOrigin(a,b){return this.graphicsCore?.computeAttachmentOrigin(a,b)}notifyGraphicGeometryChanged(a){this.graphicsCore.notifyGraphicGeometryChanged(a)}notifyGraphicVisibilityChanged(a){this.graphicsCore.notifyGraphicVisibilityChanged(a)}getRenderingInfo(a,b,c){c=v.getRenderingInfo(a,{renderer:b,arcade:c});if(c?.color){const g=c.color;g[0]/=255;g[1]/=255;g[2]/=255}null!=c&&null!=b&&this._randomRotationRenderers?.has(b)&&(b=this._randomRotationRenderers.get(b),
a=a.attributes[b],b=new x.XXH(0),b.updateFloatArray([a]),b.updateUint8Array([173]),c.heading=8.381E-8*b.digest());return c}getRenderingInfoAsync(a,b,c,g){return v.getRenderingInfoAsync(a,{renderer:b,arcade:c,...g})}getSymbolLayerSize(a,b){return this.graphicsCore?.getSymbolLayerSize(a,b)}setObjectIdVisibility(a,b){this.graphicsCore?.setObjectIdVisibility(a,b)}refreshFilter(){null!=this.filterVisibility&&this.filterVisibility.reapply()}getGraphics3DGraphicByObjectId(a){return this.graphicsCore?.getGraphics3DGraphicByObjectId(a)}_updateClippingExtent(){const a=
this.owner.view.clippingArea;this.graphicsCore.setClippingExtent(a,this.owner.view.spatialReference)&&(this.updateClippingExtent(a)||this.graphicsCore.recreateAllGraphics())}_setupSuspendResumeExtent(){(this.frustumVisibility||this.scaleVisibility)&&this.addHandles(k.watch(()=>this.suspendResumeExtentMode,()=>{this.removeHandles("suspendResumeExtentMode");switch(this.suspendResumeExtentMode){case "computed":this.addHandles([k.watch(()=>this.graphicsCore.computedExtent,a=>this._updateSuspendResumeExtent(a),
k.initial),k.watch(()=>this.graphicsCore.extentPadding,()=>this._updateSuspendResumeExtent(this.graphicsCore.computedExtent))],"suspendResumeExtentMode");break;case "data":this.addHandles([k.when(()=>this.dataExtent,a=>this._updateSuspendResumeExtent(a),k.initial),k.watch(()=>this.graphicsCore.extentPadding,()=>this._updateSuspendResumeExtent(this.dataExtent))],"suspendResumeExtentMode");break;default:z.neverReached(this.suspendResumeExtentMode)}},k.initial))}_updateSuspendResumeExtent(a){a?this._suspendResumeExtentChanged(this._extentToSuspendResumeRect(a,
this._suspendResumeExtent)):this._suspendResumeExtentChanged(null)}_extentToSuspendResumeRect(a,b){const c=this.owner.view.spatialReference;if(!a.spatialReference.equals(c)){if(!u.canProject(a,c))return;a=u.project(a,c)}return M.enlargeExtent(a,b,F.suspendResumeExtentOptimism,this.graphicsCore.extentPadding)}_suspendResumeExtentChanged(a){null!=this.frustumVisibility&&this.frustumVisibility.setExtent(a);null!=this.scaleVisibility&&this.scaleVisibility.setExtent(a)}};e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,
"type",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"owner",void 0);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"layer",null);e.__decorate([f.property({readOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"dataUpdating",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"renderer",null);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"updateClippingExtent",void 0);e.__decorate([f.property({constructOnly:!0})],
d.Graphics3DFeatureProcessor.prototype,"elevationFeatureExpressionEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"graphicsCore",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"scaleVisibilityEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"filterVisibilityEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,
"frustumVisibilityEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"elevationAlignmentEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"timeExtentEnabled",void 0);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"setUidToIdOnAdd",void 0);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"scaleVisibility",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,
"filterVisibility",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"elevationAlignment",null);e.__decorate([f.property({constructOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"frustumVisibility",void 0);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"initializePromise",void 0);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"suspendResumeExtentMode",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"dataExtent",
void 0);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"scaleVisibilitySuspended",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"suspended",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"legendEnabled",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"suspendInfo",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"updating",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,
"updatingRemaining",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"featureStore",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"view",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"loadedGraphics",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"fullOpacity",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"filter",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,
"slicePlaneEnabled",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"drapeSourceType",void 0);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"updatePolicy",null);e.__decorate([f.property()],d.Graphics3DFeatureProcessor.prototype,"preferredUpdatePolicy",void 0);e.__decorate([f.property({readOnly:!0})],d.Graphics3DFeatureProcessor.prototype,"displayFeatureLimit",null);d.Graphics3DFeatureProcessor=e.__decorate([A.subclass("esri.views.3d.layers.graphics.Graphics3DFeatureProcessor")],
d.Graphics3DFeatureProcessor);Object.defineProperty(d,Symbol.toStringTag,{value:"Module"})});