// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.30/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/tslib.es6 ../../../../Graphic ../../../../core/Accessor ../../../../core/Collection ../../../../core/handleUtils ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/reactiveUtils ../../../../core/accessorSupport/decorators/property ../../../../core/has ../../../../core/Logger ../../../../core/RandomLCG ../../../../core/accessorSupport/decorators/subclass ../../../../core/accessorSupport/diffUtils ../../../../core/support/UpdatingHandles ../../../../layers/Layer ../../../../layers/graphics/hydratedFeatures ../../../../renderers/support/renderingInfoUtils ../../../../rest/support/Query ../interfaces ./constants ./Graphics3DCore ./Graphics3DElevationAlignment ./Graphics3DFrustumVisibility ./Graphics3DObjectStates ./Graphics3DScaleVisibility ./graphicUtils ../../webgl-engine/lib/basicInterfaces ../../webgl-engine/lib/UpdatePolicy".split(" "),
function(c,d,n,t,u,l,p,v,k,f,L,M,N,w,x,y,z,A,q,B,C,D,E,F,G,H,I,J,m,K){c.GraphicsProcessor=class extends t{constructor(a){super(a);this.type="graphics-3d";this.graphicsCore=null;this.drapeSourceType=C.DrapeSourceType.Features;this.frustumVisibilityEnabled=this.scaleVisibilityEnabled=!1;this._suspendResumeExtent=null;this._updatingHandles=new y.UpdatingHandles}initialize(){const {layer:a}=this,b="effectiveScaleRange"in a?a:null,g=new E.Graphics3DCore({owner:this,layer:this.owner.layer,preferredUpdatePolicy:K.UpdatePolicy.SYNC,
graphicSymbolSupported:!0,componentFactories:{elevationAlignment:(e,h)=>new F.Graphics3DElevationAlignment({graphicsCoreOwner:this,graphicsCore:e,queryGraphicUIDsInExtent:h,elevationProvider:this.view.elevationProvider}),scaleVisibility:this.scaleVisibilityEnabled&&null!=b?(e,h)=>new I.Graphics3DScaleVisibility({graphicsCoreOwner:this,layer:b,queryGraphicUIDsInExtent:h,graphicsCore:e,basemapTerrain:this.owner.view.basemapTerrain}):null,objectStates:e=>new H.Graphics3DObjectStates(e)}});this._set("graphicsCore",
g);this.frustumVisibilityEnabled&&this._set("frustumVisibility",new G.Graphics3DFrustumVisibility({graphicsCoreOwner:this}));if("fullOpacity"in this.owner){const e=this.owner;this._updatingHandles.add(()=>e.fullOpacity,()=>this.graphicsCore.opacityChange())}"elevationInfo"in a&&this._updatingHandles.add(()=>a.elevationInfo,(e,h)=>{x.diff(e,h)&&this._updatingHandles.addPromise(this.graphicsCore.elevationInfoChange())});this._set("initializePromise",this._initializeAsync());this._updatingHandles.addPromise(this.initializePromise)}async _initializeAsync(){try{await this.graphicsCore.initializePromise}catch(a){if(v.isAbortError(a))return;
throw a;}this.destroyed||(this.addHandles(k.watch(()=>this.view.clippingArea,()=>this._updateClippingExtent(),k.sync)),this._updateClippingExtent(),this._setupSuspendResumeExtent(),this.graphicsCore.startCreateGraphics())}destroy(){this._updatingHandles.destroy();this._set("frustumVisibility",p.destroyMaybe(this.frustumVisibility));this._set("graphicsCore",p.destroyMaybe(this.graphicsCore))}get layer(){return this.owner.layer}get view(){return this.owner.view}get scaleVisibility(){return this.graphicsCore?.scaleVisibility}get elevationAlignment(){return this.graphicsCore?.elevationAlignment}get scaleVisibilitySuspended(){return!(null==
this.scaleVisibility||!this.scaleVisibility.suspended)}get frustumVisibilitySuspended(){return null!=this.frustumVisibility&&this.frustumVisibility.suspended}get suspended(){return this.owner.suspended??!1}get updating(){return!!(this.graphicsCore?.updating||null!=this.scaleVisibility&&this.scaleVisibility.updating||null!=this.frustumVisibility&&this.frustumVisibility.updating||this._updatingHandles.updating)}get graphics3DGraphics(){return this.graphicsCore?.graphics3DGraphics}get graphics3DGraphicsByObjectID(){return this.graphicsCore?.graphics3DGraphicsByObjectID}get loadedGraphics(){return this.owner.loadedGraphics}get fullOpacity(){return this.owner.fullOpacity??
1}get slicePlaneEnabled(){return this.owner.slicePlaneEnabled}get updatePolicy(){return this.owner.updatePolicy}notifyGraphicGeometryChanged(a){this.graphicsCore.notifyGraphicGeometryChanged(a)}notifyGraphicVisibilityChanged(a){this.graphicsCore.notifyGraphicVisibilityChanged(a)}getRenderingInfo(a,b,g){a=q.getRenderingInfo(a,{renderer:b,arcade:g});a?.color&&(b=a.color,b[0]/=255,b[1]/=255,b[2]/=255);return a}getRenderingInfoAsync(a,b,g,e){return q.getRenderingInfoAsync(a,{renderer:b,arcade:g,...e})}getHit(a){if(this.owner.loadedGraphics){var b=
this.owner.loadedGraphics.find(g=>g.uid===a);if(b)return b=A.hydrateGraphic(b,this.layer instanceof z?this.layer:null),{type:"graphic",graphic:b,layer:b.layer}}return null}whenGraphicBounds(a,b){return this.graphicsCore?this.graphicsCore.whenGraphicBounds(a,b):Promise.reject()}computeAttachmentOrigin(a,b){return this.graphicsCore?this.graphicsCore.computeAttachmentOrigin(a,b):null}getSymbolLayerSize(a,b){return this.graphicsCore?this.graphicsCore.getSymbolLayerSize(a,b):null}maskOccludee(a){const b=
this.graphicsCore?.objectStates;if(!b)return l.makeHandle();const {set:g,handle:e}=b.acquireSet(m.Object3DState.MaskOccludee,null);b.setUid(g,a.uid);return e}highlight(a){const b=this.graphicsCore?.objectStates;if(!b)return l.makeHandle();if(a instanceof B)return r;if("number"===typeof a||a instanceof n)return this.highlight([a]);a instanceof u&&(a=a.toArray());if(Array.isArray(a)&&0<a.length){if(a[0]instanceof n){a=a.map(h=>h.uid);const {set:g,handle:e}=b.acquireSet(m.Object3DState.Highlight,null);
b.setUids(g,a);return e}if("number"===typeof a[0]){const {set:g,handle:e}=b.acquireSet(m.Object3DState.Highlight,null);b.setObjectIds(g,a);return e}}return r}_setupSuspendResumeExtent(){const {scaleVisibility:a,frustumVisibility:b}=this;if(null!=a||null!=b){var g=({computedExtent:e,extentPadding:h})=>{this._suspendResumeExtent=J.enlargeExtent(e,this._suspendResumeExtent,D.suspendResumeExtentOptimism,h);null!=a&&a.setExtent(this._suspendResumeExtent);null!=b&&b.setExtent(this._suspendResumeExtent)};
this.addHandles(k.watch(()=>({computedExtent:this.graphicsCore?.computedExtent,extentPadding:this.graphicsCore?.extentPadding}),e=>g(e),k.syncAndInitial))}}_updateClippingExtent(){this.graphicsCore.setClippingExtent(this.view.clippingArea,this.view.spatialReference)&&this.graphicsCore.recreateAllGraphics()}};d.__decorate([f.property()],c.GraphicsProcessor.prototype,"type",void 0);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"owner",void 0);d.__decorate([f.property()],
c.GraphicsProcessor.prototype,"layer",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"view",null);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"graphicsCore",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"scaleVisibility",null);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"frustumVisibility",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"elevationAlignment",null);d.__decorate([f.property()],
c.GraphicsProcessor.prototype,"scaleVisibilitySuspended",null);d.__decorate([f.property({readOnly:!0})],c.GraphicsProcessor.prototype,"frustumVisibilitySuspended",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"suspended",null);d.__decorate([f.property({readOnly:!0})],c.GraphicsProcessor.prototype,"updating",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"loadedGraphics",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"fullOpacity",null);d.__decorate([f.property()],
c.GraphicsProcessor.prototype,"slicePlaneEnabled",null);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"drapeSourceType",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"updatePolicy",null);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"scaleVisibilityEnabled",void 0);d.__decorate([f.property({constructOnly:!0})],c.GraphicsProcessor.prototype,"frustumVisibilityEnabled",void 0);d.__decorate([f.property()],c.GraphicsProcessor.prototype,"initializePromise",
void 0);c.GraphicsProcessor=d.__decorate([w.subclass("esri.views.3d.layers.graphics.GraphicsProcessor")],c.GraphicsProcessor);const r=l.makeHandle();Object.defineProperty(c,Symbol.toStringTag,{value:"Module"})});